/**
 * Domain model entities for the knowledge graph.
 *
 * Provides {@link GraphNode}, {@link GraphEdge}, and {@link Page} as
 * multi-variant `DomainModel.make` classes with audit columns. Each entity
 * exposes `select`, `insert`, `update`, `json`, `jsonCreate`, and
 * `jsonUpdate` variants automatically.
 *
 * @example
 * ```typescript
 * import {
 *   GraphNodeEntityId,
 *   GraphEdgeEntityId,
 *   GraphNode,
 *   GraphEdge,
 *   Page,
 * } from "@beep/knowledge-graph/Models"
 *
 * // Entity IDs for table primary keys
 * GraphNodeEntityId._tag // "GraphNodeEntityId"
 * GraphEdgeEntityId.tableName // "graph_edges"
 *
 * // Domain models produce six variants
 * void GraphNode       // select
 * void GraphNode.insert
 * void GraphEdge.json
 * void Page.jsonCreate
 * ```
 *
 * @module @beep/knowledge-graph/Models
 * @since 0.0.0
 */
import { $SharedDomainId } from "@beep/identity/packages";
import { NonEmptyTrimmedStr, NonNegativeInt, SchemaUtils, Slug } from "@beep/schema";
import * as M from "@beep/schema/Model";
import { DomainModel } from "@beep/shared-domain";
import { EntityId } from "@beep/shared-domain/entity-ids/_internal/index";
import * as S from "effect/Schema";

import {
  CertaintyTier,
  KnowledgeDomain,
  KnowledgeEdgeId,
  KnowledgeEdgeKind,
  KnowledgeNodeId,
  KnowledgeNodeKind,
  PageNodeId,
} from "./Schemas.ts";

const $I = $SharedDomainId.create("knowledge-graph/Models");

// ---------------------------------------------------------------------------
// Entity IDs (auto-increment integer PKs for materialized view tables)
// ---------------------------------------------------------------------------

const $IEntityId = $SharedDomainId.create("entity-ids/knowledge_graph");
const entityIdFactory = EntityId.factory("knowledge_graph", $IEntityId);

/**
 * Auto-generated integer primary key for the `graph_nodes` table.
 *
 * Separate from the URI-shaped {@link KnowledgeNodeId} natural key so that
 * foreign-key joins stay integer-based while the natural key remains
 * deterministic and human-readable.
 *
 * @example
 * ```typescript
 * import { GraphNodeEntityId } from "@beep/knowledge-graph/Models"
 *
 * GraphNodeEntityId._tag // "GraphNodeEntityId"
 * GraphNodeEntityId.tableName // "graph_nodes"
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export const GraphNodeEntityId = entityIdFactory("GraphNodeEntityId", { tableName: "graph_nodes" });

/**
 * Type for {@link GraphNodeEntityId}.
 *
 * @since 0.0.0
 * @category models
 */
export type GraphNodeEntityId = typeof GraphNodeEntityId.Type;

/**
 * Auto-generated integer primary key for the `graph_edges` table.
 *
 * @example
 * ```typescript
 * import { GraphEdgeEntityId } from "@beep/knowledge-graph/Models"
 *
 * GraphEdgeEntityId._tag // "GraphEdgeEntityId"
 * GraphEdgeEntityId.tableName // "graph_edges"
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export const GraphEdgeEntityId = entityIdFactory("GraphEdgeEntityId", { tableName: "graph_edges" });

/**
 * Type for {@link GraphEdgeEntityId}.
 *
 * @since 0.0.0
 * @category models
 */
export type GraphEdgeEntityId = typeof GraphEdgeEntityId.Type;

// ---------------------------------------------------------------------------
// GraphNode
// ---------------------------------------------------------------------------

/**
 * Materialized graph node with audit columns.
 *
 * The `nodeId` is the URI-shaped natural key (e.g. `beep:page/foo`),
 * generated by the application rather than the database, so it uses
 * `M.GeneratedByApp`. The DomainModel factory auto-injects `createdAt`,
 * `updatedAt`, `deletedAt`, `createdBy`, `updatedBy`, `deletedBy`,
 * `version`, and `source` audit columns.
 *
 * @example
 * ```typescript
 * import { GraphNode } from "@beep/knowledge-graph/Models"
 *
 * // select variant (default)
 * // GraphNode.make({ nodeId, kind, domain, displayLabel, certainty, body, lastSequence, ... })
 *
 * // insert variant
 * // GraphNode.insert.make({ nodeId, kind, domain, displayLabel, certainty, body, lastSequence, ... })
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class GraphNode extends DomainModel.make<GraphNode>($I`GraphNodeModel`)(
  {
    nodeId: M.GeneratedByApp(KnowledgeNodeId),
    kind: KnowledgeNodeKind,
    domain: KnowledgeDomain,
    displayLabel: NonEmptyTrimmedStr,
    certainty: CertaintyTier,
    body: S.Record(S.String, S.Unknown),
    tags: S.Array(NonEmptyTrimmedStr).pipe(S.optionalKey, SchemaUtils.withKeyDefaults([])),
    aliases: S.Array(NonEmptyTrimmedStr).pipe(S.optionalKey, SchemaUtils.withKeyDefaults([])),
    lastSequence: NonNegativeInt,
  },
  $I.annote("GraphNodeModel", {
    description: "Materialized graph node with audit columns.",
  })
) {}

// ---------------------------------------------------------------------------
// GraphEdge
// ---------------------------------------------------------------------------

/**
 * Materialized graph edge with audit columns.
 *
 * Connects two {@link GraphNode}s via their URI-shaped `KnowledgeNodeId`.
 * The `edgeId` is deterministically derived from the source, target, and
 * edge kind, ensuring idempotent re-indexing.
 *
 * @example
 * ```typescript
 * import { GraphEdge } from "@beep/knowledge-graph/Models"
 *
 * // GraphEdge.make({ edgeId, sourceNodeId, targetNodeId, kind, displayLabel, certainty, lastSequence, ... })
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class GraphEdge extends DomainModel.make<GraphEdge>($I`GraphEdgeModel`)(
  {
    edgeId: M.GeneratedByApp(KnowledgeEdgeId),
    sourceNodeId: KnowledgeNodeId,
    targetNodeId: KnowledgeNodeId,
    kind: KnowledgeEdgeKind,
    displayLabel: NonEmptyTrimmedStr,
    certainty: CertaintyTier,
    lastSequence: NonNegativeInt,
  },
  $I.annote("GraphEdgeModel", {
    description: "Materialized graph edge with audit columns.",
  })
) {}

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

/**
 * A vault page document with frontmatter metadata.
 *
 * This is the domain model for `.beep/vault/pages/{slug}.md` files,
 * separate from the graph projection. When a page is saved, an indexer
 * projects it into one or more {@link GraphNode} and {@link GraphEdge}
 * records.
 *
 * @example
 * ```typescript
 * import { Page } from "@beep/knowledge-graph/Models"
 *
 * // Page.make({ id: "beep:page/design-decisions" as any, slug: "design-decisions" as any, title: "Design Decisions" })
 * ```
 *
 * @category models
 * @since 0.0.0
 */
export class Page extends DomainModel.make<Page>($I`PageModel`)(
  {
    id: M.GeneratedByApp(PageNodeId),
    slug: Slug,
    title: NonEmptyTrimmedStr,
    domain: KnowledgeDomain.pipe(S.optionalKey, SchemaUtils.withKeyDefaults("general")),
    certainty: CertaintyTier.pipe(S.optionalKey, SchemaUtils.withKeyDefaults(CertaintyTier.make(1))),
    tags: S.Array(NonEmptyTrimmedStr).pipe(S.optionalKey, SchemaUtils.withKeyDefaults([])),
    aliases: S.Array(NonEmptyTrimmedStr).pipe(S.optionalKey, SchemaUtils.withKeyDefaults([])),
    outboundLinks: S.Array(NonEmptyTrimmedStr).pipe(S.optionalKey, SchemaUtils.withKeyDefaults([])),
    excerpt: S.String.pipe(S.optionalKey, SchemaUtils.withKeyDefaults("")),
  },
  $I.annote("PageModel", {
    description: "Vault page document with frontmatter metadata.",
  })
) {}
