/**
 * Internal schema module support.
 *
 * @packageDocumentation
 * @since 0.0.0
 */

import { SchemaTransformation as Transformation } from "effect";
import * as O from "effect/Option";
import * as P from "effect/Predicate";
import * as S from "effect/Schema";
import { Field, fieldEvolve } from "./Model.variants.ts";
import type { TUnsafe } from "@beep/types";
import type * as VariantSchema from "../VariantSchema/index.ts";
import type { VariantsDatabase } from "./Model.variants.ts";
/**
 * Interface for a database-generated field present in `select`, `update`, and `json` variants.
 *
 * @since 0.0.0
 * @category models
 */
export interface Generated<S extends S.Top>
  extends VariantSchema.Field<{
    readonly select: S;
    readonly update: S;
    readonly json: S;
  }> {}

/**
 * A field that represents a column generated by the database.
 *
 * Available for selection, update, and json, but omitted from insertion.
 *
 * @example
 * ```ts
 * import * as S from "effect/Schema"
 * import * as Model from "@beep/schema/Model"
 *
 * const GroupId = S.Finite.pipe(S.brand("GroupId"))
 *
 * class Group extends Model.Class<Group>("Group")({}) {}
 *
 * console.log(Group)
 * ```
 *
 * @since 0.0.0
 * @category constructors
 */
export const Generated = <S extends S.Top>(schema: S): Generated<S> =>
  Field({
    select: schema,
    update: schema,
    json: schema,
  });

/**
 * Interface for an application-generated field present in `select`, `insert`, `update`, and `json` variants.
 *
 * @since 0.0.0
 * @category models
 */
export interface GeneratedByApp<S extends S.Top>
  extends VariantSchema.Field<{
    readonly select: S;
    readonly insert: S;
    readonly update: S;
    readonly json: S;
  }> {}

/**
 * A field generated by the application at runtime.
 *
 * Present in all database variants and `json`, but absent from `jsonCreate`
 * and `jsonUpdate` because the server assigns the value.
 *
 * @example
 * ```ts
 * import * as S from "effect/Schema"
 * import * as Model from "@beep/schema/Model"
 *
 * const field = Model.GeneratedByApp(S.String)
 * console.log(S.isSchema(field.schemas.select))
 * ```
 *
 * @since 0.0.0
 * @category constructors
 */
export const GeneratedByApp = <S extends S.Top>(schema: S): GeneratedByApp<S> =>
  Field({
    select: schema,
    insert: schema,
    update: schema,
    json: schema,
  });

/**
 * Interface for a sensitive field excluded from all JSON variants.
 *
 * @since 0.0.0
 * @category models
 */
export interface Sensitive<S extends S.Top>
  extends VariantSchema.Field<{
    readonly select: S;
    readonly insert: S;
    readonly update: S;
  }> {}

/**
 * A field for sensitive values that must never appear in JSON API responses.
 *
 * Present in `select`, `insert`, and `update` only.
 *
 * @example
 * ```ts
 * import * as S from "effect/Schema"
 * import * as Model from "@beep/schema/Model"
 *
 * class User extends Model.Class<User>("User")({}) {}
 *
 * console.log(User)
 * ```
 *
 * @since 0.0.0
 * @category constructors
 */
export const Sensitive = <S extends S.Top>(schema: S): Sensitive<S> =>
  Field({
    select: schema,
    insert: schema,
    update: schema,
  });

/**
 * Schema that decodes an optional nullable key into an `Option`.
 *
 * @example
 * ```ts
 * import * as Schema from "effect/Schema"
 * import * as Model from "@beep/schema/Model"
 *
 * const field: Model.optionalOption<typeof Schema.String> =
 *   Model.optionalOption(Schema.String)
 *
 * console.log(field)
 * ```
 *
 * @since 0.0.0
 * @category models
 */
export interface optionalOption<S extends S.Top>
  extends S.decodeTo<S.Option<S.toType<S>>, S.optionalKey<S.NullOr<S>>> {}

/**
 * Build a schema that decodes an optional nullable JSON key into an `Option`.
 *
 * @example
 * ```ts
 * import * as Schema from "effect/Schema"
 * import * as Model from "@beep/schema/Model"
 *
 * const opt = Model.optionalOption(Schema.Finite)
 * console.log(opt)
 * ```
 *
 * @since 0.0.0
 * @category constructors
 */
export const optionalOption = <S extends S.Top>(schema: S): optionalOption<S> =>
  S.NullOr(schema).pipe(
    S.optionalKey,
    S.decodeTo(
      S.toType(schema).pipe(S.Option),
      Transformation.transformOptional<O.Option<S["Type"]>, S["Type"] | null>({
        decode: (oe) => oe.pipe(O.filter(P.isNotNull), O.some),
        encode: O.flatten,
      }) as TUnsafe.Any
    )
  );

/**
 * Convert a field to one that is optional for all variants.
 *
 * For the database variants, it will accept `null`able values.
 * For the JSON variants, it will also accept missing keys.
 *
 * @example
 * ```ts
 * import * as Schema from "effect/Schema"
 * import * as Model from "@beep/schema/Model"
 *
 * const opt: Model.FieldOption<typeof Schema.String> =
 *   Model.FieldOption(Schema.String)
 *
 * console.log(opt)
 * ```
 *
 * @since 0.0.0
 * @category models
 */
export interface FieldOption<S extends S.Top>
  extends VariantSchema.Field<{
    readonly select: S.OptionFromNullOr<S>;
    readonly insert: S.OptionFromNullOr<S>;
    readonly update: S.OptionFromNullOr<S>;
    readonly json: optionalOption<S>;
    readonly jsonCreate: optionalOption<S>;
    readonly jsonUpdate: optionalOption<S>;
  }> {}

/**
 * Convert a field to one that is optional for all variants.
 *
 * For the database variants, it will accept `null`able values.
 * For the JSON variants, it will also accept missing keys.
 *
 * @example
 * ```ts
 * import * as Schema from "effect/Schema"
 * import * as Model from "@beep/schema/Model"
 *
 * const opt = Model.FieldOption(Schema.String)
 * console.log(opt)
 * ```
 *
 * @since 0.0.0
 * @category constructors
 */
export const FieldOption: <Field extends VariantSchema.Field<TUnsafe.Any> | S.Top>(
  self: Field
) => Field extends S.Top
  ? FieldOption<Field>
  : Field extends VariantSchema.Field<infer S>
    ? VariantSchema.Field<{
        readonly [K in keyof S]: S[K] extends S.Top
          ? K extends VariantsDatabase
            ? S.OptionFromNullOr<S[K]>
            : optionalOption<S[K]>
          : never;
      }>
    : never = fieldEvolve({
  select: S.OptionFromNullOr,
  insert: S.OptionFromNullOr,
  update: S.OptionFromNullOr,
  json: optionalOption,
  jsonCreate: optionalOption,
  jsonUpdate: optionalOption,
}) as TUnsafe.Any;
