name: Setup
description: Perform standard setup and install dependencies using Bun.
inputs:
  node-version:
    description: The version of Node.js to install
    required: true
    default: 20.14.0

runs:
  using: composite
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version-file: .bun-version
    - name: Install bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}
        cache: npm
    - name: Install dependencies
      shell: bash
      run: bun install
