// Package rules contains all Effect diagnostic rule implementations and the registry.
package rules

import (
	"github.com/effect-ts/tsgo/internal/rule"
)

// All is the list of all diagnostic rules.
// Add new rules here explicitly - no init() magic.
var All = []rule.Rule{
	FloatingEffect,
	MissingEffectError,
	MissingEffectContext,
	MissingReturnYieldStar,
	MissingStarInYieldEffectGen,
	CatchUnfailableEffect,
	CatchAllToMapError,
	EffectFnIife,
	TryCatchInEffectGen,
	UnnecessaryPipe,
	ReturnEffectInGen,
	UnnecessaryPipeChain,
	EffectSucceedWithVoid,
	UnnecessaryEffectGen,
	EffectMapVoid,
	UnnecessaryFailYieldableError,
	EffectInVoidSuccess,
	EffectInFailure,
	UnknownInEffectCatch,
	GlobalErrorInEffectCatch,
	GlobalErrorInEffectFailure,
	CryptoRandomUUID,
	CryptoRandomUUIDInEffect,
	GlobalFetch,
	GlobalFetchInEffect,
	ProcessEnv,
	ProcessEnvInEffect,
	GlobalConsole,
	GlobalConsoleInEffect,
	GlobalDate,
	GlobalDateInEffect,
	GlobalRandom,
	GlobalRandomInEffect,
	GlobalTimers,
	GlobalTimersInEffect,
	RunEffectInsideEffect,
	PreferSchemaOverJson,
	EffectGenUsesAdapter,
	EffectFnImplicitAny,
	StrictBooleanExpressions,
	AnyUnknownInErrorContext,
	AsyncFunction,
	ScopeInLayerEffect,
	StrictEffectProvide,
	MultipleEffectProvide,
	MissingLayerContext,
	LayerMergeAllWithDependencies,
	SchemaStructWithTag,
	SchemaSyncInEffect,
	SchemaUnionOfLiterals,
	MissingEffectServiceDependency,
	LeakingRequirements,
	LazyPromiseInEffectSync,
	NestedEffectGenYield,
	UnnecessaryArrowBlock,
	InstanceOfSchema,
	GenericEffectServices,
	OverriddenSchemaConstructor,
	RedundantSchemaTagIdentifier,
	ClassSelfMismatch,
	EffectFnOpportunity,
	NonObjectEffectServiceType,
	DeterministicKeys,
	MissedPipeableOpportunity,
	DuplicatePackage,
	EffectDoNotation,
	EffectMapFlatten,
	ExtendsNativeError,
	NodeBuiltinImport,
	NewPromise,
	OutdatedApi,
	ServiceNotAsClass,
}
