/**
 * Generated ACP protocol schema and metadata modules.
 *
 * @packageDocumentation
 * @since 0.0.0
 */

// This file is generated by the @beep/acp package. Do not edit manually.
// Current ACP schema release: v0.11.3

import { $AcpId } from "@beep/identity";

const $I = $AcpId.create("_generated/meta.gen");
void $I;

/**
 * Generated ACP agent method lookup table.
 *
 * @example
 * ```ts
 * import { AGENT_METHODS } from "@beep/acp/schema"
 *
 * console.log(AGENT_METHODS)
 * ```
 *
 * @category constants
 * @since 0.0.0
 */
export const AGENT_METHODS = {
  authenticate: "authenticate",
  initialize: "initialize",
  logout: "logout",
  session_cancel: "session/cancel",
  session_close: "session/close",
  session_fork: "session/fork",
  session_list: "session/list",
  session_load: "session/load",
  session_new: "session/new",
  session_prompt: "session/prompt",
  session_resume: "session/resume",
  session_set_config_option: "session/set_config_option",
  session_set_mode: "session/set_mode",
  session_set_model: "session/set_model",
} as const;

/**
 * Generated ACP client method lookup table.
 *
 * @example
 * ```ts
 * import { CLIENT_METHODS } from "@beep/acp/schema"
 *
 * console.log(CLIENT_METHODS)
 * ```
 *
 * @category constants
 * @since 0.0.0
 */
export const CLIENT_METHODS = {
  fs_read_text_file: "fs/read_text_file",
  fs_write_text_file: "fs/write_text_file",
  session_elicitation: "session/elicitation",
  session_elicitation_complete: "session/elicitation/complete",
  session_request_permission: "session/request_permission",
  session_update: "session/update",
  terminal_create: "terminal/create",
  terminal_kill: "terminal/kill",
  terminal_output: "terminal/output",
  terminal_release: "terminal/release",
  terminal_wait_for_exit: "terminal/wait_for_exit",
} as const;

/**
 * Generated ACP protocol version.
 *
 * @example
 * ```ts
 * import { PROTOCOL_VERSION } from "@beep/acp/schema"
 *
 * console.log(PROTOCOL_VERSION)
 * ```
 *
 * @category constants
 * @since 0.0.0
 */
export const PROTOCOL_VERSION = 1 as const;
