remote_theme: mikearnaldi/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  '@beep/professional-desktop on GitHub':
    - 'https://github.com/kriegcloud/beep-effect/tree/main/apps/professional-desktop'
