import type { RcFile } from "syncpack";

const config = {
  source: [
    "package.json",
    "infra/package.json",
    "packages/_internal/*/package.json",
    "packages/foundation/capability/*/package.json",
    "packages/foundation/modeling/*/package.json",
    "packages/foundation/primitive/*/package.json",
    "packages/foundation/ui-system/*/package.json",
    "packages/shared/client/package.json",
    "packages/shared/domain/package.json",
    "packages/shared/server/package.json",
    "packages/shared/tables/package.json",
    "packages/shared/ui/package.json",
    "packages/tooling/library/*/package.json",
    "packages/tooling/policy-pack/*/package.json",
    "packages/tooling/test-kit/*/package.json",
    "packages/tooling/tool/*/package.json",
    "apps/oip-web/package.json",
    "apps/professional-desktop/package.json",
    "apps/storybook/package.json",
    "packages/agents/domain/package.json",
    "packages/agents/use-cases/package.json",
    "packages/agents/client/package.json",
    "packages/agents/server/package.json",
    "packages/epistemic/domain/package.json",
    "packages/epistemic/tables/package.json",
    "packages/epistemic/use-cases/package.json",
    "packages/epistemic/server/package.json",
    "packages/law-practice/domain/package.json",
    "packages/law-practice/use-cases/package.json",
    "packages/law-practice/server/package.json",
    "packages/workspace/domain/package.json",
    "packages/shared/use-cases/package.json",
    "packages/shared/config/package.json",
    "packages/drivers/drizzle/package.json",
    "packages/drivers/duckdb/package.json",
    "packages/drivers/face-detection/package.json",
    "packages/drivers/ffmpeg/package.json",
    "packages/drivers/postgres/package.json",
    "packages/drivers/anthropic/package.json",
    "packages/drivers/venice-ai/package.json",
    "packages/drivers/xai/package.json",
    "packages/drivers/acp/package.json",
    "packages/drivers/openai-compat/package.json",
    "packages/workspace/tables/package.json",
    "packages/workspace/use-cases/package.json",
    "packages/workspace/server/package.json",
    "packages/architecture-lab/domain/package.json",
    "packages/architecture-lab/use-cases/package.json",
    "packages/architecture-lab/config/package.json",
    "packages/architecture-lab/server/package.json",
    "packages/architecture-lab/tables/package.json",
    "packages/architecture-lab/client/package.json",
    "packages/architecture-lab/ui/package.json",
    "apps/architecture-lab-proof/package.json",
    "packages/drivers/runpod/package.json",
    "packages/drivers/onepassword-cli/package.json",
    "packages/drivers/discord/package.json",
    "packages/drivers/ai-provider-cli/package.json",
    "packages/drivers/sanity/package.json",
    "packages/drivers/hubspot/package.json",
    "packages/drivers/phoenix/package.json",
    "packages/drivers/konva/package.json",
    "packages/drivers/nlp-mcp/package.json",
    "packages/drivers/wink/package.json",
    "packages/drivers/tika/package.json",
    "packages/drivers/libpff/package.json",
    "packages/drivers/box/package.json",
    "packages/drivers/firecrawl/package.json",
    "packages/drivers/uspto/package.json",
    "packages/drivers/pglite/package.json",
    "packages/drivers/m365/package.json",
    "packages/drivers/m365-mcp/package.json",
  ],
  customTypes: {
    catalog: {
      path: "catalog",
      strategy: "versionsByName",
    },
  },
  versionGroups: [
    {
      label: "Catalog (Pinned)",
      dependencies: ["**"],
      dependencyTypes: ["catalog"],
      preferVersion: "highestSemver",
    },
    {
      label: "Workspace packages use workspace: protocol",
      dependencies: ["@beep/**"],
      packages: ["**"],
      dependencyTypes: ["dev", "prod"],
      pinVersion: "workspace:^",
    },
    {
      label: "Peer dependencies allow broader ranges",
      dependencies: ["**"],
      dependencyTypes: ["peer"],
      isIgnored: true,
    },
    {
      label: "Root devDependencies (third-party) should use catalog references",
      dependencies: ["!@beep/**"],
      packages: ["@beep/root"],
      dependencyTypes: ["dev"],
      pinVersion: "catalog:",
    },
  ],
} satisfies RcFile;
export default config;
