config:
  opipWeb:attachProductionDomains: "false"
  opipWeb:attachStagingDomain: "true"
  opipWeb:assetsBucketName: staging-assets.opip.law
  opipWeb:awsRegion: us-east-1
  opipWeb:cloudflareZoneId: 0d26e874202f4579081926dc38b3bf80
  opipWeb:projectName: opip-web-staging
  opipWeb:productionBranch: main
  opipWeb:repository: kriegcloud/beep-effect
  opipWeb:rootDirectory: apps/opip-web
  opipWeb:stagingBranch: main
  opipWeb:stagingDomain: staging.opip.law
  opipWeb:vercelAuthenticationDeploymentType: none
  opipWeb:hubSpotAccountId: "246203876"
  opipWeb:hubSpotServiceKey:
    secure: v1:XEsDLRxOQVGaArr/:Mb2z7gccHpOZ64SCL3HGTqMt4pg+LsH3mZEObVzbWtm6o/kY0dEcCS4Iq3Z6Zn/h96AX8U70ZG7uYlVb
encryptionsalt: v1:fqQdn9tkmAc=:v1:cwXzl12rh4BfgroT:d/vugmtdMVFDl8zAdF+YOXVM7O4giw==
