/**
 * @since 0.0.0
 */

import type { TUnsafe } from "@beep/types";
import type { Brand } from "effect/Brand";
import * as DateTime from "effect/DateTime";
import * as Effect from "effect/Effect";
import * as O from "effect/Option";
import * as P from "effect/Predicate";
import * as S from "effect/Schema";
import * as Getter from "effect/SchemaGetter";
import * as Transformation from "effect/SchemaTransformation";
import * as Uuid from "uuid";
import * as VariantSchema from "./VariantSchema.ts";

const { Class, Field, FieldExcept, ClassFactory, FieldOnly, Struct, Union, extract, fieldEvolve } = VariantSchema.make({
  variants: ["select", "insert", "update", "json", "jsonCreate", "jsonUpdate"],
  defaultVariant: "select",
});

/**
 * @since 0.0.0
 * @category models
 */
export type Any = S.Top & {
  readonly fields: S.Struct.Fields;
  readonly insert: S.Top;
  readonly update: S.Top;
  readonly json: S.Top;
  readonly jsonCreate: S.Top;
  readonly jsonUpdate: S.Top;
};

/**
 * @since 0.0.0
 * @category models
 */
export type VariantsDatabase = "select" | "insert" | "update";

/**
 * @since 0.0.0
 * @category models
 */
export type VariantsJson = "json" | "jsonCreate" | "jsonUpdate";

export {
  /**
   * A base class used for creating domain model schemas.
   *
   * It supports common variants for database and JSON apis.
   *
   * @since 0.0.0
   * @category constructors
   * @example
   * ```ts
   * import * as Schema from "effect/Schema"
   * import * as Model from "@beep/schema/Model"
   *
   * export const GroupId = Schema.Number.pipe(Schema.brand("GroupId"))
   *
   * export class Group extends Model.Class<Group>("Group")({
   *   id: Model.Generated(GroupId),
   *   name: Schema.String,
   *   createdAt: Model.DateTimeInsertFromDate,
   *   updatedAt: Model.DateTimeUpdateFromDate
   * }) {}
   *
   * // schema used for selects
   * Group
   *
   * // schema used for inserts
   * Group.insert
   *
   * // schema used for updates
   * Group.update
   *
   * // schema used for json api
   * Group.json
   * Group.jsonCreate
   * Group.jsonUpdate
   *
   * // you can also turn them into classes
   * class GroupJson extends Schema.Class<GroupJson>("GroupJson")(Group.json) {
   *   get upperName() {
   *     return this.name?.toUpperCase() ?? ""
   *   }
   * }
   * ```
   */
  Class,
  /**
   * @since 0.0.0
   * @category constructors
   */
  ClassFactory,
  /**
   * @since 0.0.0
   * @category extraction
   */
  extract,
  /**
   * @since 0.0.0
   * @category fields
   */
  Field,
  /**
   * @since 0.0.0
   * @category fields
   */
  FieldExcept,
  /**
   * @since 0.0.0
   * @category fields
   */
  FieldOnly,
  /**
   * @since 0.0.0
   * @category fields
   */
  fieldEvolve,
  /**
   * @since 0.0.0
   * @category constructors
   */
  Struct,
  /**
   * @since 0.0.0
   * @category constructors
   */
  Union,
};

/**
 * @since 0.0.0
 * @category fields
 */
export const fields: <A extends VariantSchema.Struct<TUnsafe.Any>>(self: A) => A[typeof VariantSchema.TypeId] =
  VariantSchema.fields;

/**
 * @since 0.0.0
 * @category overridable
 */
export const Override: <A>(value: A) => A & Brand<"Override"> = VariantSchema.Override;

/**
 * @since 0.0.0
 * @category generated
 */
export interface Generated<S extends S.Top>
  extends VariantSchema.Field<{
    readonly select: S;
    readonly update: S;
    readonly json: S;
  }> {}

/**
 * A field that represents a column that is generated by the database.
 *
 * It is available for selection and update, but not for insertion.
 *
 * @since 0.0.0
 * @category generated
 */
export const Generated = <S extends S.Top>(schema: S): Generated<S> =>
  Field({
    select: schema,
    update: schema,
    json: schema,
  });

/**
 * @since 0.0.0
 * @category generated
 */
export interface GeneratedByApp<S extends S.Top>
  extends VariantSchema.Field<{
    readonly select: S;
    readonly insert: S;
    readonly update: S;
    readonly json: S;
  }> {}

/**
 * A field that represents a column that is generated by the application.
 *
 * It is required by the database, but not by the JSON variants.
 *
 * @since 0.0.0
 * @category generated
 */
export const GeneratedByApp = <S extends S.Top>(schema: S): GeneratedByApp<S> =>
  Field({
    select: schema,
    insert: schema,
    update: schema,
    json: schema,
  });

/**
 * @since 0.0.0
 * @category sensitive
 */
export interface Sensitive<S extends S.Top>
  extends VariantSchema.Field<{
    readonly select: S;
    readonly insert: S;
    readonly update: S;
  }> {}

/**
 * A field that represents a sensitive value that should not be exposed in the
 * JSON variants.
 *
 * @since 0.0.0
 * @category sensitive
 */
export const Sensitive = <S extends S.Top>(schema: S): Sensitive<S> =>
  Field({
    select: schema,
    insert: schema,
    update: schema,
  });

/**
 * @since 0.0.0
 * @category optional
 */
export interface optionalOption<S extends S.Top>
  extends S.decodeTo<S.Option<S.toType<S>>, S.optionalKey<S.NullOr<S>>> {}

/**
 * @since 0.0.0
 * @category optional
 */
export const optionalOption = <S extends S.Top>(schema: S): optionalOption<S> =>
  S.NullOr(schema).pipe(
    S.optionalKey,
    S.decodeTo(
      S.toType(schema).pipe(S.Option),
      Transformation.transformOptional<O.Option<S["Type"]>, S["Type"] | null>({
        decode: (oe) => oe.pipe(O.filter(P.isNotNull), O.some),
        encode: O.flatten,
      }) as TUnsafe.Any
    )
  );

/**
 * Convert a field to one that is optional for all variants.
 *
 * For the database variants, it will accept `null`able values.
 * For the JSON variants, it will also accept missing keys.
 *
 * @since 0.0.0
 * @category optional
 */
export interface FieldOption<S extends S.Top>
  extends VariantSchema.Field<{
    readonly select: S.OptionFromNullOr<S>;
    readonly insert: S.OptionFromNullOr<S>;
    readonly update: S.OptionFromNullOr<S>;
    readonly json: optionalOption<S>;
    readonly jsonCreate: optionalOption<S>;
    readonly jsonUpdate: optionalOption<S>;
  }> {}

/**
 * Convert a field to one that is optional for all variants.
 *
 * For the database variants, it will accept `null`able values.
 * For the JSON variants, it will also accept missing keys.
 *
 * @since 0.0.0
 * @category optional
 */
export const FieldOption: <Field extends VariantSchema.Field<TUnsafe.Any> | S.Top>(
  self: Field
) => Field extends S.Top
  ? FieldOption<Field>
  : Field extends VariantSchema.Field<infer S>
    ? VariantSchema.Field<{
        readonly [K in keyof S]: S[K] extends S.Top
          ? K extends VariantsDatabase
            ? S.OptionFromNullOr<S[K]>
            : optionalOption<S[K]>
          : never;
      }>
    : never = fieldEvolve({
  select: S.OptionFromNullOr,
  insert: S.OptionFromNullOr,
  update: S.OptionFromNullOr,
  json: optionalOption,
  jsonCreate: optionalOption,
  jsonUpdate: optionalOption,
}) as TUnsafe.Any;

/**
 * @since 0.0.0
 * @category booleans
 */
export interface BooleanSqlite
  extends VariantSchema.Field<{
    readonly select: S.BooleanFromBit;
    readonly insert: S.BooleanFromBit;
    readonly update: S.BooleanFromBit;
    readonly json: S.Boolean;
    readonly jsonCreate: S.Boolean;
    readonly jsonUpdate: S.Boolean;
  }> {}

/**
 * A schema for sqlite booleans that are represented as `0 | 1` in database
 * variants and `boolean` in JSON variants.
 *
 * @since 0.0.0
 * @category booleans
 */
export const BooleanSqlite: BooleanSqlite = Field({
  select: S.BooleanFromBit,
  insert: S.BooleanFromBit,
  update: S.BooleanFromBit,
  json: S.Boolean,
  jsonCreate: S.Boolean,
  jsonUpdate: S.Boolean,
});

/**
 * @since 0.0.0
 * @category date & time
 */
export interface Date extends S.decodeTo<S.instanceOf<DateTime.Utc>, S.String> {}

/**
 * A schema for a `DateTime.Utc` that is serialized as a date string in the
 * format `YYYY-MM-DD`.
 *
 * @since 0.0.0
 * @category date & time
 */
export const Date: Date = S.String.pipe(
  S.decodeTo(S.DateTimeUtc, {
    decode: Getter.dateTimeUtcFromInput().map(DateTime.removeTime),
    encode: Getter.transform(DateTime.formatIsoDate),
  })
);

/**
 * @since 0.0.0
 * @category date & time
 */
export const DateWithNow = VariantSchema.Overridable(Date, {
  defaultValue: Effect.map(DateTime.now, DateTime.removeTime),
});

/**
 * @since 0.0.0
 * @category date & time
 */
export const DateTimeWithNow = VariantSchema.Overridable(S.DateTimeUtcFromString, {
  defaultValue: DateTime.now,
});

/**
 * @since 0.0.0
 * @category date & time
 */
export const DateTimeFromDateWithNow = VariantSchema.Overridable(S.DateTimeUtcFromDate, {
  defaultValue: DateTime.now,
});

/**
 * @since 0.0.0
 * @category date & time
 */
export const DateTimeFromNumberWithNow = VariantSchema.Overridable(S.DateTimeUtcFromMillis, {
  defaultValue: DateTime.now,
});

/**
 * @since 0.0.0
 * @category date & time
 */
export interface DateTimeInsert
  extends VariantSchema.Field<{
    readonly select: S.DateTimeUtcFromString;
    readonly insert: VariantSchema.Overridable<S.DateTimeUtcFromString>;
    readonly json: S.DateTimeUtcFromString;
  }> {}

/**
 * A field that represents a date-time value that is inserted as the current
 * `DateTime.Utc`. It is serialized as a string for the database.
 *
 * It is omitted from updates and is available for selection.
 *
 * @since 0.0.0
 * @category date & time
 */
export const DateTimeInsert: DateTimeInsert = Field({
  select: S.DateTimeUtcFromString,
  insert: DateTimeWithNow,
  json: S.DateTimeUtcFromString,
});

/**
 * @since 0.0.0
 * @category date & time
 */
export interface DateTimeInsertFromDate
  extends VariantSchema.Field<{
    readonly select: S.DateTimeUtcFromDate;
    readonly insert: VariantSchema.Overridable<S.DateTimeUtcFromDate>;
    readonly json: S.DateTimeUtcFromString;
  }> {}

/**
 * A field that represents a date-time value that is inserted as the current
 * `DateTime.Utc`. It is serialized as a `Date` for the database.
 *
 * It is omitted from updates and is available for selection.
 *
 * @since 0.0.0
 * @category date & time
 */
export const DateTimeInsertFromDate: DateTimeInsertFromDate = Field({
  select: S.DateTimeUtcFromDate,
  insert: DateTimeFromDateWithNow,
  json: S.DateTimeUtcFromString,
});

/**
 * @since 0.0.0
 * @category date & time
 */
export interface DateTimeInsertFromNumber
  extends VariantSchema.Field<{
    readonly select: S.DateTimeUtcFromMillis;
    readonly insert: VariantSchema.Overridable<S.DateTimeUtcFromMillis>;
    readonly json: S.DateTimeUtcFromMillis;
  }> {}

/**
 * A field that represents a date-time value that is inserted as the current
 * `DateTime.Utc`. It is serialized as a `number`.
 *
 * It is omitted from updates and is available for selection.
 *
 * @since 0.0.0
 * @category date & time
 */
export const DateTimeInsertFromNumber: DateTimeInsertFromNumber = Field({
  select: S.DateTimeUtcFromMillis,
  insert: DateTimeFromNumberWithNow,
  json: S.DateTimeUtcFromMillis,
});

/**
 * @since 0.0.0
 * @category date & time
 */
export interface DateTimeUpdate
  extends VariantSchema.Field<{
    readonly select: S.DateTimeUtcFromString;
    readonly insert: VariantSchema.Overridable<S.DateTimeUtcFromString>;
    readonly update: VariantSchema.Overridable<S.DateTimeUtcFromString>;
    readonly json: S.DateTimeUtcFromString;
  }> {}

/**
 * A field that represents a date-time value that is updated as the current
 * `DateTime.Utc`. It is serialized as a string for the database.
 *
 * It is set to the current `DateTime.Utc` on updates and inserts and is
 * available for selection.
 *
 * @since 0.0.0
 * @category date & time
 */
export const DateTimeUpdate: DateTimeUpdate = Field({
  select: S.DateTimeUtcFromString,
  insert: DateTimeWithNow,
  update: DateTimeWithNow,
  json: S.DateTimeUtcFromString,
});

/**
 * @since 0.0.0
 * @category date & time
 */
export interface DateTimeUpdateFromDate
  extends VariantSchema.Field<{
    readonly select: S.DateTimeUtcFromDate;
    readonly insert: VariantSchema.Overridable<S.DateTimeUtcFromDate>;
    readonly update: VariantSchema.Overridable<S.DateTimeUtcFromDate>;
    readonly json: S.DateTimeUtcFromString;
  }> {}

/**
 * A field that represents a date-time value that is updated as the current
 * `DateTime.Utc`. It is serialized as a `Date` for the database.
 *
 * It is set to the current `DateTime.Utc` on updates and inserts and is
 * available for selection.
 *
 * @since 0.0.0
 * @category date & time
 */
export const DateTimeUpdateFromDate: DateTimeUpdateFromDate = Field({
  select: S.DateTimeUtcFromDate,
  insert: DateTimeFromDateWithNow,
  update: DateTimeFromDateWithNow,
  json: S.DateTimeUtcFromString,
});

/**
 * @since 0.0.0
 * @category date & time
 */
export interface DateTimeUpdateFromNumber
  extends VariantSchema.Field<{
    readonly select: S.DateTimeUtcFromMillis;
    readonly insert: VariantSchema.Overridable<S.DateTimeUtcFromMillis>;
    readonly update: VariantSchema.Overridable<S.DateTimeUtcFromMillis>;
    readonly json: S.DateTimeUtcFromMillis;
  }> {}

/**
 * A field that represents a date-time value that is updated as the current
 * `DateTime.Utc`. It is serialized as a `number`.
 *
 * It is set to the current `DateTime.Utc` on updates and inserts and is
 * available for selection.
 *
 * @since 0.0.0
 * @category date & time
 */
export const DateTimeUpdateFromNumber: DateTimeUpdateFromNumber = Field({
  select: S.DateTimeUtcFromMillis,
  insert: DateTimeFromNumberWithNow,
  update: DateTimeFromNumberWithNow,
  json: S.DateTimeUtcFromMillis,
});

/**
 * @since 0.0.0
 * @category json
 */
export interface JsonFromString<S extends S.Top>
  extends VariantSchema.Field<{
    readonly select: S.fromJsonString<S>;
    readonly insert: S.fromJsonString<S>;
    readonly update: S.fromJsonString<S>;
    readonly json: S;
    readonly jsonCreate: S;
    readonly jsonUpdate: S;
  }> {}

/**
 * A field that represents a JSON value stored as text in the database.
 *
 * The "json" variants will use the object schema directly.
 *
 * @since 0.0.0
 * @category json
 */
export const JsonFromString = <S extends S.Top>(schema: S): JsonFromString<S> => {
  const parsed = S.fromJsonString(schema);
  return Field({
    select: parsed,
    insert: parsed,
    update: parsed,
    json: schema,
    jsonCreate: schema,
    jsonUpdate: schema,
  });
};

/**
 * @since 0.0.0
 * @category uuid
 */
export interface UuidV4Insert<B extends string>
  extends VariantSchema.Field<{
    readonly select: S.brand<S.instanceOf<Uint8Array<ArrayBuffer>>, B>;
    readonly insert: VariantSchema.Overridable<S.brand<S.instanceOf<Uint8Array<ArrayBuffer>>, B>>;
    readonly update: S.brand<S.instanceOf<Uint8Array<ArrayBuffer>>, B>;
    readonly json: S.brand<S.instanceOf<Uint8Array<ArrayBuffer>>, B>;
  }> {}

/**
 * @since 0.0.0
 * @category Uint8Array
 */
export const Uint8Array: S.instanceOf<Uint8Array<ArrayBuffer>> = S.Uint8Array as S.instanceOf<
  globalThis.Uint8Array<ArrayBuffer>
>;

/**
 * @since 0.0.0
 * @category uuid
 */
export const UuidV4WithGenerate = <B extends string>(
  schema: S.brand<S.instanceOf<Uint8Array<ArrayBuffer>>, B>
): VariantSchema.Overridable<S.brand<S.instanceOf<Uint8Array<ArrayBuffer>>, B>> =>
  VariantSchema.Overridable(schema, {
    defaultValue: Effect.sync(() => Uuid.v4({}, new globalThis.Uint8Array(16))),
  });

/**
 * A field that represents a binary UUID v4 that is generated on inserts.
 *
 * @since 0.0.0
 * @category uuid
 */
export const UuidV4Insert = <const B extends string>(
  schema: S.brand<S.instanceOf<Uint8Array<ArrayBuffer>>, B>
): UuidV4Insert<B> =>
  Field({
    select: schema,
    insert: UuidV4WithGenerate(schema),
    update: schema,
    json: schema,
  });
