package cli

import (
	"fmt"
	"os/exec"
	"strings"

	"github.com/Goldziher/ai-rulez/internal/config"
	"github.com/Goldziher/ai-rulez/internal/progress"
	"github.com/samber/oops"
)

type CLIIntegrator interface {
	ToolName() string

	IsAvailable() bool

	ConfigureServer(server *config.MCPServer) error

	RemoveServer(serverName string) error
}

func ConfigureCLITools(servers []config.MCPServer) error {
	return ConfigureCLIToolsWithOutputs(servers, nil)
}

func ConfigureCLIToolsWithOutputs(servers []config.MCPServer, outputs []config.Output) error {
	if len(servers) == 0 {
		return nil
	}

	integrators := []CLIIntegrator{
		&ClaudeIntegrator{},
		&GeminiIntegrator{},
	}

	availableIntegrators := make([]CLIIntegrator, 0, len(integrators))
	for _, integrator := range integrators {
		if integrator.IsAvailable() {
			availableIntegrators = append(availableIntegrators, integrator)
		}
	}

	if len(availableIntegrators) == 0 {
		progress.PrintIfNotQuiet("ℹ️  No CLI MCP tools available (claude, gemini, etc.)\n")
		return nil
	}

	// Check which MCP formats are being generated by templates
	templateMCPFiles := getTemplateMCPFiles(outputs)

	var errors []error
	for i := range servers {
		server := &servers[i]
		if !server.IsEnabled() {
			continue
		}

		for _, integrator := range availableIntegrators {
			if shouldConfigureForTool(server, integrator.ToolName()) {
				// Skip if this server will be handled by template outputs
				if shouldSkipDueToTemplate(server, integrator.ToolName(), templateMCPFiles) {
					progress.PrintIfNotQuiet("ℹ️  Skipping CLI config for %s server '%s' (handled by template)\n",
						integrator.ToolName(), server.Name)
					continue
				}

				if err := integrator.ConfigureServer(server); err != nil {
					errorMsg := fmt.Sprintf("failed to configure %s MCP server '%s': %v",
						integrator.ToolName(), server.Name, err)
					errors = append(errors, oops.Errorf("MCP configuration error: %s", errorMsg))
					progress.PrintIfNotQuiet("❌ %s\n", errorMsg)
				} else {
					progress.PrintIfNotQuiet("✅ Configured %s MCP server: %s\n",
						integrator.ToolName(), server.Name)
				}
			}
		}
	}

	if len(errors) > 0 {
		return oops.
			With("configured_tools", len(availableIntegrators)).
			With("failed_configurations", len(errors)).
			Errorf("some MCP CLI configurations failed")
	}

	return nil
}

func shouldConfigureForTool(server *config.MCPServer, toolName string) bool {
	if len(server.Targets) == 0 {
		return true
	}

	targetPattern := fmt.Sprintf("@%s-cli", toolName)
	for _, target := range server.Targets {
		if target == targetPattern {
			return true
		}
	}

	return false
}

func isToolAvailable(toolName string) bool {
	cmd := exec.Command(toolName, "--help")
	err := cmd.Run()
	return err == nil
}

func buildEnvFlags(env map[string]string, flagPattern string) []string {
	if len(env) == 0 {
		return nil
	}

	var flags []string
	for key, value := range env {
		flags = append(flags, flagPattern, fmt.Sprintf("%s=%s", key, value))
	}
	return flags
}

// getTemplateMCPFiles returns a map of MCP files being generated by templates
func getTemplateMCPFiles(outputs []config.Output) map[string]string {
	mcpFiles := make(map[string]string)
	if outputs == nil {
		return mcpFiles
	}

	for _, output := range outputs {
		template, err := output.GetTemplate()
		if err != nil || template == nil {
			continue
		}

		templateValue := template.Value
		switch templateValue {
		case "claude-code-mcp":
			mcpFiles[".mcp.json"] = "claude"
		case "cursor-mcp":
			mcpFiles[".cursor/mcp.json"] = "cursor"
		case "windsurf-mcp":
			mcpFiles["mcp_config.json"] = "windsurf"
		case "vscode-mcp":
			mcpFiles[".vscode/mcp.json"] = "vscode"
		case "continuedev-mcp":
			mcpFiles[".continue/mcpServers/servers.yaml"] = "continue"
		case "cline-mcp":
			mcpFiles["cline_mcp_settings.json"] = "cline"
		}
	}

	return mcpFiles
}

// shouldSkipDueToTemplate checks if a server should skip CLI configuration
// because it's handled by template generation
func shouldSkipDueToTemplate(server *config.MCPServer, toolName string, templateMCPFiles map[string]string) bool {
	// Map CLI tool names to their expected MCP files
	toolMCPFiles := map[string][]string{
		"claude":   {".mcp.json"},
		"gemini":   {".gemini/settings.json"},
		"cursor":   {".cursor/mcp.json"},
		"windsurf": {"mcp_config.json"},
		"vscode":   {".vscode/mcp.json"},
		"continue": {".continue/mcpServers/servers.yaml"},
		"cline":    {"cline_mcp_settings.json"},
	}

	expectedFiles, exists := toolMCPFiles[toolName]
	if !exists {
		return false // Unknown tool, don't skip
	}

	// Check if any of this tool's expected files are being generated by templates
	for _, file := range expectedFiles {
		if _, isGenerated := templateMCPFiles[file]; isGenerated {
			// Check if this specific server should be included in this file's template
			if shouldServerBeInTemplate(server, file) {
				return true // Skip CLI configuration
			}
		}
	}

	return false
}

// shouldServerBeInTemplate checks if a server should be included in a specific template file
func shouldServerBeInTemplate(server *config.MCPServer, templateFile string) bool {
	if len(server.Targets) == 0 {
		return true // No targets means include in all outputs
	}

	// Check if the server targets this specific template file
	for _, target := range server.Targets {
		if target == templateFile {
			return true
		}
	}

	return false
}

func executeCommand(cmdArgs []string) error {
	if len(cmdArgs) == 0 {
		return oops.Errorf("empty command arguments")
	}

	allowedCommands := map[string]bool{
		"claude": true,
		"gemini": true,
	}

	if !allowedCommands[cmdArgs[0]] {
		return oops.
			With("command", cmdArgs[0]).
			Errorf("command not allowed: %s", cmdArgs[0])
	}

	cmd := exec.Command(cmdArgs[0], cmdArgs[1:]...) // #nosec G204 - cmdArgs[0] is validated against allowedCommands
	output, err := cmd.CombinedOutput()

	if err != nil {
		return oops.
			With("command", strings.Join(cmdArgs, " ")).
			With("output", string(output)).
			Wrapf(err, "command execution failed")
	}

	return nil
}
