/**
 * GENERATED FILE — do not edit by hand. Run `bun run generate`.
 *
 * Per-element metadata for the HTML AST: DOM interface, conformance tier, void /
 * raw-text classification, and (advisory) content categories.
 *
 * @packageDocumentation \@beep/html/Html.meta
 * @since 0.0.0
 */

import {$HtmlId} from "@beep/identity";
import {LiteralKit} from "@beep/schema";
import * as S from "effect/Schema";
import type * as R from "effect/Record";

const $I = $HtmlId.create("Html.meta");

/**
 * Schema describing one HTML element kind's metadata.
 *
 * @category models
 * @since 0.0.0
 */
export class HtmlElementMeta extends S.Class<HtmlElementMeta>($I`HtmlElementMeta`)({
	tag: S.String,
	interface: S.String,
	conformance: LiteralKit([
		"conforming",
		"non-conforming",
	]),
	void: S.Boolean,
	rawText: S.Boolean,
	categories: S.Array(S.String),
}, $I.annote("HtmlElementMeta", {
	description: "Metadata describing one HTML element kind.",
})) {
	static readonly define = (input: {
		readonly [tag: string]: HtmlElementMeta
	}): R.ReadonlyRecord<string, HtmlElementMeta> => {
		const schema = S.Record(S.String, HtmlElementMeta);

		return schema.make(input)
	}
}

/**
 * Metadata for every generated HTML element, keyed by tag name.
 *
 * @category models
 * @since 0.0.0
 */
export const ELEMENT_META = HtmlElementMeta.define({
	a: ({
		tag: "a",
		interface: "HTMLAnchorElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"interactive",
			"palpable",
		],
	}),
	abbr: {
		tag: "abbr",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	acronym: {
		tag: "acronym",
		interface: "HTMLElement",
		conformance: "non-conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	address: {
		tag: "address",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"palpable",
		],
	},
	applet: {
		tag: "applet",
		interface: "HTMLUnknownElement",
		conformance: "non-conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	area: {
		tag: "area",
		interface: "HTMLAreaElement",
		conformance: "conforming",
		void: true,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
		],
	},
	article: {
		tag: "article",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"sectioning",
			"palpable",
		],
	},
	aside: {
		tag: "aside",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"sectioning",
			"palpable",
		],
	},
	audio: {
		tag: "audio",
		interface: "HTMLAudioElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"embedded",
			"interactive",
			"palpable",
		],
	},
	b: {
		tag: "b",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	base: {
		tag: "base",
		interface: "HTMLBaseElement",
		conformance: "conforming",
		void: true,
		rawText: false,
		categories: ["metadata"],
	},
	basefont: {
		tag: "basefont",
		interface: "HTMLElement",
		conformance: "non-conforming",
		void: true,
		rawText: false,
		categories: [],
	},
	bdi: {
		tag: "bdi",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	bdo: {
		tag: "bdo",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	bgsound: {
		tag: "bgsound",
		interface: "HTMLUnknownElement",
		conformance: "non-conforming",
		void: true,
		rawText: false,
		categories: [],
	},
	big: {
		tag: "big",
		interface: "HTMLElement",
		conformance: "non-conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	blink: {
		tag: "blink",
		interface: "HTMLUnknownElement",
		conformance: "non-conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	blockquote: {
		tag: "blockquote",
		interface: "HTMLQuoteElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"palpable",
		],
	},
	body: {
		tag: "body",
		interface: "HTMLBodyElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	br: {
		tag: "br",
		interface: "HTMLBRElement",
		conformance: "conforming",
		void: true,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
		],
	},
	button: {
		tag: "button",
		interface: "HTMLButtonElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"interactive",
			"listed",
			"labelable",
			"submittable",
			"form-associated",
			"palpable",
		],
	},
	canvas: {
		tag: "canvas",
		interface: "HTMLCanvasElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"embedded",
			"palpable",
		],
	},
	caption: {
		tag: "caption",
		interface: "HTMLTableCaptionElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	center: {
		tag: "center",
		interface: "HTMLElement",
		conformance: "non-conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	cite: {
		tag: "cite",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	code: {
		tag: "code",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	col: {
		tag: "col",
		interface: "HTMLTableColElement",
		conformance: "conforming",
		void: true,
		rawText: false,
		categories: [],
	},
	colgroup: {
		tag: "colgroup",
		interface: "HTMLTableColElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	data: {
		tag: "data",
		interface: "HTMLDataElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	datalist: {
		tag: "datalist",
		interface: "HTMLDataListElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
		],
	},
	dd: {
		tag: "dd",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	del: {
		tag: "del",
		interface: "HTMLModElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	details: {
		tag: "details",
		interface: "HTMLDetailsElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"interactive",
			"palpable",
		],
	},
	dfn: {
		tag: "dfn",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	dialog: {
		tag: "dialog",
		interface: "HTMLDialogElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: ["flow"],
	},
	dir: {
		tag: "dir",
		interface: "HTMLDirectoryElement",
		conformance: "non-conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	div: {
		tag: "div",
		interface: "HTMLDivElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"palpable",
		],
	},
	dl: {
		tag: "dl",
		interface: "HTMLDListElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"palpable",
		],
	},
	dt: {
		tag: "dt",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	em: {
		tag: "em",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	embed: {
		tag: "embed",
		interface: "HTMLEmbedElement",
		conformance: "conforming",
		void: true,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"embedded",
			"interactive",
			"palpable",
		],
	},
	fieldset: {
		tag: "fieldset",
		interface: "HTMLFieldSetElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"listed",
			"form-associated",
			"palpable",
		],
	},
	figcaption: {
		tag: "figcaption",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	figure: {
		tag: "figure",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"palpable",
		],
	},
	font: {
		tag: "font",
		interface: "HTMLFontElement",
		conformance: "non-conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	footer: {
		tag: "footer",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"palpable",
		],
	},
	form: {
		tag: "form",
		interface: "HTMLFormElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"palpable",
		],
	},
	frame: {
		tag: "frame",
		interface: "HTMLFrameElement",
		conformance: "non-conforming",
		void: true,
		rawText: false,
		categories: [],
	},
	frameset: {
		tag: "frameset",
		interface: "HTMLFrameSetElement",
		conformance: "non-conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	h1: {
		tag: "h1",
		interface: "HTMLHeadingElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"heading",
			"palpable",
		],
	},
	h2: {
		tag: "h2",
		interface: "HTMLHeadingElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"heading",
			"palpable",
		],
	},
	h3: {
		tag: "h3",
		interface: "HTMLHeadingElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"heading",
			"palpable",
		],
	},
	h4: {
		tag: "h4",
		interface: "HTMLHeadingElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"heading",
			"palpable",
		],
	},
	h5: {
		tag: "h5",
		interface: "HTMLHeadingElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"heading",
			"palpable",
		],
	},
	h6: {
		tag: "h6",
		interface: "HTMLHeadingElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"heading",
			"palpable",
		],
	},
	head: {
		tag: "head",
		interface: "HTMLHeadElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	header: {
		tag: "header",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"palpable",
		],
	},
	hgroup: {
		tag: "hgroup",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"palpable",
		],
	},
	hr: {
		tag: "hr",
		interface: "HTMLHRElement",
		conformance: "conforming",
		void: true,
		rawText: false,
		categories: ["flow"],
	},
	html: {
		tag: "html",
		interface: "HTMLHtmlElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	i: {
		tag: "i",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	iframe: {
		tag: "iframe",
		interface: "HTMLIFrameElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"embedded",
			"interactive",
			"palpable",
		],
	},
	img: {
		tag: "img",
		interface: "HTMLImageElement",
		conformance: "conforming",
		void: true,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"embedded",
			"interactive",
			"form-associated",
			"palpable",
		],
	},
	input: {
		tag: "input",
		interface: "HTMLInputElement",
		conformance: "conforming",
		void: true,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"interactive",
			"listed",
			"labelable",
			"submittable",
			"resettable",
			"form-associated",
			"palpable",
		],
	},
	ins: {
		tag: "ins",
		interface: "HTMLModElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	isindex: {
		tag: "isindex",
		interface: "HTMLUnknownElement",
		conformance: "non-conforming",
		void: true,
		rawText: false,
		categories: [],
	},
	kbd: {
		tag: "kbd",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	keygen: {
		tag: "keygen",
		interface: "HTMLUnknownElement",
		conformance: "non-conforming",
		void: true,
		rawText: false,
		categories: [],
	},
	label: {
		tag: "label",
		interface: "HTMLLabelElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"interactive",
			"palpable",
		],
	},
	legend: {
		tag: "legend",
		interface: "HTMLLegendElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	li: {
		tag: "li",
		interface: "HTMLLIElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	link: {
		tag: "link",
		interface: "HTMLLinkElement",
		conformance: "conforming",
		void: true,
		rawText: false,
		categories: [
			"metadata",
			"flow",
			"phrasing",
		],
	},
	listing: {
		tag: "listing",
		interface: "HTMLPreElement",
		conformance: "non-conforming",
		void: false,
		rawText: true,
		categories: [],
	},
	main: {
		tag: "main",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"palpable",
		],
	},
	map: {
		tag: "map",
		interface: "HTMLMapElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	mark: {
		tag: "mark",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	marquee: {
		tag: "marquee",
		interface: "HTMLMarqueeElement",
		conformance: "non-conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	menu: {
		tag: "menu",
		interface: "HTMLMenuElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"palpable",
		],
	},
	menuitem: {
		tag: "menuitem",
		interface: "HTMLUnknownElement",
		conformance: "non-conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	meta: {
		tag: "meta",
		interface: "HTMLMetaElement",
		conformance: "conforming",
		void: true,
		rawText: false,
		categories: [
			"metadata",
			"flow",
			"phrasing",
		],
	},
	meter: {
		tag: "meter",
		interface: "HTMLMeterElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"labelable",
			"palpable",
		],
	},
	multicol: {
		tag: "multicol",
		interface: "HTMLUnknownElement",
		conformance: "non-conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	nav: {
		tag: "nav",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"sectioning",
			"palpable",
		],
	},
	nextid: {
		tag: "nextid",
		interface: "HTMLUnknownElement",
		conformance: "non-conforming",
		void: true,
		rawText: false,
		categories: [],
	},
	nobr: {
		tag: "nobr",
		interface: "HTMLElement",
		conformance: "non-conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	noembed: {
		tag: "noembed",
		interface: "HTMLElement",
		conformance: "non-conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	noframes: {
		tag: "noframes",
		interface: "HTMLElement",
		conformance: "non-conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	noscript: {
		tag: "noscript",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"metadata",
			"flow",
			"phrasing",
		],
	},
	object: {
		tag: "object",
		interface: "HTMLObjectElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"embedded",
			"interactive",
			"listed",
			"form-associated",
			"palpable",
		],
	},
	ol: {
		tag: "ol",
		interface: "HTMLOListElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"palpable",
		],
	},
	optgroup: {
		tag: "optgroup",
		interface: "HTMLOptGroupElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	option: {
		tag: "option",
		interface: "HTMLOptionElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	output: {
		tag: "output",
		interface: "HTMLOutputElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"listed",
			"labelable",
			"resettable",
			"form-associated",
			"palpable",
		],
	},
	p: {
		tag: "p",
		interface: "HTMLParagraphElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"palpable",
		],
	},
	param: {
		tag: "param",
		interface: "HTMLParamElement",
		conformance: "non-conforming",
		void: true,
		rawText: false,
		categories: [],
	},
	picture: {
		tag: "picture",
		interface: "HTMLPictureElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"embedded",
			"palpable",
		],
	},
	plaintext: {
		tag: "plaintext",
		interface: "HTMLElement",
		conformance: "non-conforming",
		void: false,
		rawText: true,
		categories: [],
	},
	pre: {
		tag: "pre",
		interface: "HTMLPreElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"palpable",
		],
	},
	progress: {
		tag: "progress",
		interface: "HTMLProgressElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"labelable",
			"palpable",
		],
	},
	q: {
		tag: "q",
		interface: "HTMLQuoteElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	rb: {
		tag: "rb",
		interface: "HTMLElement",
		conformance: "non-conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	rp: {
		tag: "rp",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	rt: {
		tag: "rt",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	rtc: {
		tag: "rtc",
		interface: "HTMLElement",
		conformance: "non-conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	ruby: {
		tag: "ruby",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	s: {
		tag: "s",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	samp: {
		tag: "samp",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	script: {
		tag: "script",
		interface: "HTMLScriptElement",
		conformance: "conforming",
		void: false,
		rawText: true,
		categories: [
			"metadata",
			"flow",
			"phrasing",
			"script-supporting",
		],
	},
	search: {
		tag: "search",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"palpable",
		],
	},
	section: {
		tag: "section",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"sectioning",
			"palpable",
		],
	},
	select: {
		tag: "select",
		interface: "HTMLSelectElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"interactive",
			"listed",
			"labelable",
			"submittable",
			"resettable",
			"form-associated",
			"palpable",
		],
	},
	selectedcontent: {
		tag: "selectedcontent",
		interface: "HTMLSelectedContentElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	slot: {
		tag: "slot",
		interface: "HTMLSlotElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
		],
	},
	small: {
		tag: "small",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	source: {
		tag: "source",
		interface: "HTMLSourceElement",
		conformance: "conforming",
		void: true,
		rawText: false,
		categories: [],
	},
	spacer: {
		tag: "spacer",
		interface: "HTMLUnknownElement",
		conformance: "non-conforming",
		void: true,
		rawText: false,
		categories: [],
	},
	span: {
		tag: "span",
		interface: "HTMLSpanElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	strike: {
		tag: "strike",
		interface: "HTMLElement",
		conformance: "non-conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	strong: {
		tag: "strong",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	style: {
		tag: "style",
		interface: "HTMLStyleElement",
		conformance: "conforming",
		void: false,
		rawText: true,
		categories: ["metadata"],
	},
	sub: {
		tag: "sub",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	summary: {
		tag: "summary",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	sup: {
		tag: "sup",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	table: {
		tag: "table",
		interface: "HTMLTableElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"palpable",
		],
	},
	tbody: {
		tag: "tbody",
		interface: "HTMLTableSectionElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	td: {
		tag: "td",
		interface: "HTMLTableCellElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	template: {
		tag: "template",
		interface: "HTMLTemplateElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"metadata",
			"flow",
			"phrasing",
			"script-supporting",
		],
	},
	textarea: {
		tag: "textarea",
		interface: "HTMLTextAreaElement",
		conformance: "conforming",
		void: false,
		rawText: true,
		categories: [
			"flow",
			"phrasing",
			"interactive",
			"listed",
			"labelable",
			"submittable",
			"resettable",
			"form-associated",
			"palpable",
		],
	},
	tfoot: {
		tag: "tfoot",
		interface: "HTMLTableSectionElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	th: {
		tag: "th",
		interface: "HTMLTableCellElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: ["interactive"],
	},
	thead: {
		tag: "thead",
		interface: "HTMLTableSectionElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	time: {
		tag: "time",
		interface: "HTMLTimeElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	title: {
		tag: "title",
		interface: "HTMLTitleElement",
		conformance: "conforming",
		void: false,
		rawText: true,
		categories: ["metadata"],
	},
	tr: {
		tag: "tr",
		interface: "HTMLTableRowElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	track: {
		tag: "track",
		interface: "HTMLTrackElement",
		conformance: "conforming",
		void: true,
		rawText: false,
		categories: [],
	},
	tt: {
		tag: "tt",
		interface: "HTMLElement",
		conformance: "non-conforming",
		void: false,
		rawText: false,
		categories: [],
	},
	u: {
		tag: "u",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	ul: {
		tag: "ul",
		interface: "HTMLUListElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"palpable",
		],
	},
	var: {
		tag: "var",
		interface: "HTMLElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"palpable",
		],
	},
	video: {
		tag: "video",
		interface: "HTMLVideoElement",
		conformance: "conforming",
		void: false,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
			"embedded",
			"interactive",
			"palpable",
		],
	},
	wbr: {
		tag: "wbr",
		interface: "HTMLElement",
		conformance: "conforming",
		void: true,
		rawText: false,
		categories: [
			"flow",
			"phrasing",
		],
	},
	xmp: {
		tag: "xmp",
		interface: "HTMLPreElement",
		conformance: "non-conforming",
		void: false,
		rawText: true,
		categories: [],
	},
} as const);
