/**
 * Shared emoji data and shortcode lookup.
 * Source of truth for emoji ↔ shortcode mappings used by
 * the autocomplete trigger, decorator, and tooltip system.
 *
 * Format: [emoji, name, ...keywords]
 */
export const EMOJI_DATA: Array<[string, string, ...string[]]> = [
	// Smileys & Emotion
	["😀", "grinning", "smile", "happy"],
	["😃", "smiley", "smile", "happy"],
	["😄", "smile", "happy", "joy"],
	["😁", "grin", "happy"],
	["😅", "sweat_smile", "hot"],
	["😂", "joy", "laugh", "lol"],
	["🤣", "rofl", "laugh", "lol"],
	["😊", "blush", "smile"],
	["😇", "innocent", "angel"],
	["🙂", "slightly_smiling_face", "smile"],
	["🙃", "upside_down_face"],
	["😉", "wink"],
	["😌", "relieved"],
	["😍", "heart_eyes", "love"],
	["🥰", "smiling_face_with_hearts", "love"],
	["😘", "kissing_heart", "love"],
	["😗", "kissing"],
	["😙", "kissing_smiling_eyes"],
	["😚", "kissing_closed_eyes"],
	["😋", "yum", "delicious"],
	["😛", "stuck_out_tongue"],
	["😜", "stuck_out_tongue_winking_eye"],
	["🤪", "zany_face", "crazy"],
	["😝", "stuck_out_tongue_closed_eyes"],
	["🤑", "money_mouth_face", "rich"],
	["🤗", "hugs", "hug"],
	["🤭", "hand_over_mouth"],
	["🤫", "shushing_face", "quiet"],
	["🤔", "thinking", "hmm"],
	["🤐", "zipper_mouth_face"],
	["🤨", "raised_eyebrow"],
	["😐", "neutral_face"],
	["😑", "expressionless"],
	["😶", "no_mouth"],
	["😏", "smirk"],
	["😒", "unamused"],
	["🙄", "roll_eyes", "whatever"],
	["😬", "grimacing"],
	["🤥", "lying_face"],
	["😌", "relieved"],
	["😔", "pensive", "sad"],
	["😪", "sleepy"],
	["🤤", "drooling_face"],
	["😴", "sleeping", "zzz"],
	["😷", "mask", "sick"],
	["🤒", "face_with_thermometer", "sick"],
	["🤕", "face_with_head_bandage", "hurt"],
	["🤢", "nauseated_face", "sick"],
	["🤮", "vomiting_face"],
	["🤧", "sneezing_face"],
	["🥵", "hot_face", "hot"],
	["🥶", "cold_face", "cold"],
	["🥴", "woozy_face", "drunk"],
	["😵", "dizzy_face"],
	["🤯", "exploding_head", "mind_blown"],
	["🤠", "cowboy_hat_face"],
	["🥳", "partying_face", "party"],
	["🥸", "disguised_face"],
	["😎", "sunglasses", "cool"],
	["🤓", "nerd_face", "nerd"],
	["🧐", "monocle_face"],
	["😕", "confused"],
	["😟", "worried"],
	["🙁", "slightly_frowning_face"],
	["☹️", "frowning_face"],
	["😮", "open_mouth", "surprised"],
	["😯", "hushed"],
	["😲", "astonished"],
	["😳", "flushed"],
	["🥺", "pleading_face", "puppy"],
	["😦", "frowning"],
	["😧", "anguished"],
	["😨", "fearful", "scared"],
	["😰", "cold_sweat"],
	["😥", "disappointed_relieved"],
	["😢", "cry", "sad"],
	["😭", "sob", "crying"],
	["😱", "scream", "scared"],
	["😖", "confounded"],
	["😣", "persevere"],
	["😞", "disappointed", "sad"],
	["😓", "sweat"],
	["😩", "weary"],
	["😫", "tired_face"],
	["🥱", "yawning_face"],
	["😤", "triumph", "angry"],
	["😡", "rage", "angry"],
	["😠", "angry"],
	["🤬", "cursing_face", "angry"],
	["😈", "smiling_imp", "devil"],
	["👿", "imp", "devil"],
	["💀", "skull", "dead"],
	["☠️", "skull_and_crossbones"],
	["💩", "poop", "shit"],
	["🤡", "clown_face"],
	["👹", "japanese_ogre"],
	["👺", "japanese_goblin"],
	["👻", "ghost"],
	["👽", "alien"],
	["👾", "space_invader"],
	["🤖", "robot"],

	// Gestures
	["👍", "thumbsup", "ok", "yes", "+1"],
	["👎", "thumbsdown", "no", "-1"],
	["👌", "ok_hand", "perfect"],
	["🤌", "pinched_fingers"],
	["✌️", "v", "peace"],
	["🤞", "crossed_fingers", "luck"],
	["🤟", "love_you_gesture"],
	["🤘", "metal", "rock"],
	["🤙", "call_me_hand"],
	["👈", "point_left"],
	["👉", "point_right"],
	["👆", "point_up"],
	["👇", "point_down"],
	["☝️", "point_up_2"],
	["👋", "wave", "hi", "hello"],
	["🤚", "raised_back_of_hand"],
	["🖐️", "raised_hand_with_fingers_splayed"],
	["✋", "hand", "stop", "high_five"],
	["🖖", "vulcan_salute", "spock"],
	["👏", "clap", "applause"],
	["🙌", "raised_hands", "hooray"],
	["👐", "open_hands"],
	["🤲", "palms_up_together"],
	["🤝", "handshake", "deal"],
	["🙏", "pray", "please", "thanks"],
	["✍️", "writing_hand"],
	["💪", "muscle", "flex", "strong"],

	// Hearts & Love
	["❤️", "heart", "love"],
	["🧡", "orange_heart"],
	["💛", "yellow_heart"],
	["💚", "green_heart"],
	["💙", "blue_heart"],
	["💜", "purple_heart"],
	["🖤", "black_heart"],
	["🤍", "white_heart"],
	["🤎", "brown_heart"],
	["💔", "broken_heart"],
	["❤️‍🔥", "heart_on_fire"],
	["💕", "two_hearts"],
	["💞", "revolving_hearts"],
	["💓", "heartbeat"],
	["💗", "heartpulse"],
	["💖", "sparkling_heart"],
	["💘", "cupid"],
	["💝", "gift_heart"],

	// Celebration
	["🎉", "tada", "party", "celebration"],
	["🎊", "confetti_ball"],
	["🎁", "gift", "present"],
	["🎈", "balloon"],
	["🎂", "birthday", "cake"],
	["🍰", "cake"],
	["🎄", "christmas_tree"],
	["🎃", "jack_o_lantern", "halloween"],
	["🎆", "fireworks"],
	["🎇", "sparkler"],
	["✨", "sparkles", "magic"],
	["⭐", "star"],
	["🌟", "star2", "glowing_star"],
	["💫", "dizzy", "star"],

	// Objects & Symbols
	["🔥", "fire", "hot", "lit"],
	["💯", "100", "perfect"],
	["💢", "anger"],
	["💥", "boom", "explosion"],
	["💫", "dizzy"],
	["💦", "sweat_drops"],
	["💨", "dash", "wind"],
	["🕳️", "hole"],
	["💣", "bomb"],
	["💬", "speech_balloon", "comment"],
	["👁️‍🗨️", "eye_speech_bubble"],
	["🗨️", "left_speech_bubble"],
	["🗯️", "right_anger_bubble"],
	["💭", "thought_balloon"],
	["💤", "zzz", "sleep"],
	["🔔", "bell", "notification"],
	["🔕", "no_bell", "mute"],
	["📢", "loudspeaker"],
	["📣", "mega"],
	["📝", "memo", "note"],
	["✏️", "pencil2"],
	["✒️", "black_nib"],
	["📌", "pushpin", "pin"],
	["📍", "round_pushpin"],
	["📎", "paperclip"],
	["🔗", "link"],
	["📧", "email", "mail"],
	["💻", "computer", "laptop"],
	["🖥️", "desktop_computer"],
	["⌨️", "keyboard"],
	["🖱️", "computer_mouse"],
	["📱", "iphone", "phone"],
	["☎️", "phone", "telephone"],
	["📞", "telephone_receiver"],
	["⏰", "alarm_clock"],
	["⏳", "hourglass_flowing_sand"],
	["⌛", "hourglass"],
	["📅", "date", "calendar"],
	["📆", "calendar"],
	["🔒", "lock", "secure"],
	["🔓", "unlock"],
	["🔑", "key"],
	["🔨", "hammer"],
	["🔧", "wrench", "tool"],
	["🔩", "nut_and_bolt"],
	["⚙️", "gear", "settings"],
	["🧲", "magnet"],
	["💡", "bulb", "idea"],
	["🔦", "flashlight"],
	["🕯️", "candle"],
	["📦", "package", "box"],
	["🗑️", "wastebasket", "trash"],

	// Weather & Nature
	["☀️", "sunny", "sun"],
	["🌤️", "sun_behind_small_cloud"],
	["⛅", "partly_sunny"],
	["🌥️", "sun_behind_large_cloud"],
	["☁️", "cloud"],
	["🌦️", "sun_behind_rain_cloud"],
	["🌧️", "cloud_with_rain", "rain"],
	["⛈️", "cloud_with_lightning_and_rain"],
	["🌩️", "cloud_with_lightning"],
	["🌨️", "cloud_with_snow"],
	["❄️", "snowflake", "snow"],
	["☃️", "snowman"],
	["⛄", "snowman_without_snow"],
	["🌬️", "wind_face"],
	["💨", "dash", "wind"],
	["🌪️", "tornado"],
	["🌈", "rainbow"],

	// Food & Drink
	["☕", "coffee"],
	["🍵", "tea"],
	["🍺", "beer"],
	["🍻", "beers", "cheers"],
	["🥂", "champagne", "cheers"],
	["🍷", "wine_glass"],
	["🍸", "cocktail"],
	["🍹", "tropical_drink"],
	["🍾", "champagne_bottle"],
	["🍕", "pizza"],
	["🍔", "hamburger", "burger"],
	["🍟", "fries"],
	["🌭", "hotdog"],
	["🍿", "popcorn"],
	["🍩", "doughnut", "donut"],
	["🍪", "cookie"],
	["🍫", "chocolate_bar"],
	["🍬", "candy"],
	["🍭", "lollipop"],
	["🍦", "icecream"],
	["🍨", "ice_cream"],
	["🎂", "birthday", "cake"],
	["🍰", "cake"],

	// Animals
	["🐶", "dog"],
	["🐱", "cat"],
	["🐭", "mouse"],
	["🐹", "hamster"],
	["🐰", "rabbit"],
	["🦊", "fox_face", "fox"],
	["🐻", "bear"],
	["🐼", "panda_face", "panda"],
	["🐨", "koala"],
	["🐯", "tiger"],
	["🦁", "lion"],
	["🐮", "cow"],
	["🐷", "pig"],
	["🐸", "frog"],
	["🐵", "monkey_face", "monkey"],
	["🙈", "see_no_evil"],
	["🙉", "hear_no_evil"],
	["🙊", "speak_no_evil"],
	["🐔", "chicken"],
	["🐧", "penguin"],
	["🐦", "bird"],
	["🐤", "baby_chick"],
	["🦆", "duck"],
	["🦅", "eagle"],
	["🦉", "owl"],
	["🦇", "bat"],
	["🐺", "wolf"],
	["🐗", "boar"],
	["🐴", "horse"],
	["🦄", "unicorn"],
	["🐝", "bee", "honeybee"],
	["🐛", "bug"],
	["🦋", "butterfly"],
	["🐌", "snail"],
	["🐞", "beetle", "ladybug"],
	["🐜", "ant"],
	["🦟", "mosquito"],
	["🦗", "cricket"],
	["🕷️", "spider"],
	["🕸️", "spider_web"],
	["🦂", "scorpion"],
	["🐢", "turtle"],
	["🐍", "snake"],
	["🦎", "lizard"],
	["🐙", "octopus"],
	["🦑", "squid"],
	["🦐", "shrimp"],
	["🦞", "lobster"],
	["🦀", "crab"],
	["🐡", "blowfish"],
	["🐠", "tropical_fish"],
	["🐟", "fish"],
	["🐬", "dolphin"],
	["🐳", "whale"],
	["🐋", "whale2"],
	["🦈", "shark"],
	["🐊", "crocodile"],
	["🐅", "tiger2"],
	["🐆", "leopard"],
	["🦓", "zebra"],
	["🦍", "gorilla"],
	["🦧", "orangutan"],
	["🐘", "elephant"],
	["🦛", "hippopotamus", "hippo"],
	["🦏", "rhinoceros", "rhino"],
	["🐪", "camel"],
	["🐫", "two_hump_camel"],
	["🦒", "giraffe"],
	["🦘", "kangaroo"],
	["🦬", "bison"],
	["🐃", "water_buffalo"],
	["🐂", "ox"],
	["🐄", "cow2"],
	["🐎", "racehorse"],
	["🐖", "pig2"],
	["🐏", "ram"],
	["🐑", "sheep"],
	["🦙", "llama"],
	["🐐", "goat"],
	["🦌", "deer"],
	["🐕", "dog2"],
	["🐩", "poodle"],
	["🦮", "guide_dog"],
	["🐕‍🦺", "service_dog"],
	["🐈", "cat2"],
	["🐈‍⬛", "black_cat"],
	["🐓", "rooster"],
	["🦃", "turkey"],
	["🦤", "dodo"],
	["🦚", "peacock"],
	["🦜", "parrot"],
	["🦢", "swan"],
	["🦩", "flamingo"],
	["🕊️", "dove"],
	["🐇", "rabbit2"],
	["🦝", "raccoon"],
	["🦨", "skunk"],
	["🦡", "badger"],
	["🦫", "beaver"],
	["🦦", "otter"],
	["🦥", "sloth"],
	["🐁", "mouse2"],
	["🐀", "rat"],
	["🐿️", "chipmunk"],
	["🦔", "hedgehog"],

	// Work & Office
	["✅", "white_check_mark", "check", "done"],
	["❌", "x", "no", "cross"],
	["❓", "question"],
	["❗", "exclamation", "bang"],
	["⚠️", "warning"],
	["🚫", "no_entry_sign", "forbidden"],
	["⛔", "no_entry"],
	["🔴", "red_circle"],
	["🟠", "orange_circle"],
	["🟡", "yellow_circle"],
	["🟢", "green_circle"],
	["🔵", "blue_circle"],
	["🟣", "purple_circle"],
	["⚫", "black_circle"],
	["⚪", "white_circle"],
	["🟤", "brown_circle"],
	["🔺", "small_red_triangle"],
	["🔻", "small_red_triangle_down"],
	["🔶", "large_orange_diamond"],
	["🔷", "large_blue_diamond"],
	["🔸", "small_orange_diamond"],
	["🔹", "small_blue_diamond"],
	["▪️", "black_small_square"],
	["▫️", "white_small_square"],
	["◾", "black_medium_small_square"],
	["◽", "white_medium_small_square"],
	["◼️", "black_medium_square"],
	["◻️", "white_medium_square"],
	["⬛", "black_large_square"],
	["⬜", "white_large_square"],
]

/**
 * Reverse lookup map: emoji char → shortcode name.
 * Stores both with and without variation selector \uFE0F for reliable matching.
 */
const emojiToShortcode = new Map<string, string>()
for (const [emoji, name] of EMOJI_DATA) {
	emojiToShortcode.set(emoji, name)
	// Also store without variation selector for matching
	const withoutVS = emoji.replace(/\uFE0F/g, "")
	if (withoutVS !== emoji) {
		emojiToShortcode.set(withoutVS, name)
	}
}

/**
 * Look up the shortcode for a Unicode emoji character.
 * Handles variation selectors transparently.
 */
export function getEmojiShortcode(emoji: string): string | undefined {
	return emojiToShortcode.get(emoji) ?? emojiToShortcode.get(emoji.replace(/\uFE0F/g, ""))
}
