/**
 * Official IANA media type registry target definition.
 *
 * @packageDocumentation
 * @since 0.0.0
 */

import { $RepoCliId } from "@beep/identity/packages";
import { A, Str } from "@beep/utils";
import { Effect, Order, pipe } from "effect";
import * as P from "effect/Predicate";
import * as R from "effect/Record";
import * as S from "effect/Schema";
import {
  fetchSource,
  formatJson,
  formatTsLiteral,
  outputFile,
  parseXmlSource,
  sourceMetadata,
} from "../internal/Source.js";
import { SyncDataTargetProjection, SyncDataToTsError } from "../internal/Models.js";
import type { SyncDataTarget } from "../internal/Models.js";

const $I = $RepoCliId.create("commands/SyncDataToTs/targets/IanaMediaTypes");
const targetId = "iana-media-types" as const;
const outputPath = "packages/foundation/primitive/data/src/generated/iana-media-types.ts" as const;
const canonicalPath = "packages/foundation/primitive/data/src/generated/iana-media-types.data.json" as const;

/**
 * Official IANA media type registry XML source.
 *
 * @category configuration
 * @since 0.0.0
 */
export const IANA_MEDIA_TYPES_SOURCE_URL = "https://www.iana.org/assignments/media-types/media-types.xml" as const;

class IanaMediaTypeTextNode extends S.Class<IanaMediaTypeTextNode>($I`IanaMediaTypeTextNode`)(
  {
    text: S.String,
  },
  $I.annote("IanaMediaTypeTextNode", {
    description: "XML text node emitted by the registry parser for selected fields.",
  })
) {}

const IanaMediaTypeName = S.Union([S.String, IanaMediaTypeTextNode]);

class IanaMediaTypeRecord extends S.Class<IanaMediaTypeRecord>($I`IanaMediaTypeRecord`)(
  {
    name: IanaMediaTypeName,
    date: S.optionalKey(S.String),
  },
  $I.annote("IanaMediaTypeRecord", {
    description: "Single IANA media type registry record.",
  })
) {}

class IanaMediaTypeRegistry extends S.Class<IanaMediaTypeRegistry>($I`IanaMediaTypeRegistry`)(
  {
    title: S.String,
    record: S.optionalKey(S.Union([IanaMediaTypeRecord, S.Array(IanaMediaTypeRecord)])),
  },
  $I.annote("IanaMediaTypeRegistry", {
    description: "Nested top-level IANA media type registry.",
  })
) {}

class IanaMediaTypesRoot extends S.Class<IanaMediaTypesRoot>($I`IanaMediaTypesRoot`)(
  {
    updated: S.String,
    registry: S.Array(IanaMediaTypeRegistry),
  },
  $I.annote("IanaMediaTypesRoot", {
    description: "Top-level IANA media type registry XML payload.",
  })
) {}

class IanaMediaTypesDocument extends S.Class<IanaMediaTypesDocument>($I`IanaMediaTypesDocument`)(
  {
    registry: IanaMediaTypesRoot,
  },
  $I.annote("IanaMediaTypesDocument", {
    description: "Decoded XML document for the official IANA media type registry.",
  })
) {}

class IanaMediaTypeEntry extends S.Class<IanaMediaTypeEntry>($I`IanaMediaTypeEntry`)(
  {
    type: S.String,
    topLevel: S.String,
    name: S.String,
    registryName: S.String,
    date: S.optionalKey(S.String),
  },
  $I.annote("IanaMediaTypeEntry", {
    description: "Normalized IANA media type entry rendered into @beep/data.",
  })
) {}

type IanaMediaTypeEntryType = IanaMediaTypeEntry;
const isTextNode = S.is(IanaMediaTypeTextNode);
const primaryTopLevels = new Set(["application", "audio", "image", "text", "video"]);

const extractName = (name: string | IanaMediaTypeTextNode): string => (isTextNode(name) ? name.text : name);

const recordsArray = (
  record: IanaMediaTypeRegistry["record"]
): ReadonlyArray<IanaMediaTypeRecord> => {
  if (record === undefined) {
    return [];
  }
  return Array.isArray(record) ? (record as ReadonlyArray<IanaMediaTypeRecord>) : [record as IanaMediaTypeRecord];
};

const byType = (values: ReadonlyArray<IanaMediaTypeEntryType>) =>
  pipe(
    values,
    A.map((entry) => [entry.type, entry] as const),
    R.fromEntries
  );

const byTopLevel = (values: ReadonlyArray<IanaMediaTypeEntryType>) => {
  const grouped: Record<string, Record<string, IanaMediaTypeEntryType>> = {
    application: {},
    audio: {},
    image: {},
    misc: {},
    text: {},
    video: {},
  };

  for (const entry of values) {
    const bucket = primaryTopLevels.has(entry.topLevel) ? entry.topLevel : "misc";
    grouped[bucket] = {
      ...grouped[bucket],
      [entry.type]: entry,
    };
  }

  return grouped;
};

const renderIanaMediaTypesModule = (
  updated: string,
  sha256: string,
  values: ReadonlyArray<IanaMediaTypeEntryType>
): string => `/**
 * Generated IANA media type registry data.
 *
 * Generated by \`bun run beep sync-data-to-ts --target iana-media-types\`.
 * Source: ${IANA_MEDIA_TYPES_SOURCE_URL}
 * Updated: ${updated}
 *
 * @packageDocumentation
 * @since 0.0.0
 */

/**
 * Stable source metadata for the official IANA media type registry.
 *
 * @since 0.0.0
 */
export const OfficialMimeTypeDataMetadata = ${formatTsLiteral({
  sourceUrl: IANA_MEDIA_TYPES_SOURCE_URL,
  updated,
  sha256,
})} as const;

/**
 * Last updated date reported by the official IANA media type registry.
 *
 * @since 0.0.0
 */
export const OfficialMimeTypeDataUpdated = ${formatTsLiteral(updated)} as const;

/**
 * Official IANA media type registry source URL.
 *
 * @since 0.0.0
 */
export const OfficialMimeTypeDataSourceUrl = ${formatTsLiteral(IANA_MEDIA_TYPES_SOURCE_URL)} as const;

/**
 * SHA-256 digest of the official source payload used for this generated module.
 *
 * @since 0.0.0
 */
export const OfficialMimeTypeDataSourceSha256 = ${formatTsLiteral(sha256)} as const;

/**
 * Normalized IANA media type entries.
 *
 * @since 0.0.0
 */
export const OfficialMimeTypeDataValues = ${formatTsLiteral(values)} as const;

/**
 * Normalized IANA media type entries keyed by full media type.
 *
 * @since 0.0.0
 */
export const OfficialMimeTypeDataByType = ${formatTsLiteral(byType(values))} as const;

/**
 * IANA media type literal values.
 *
 * @since 0.0.0
 */
export const OfficialMimeTypeDataTypeValues = ${formatTsLiteral(A.map(values, (entry) => entry.type))} as const;

/**
 * IANA media type entries grouped for schema category helpers.
 *
 * @since 0.0.0
 */
export const OfficialMimeTypeDataByTopLevel = ${formatTsLiteral(byTopLevel(values))} as const;
`;

const normalizeIanaMediaTypes = Effect.fn("SyncDataToTs.IanaMediaTypes.normalize")(function* (document: unknown) {
  const decoded = yield* S.decodeUnknownEffect(IanaMediaTypesDocument)(document).pipe(
    SyncDataToTsError.mapError("Failed to decode the official IANA media types XML payload", targetId)
  );

  const updated = decoded.registry.updated;
  const values = pipe(
    decoded.registry.registry,
    A.flatMap((registry) => {
      const topLevel = Str.toLowerCase(registry.title);
      return pipe(
        recordsArray(registry.record),
        A.map((record) => {
          const registryName = extractName(record.name);
          const normalizedName = Str.toLowerCase(registryName);
          return IanaMediaTypeEntry.make({
            type: `${topLevel}/${normalizedName}`,
            topLevel,
            name: normalizedName,
            registryName,
            ...(P.isString(record.date) ? { date: record.date } : {}),
          });
        })
      );
    }),
    A.sort(Order.mapInput(Order.String, ({ type }: IanaMediaTypeEntryType) => type))
  );

  return { updated, values } as const;
});

const acquireIanaMediaTypesProjection = Effect.fn("SyncDataToTs.IanaMediaTypes.acquire")(function* () {
  const source = yield* fetchSource(targetId, "iana-media-types-xml", IANA_MEDIA_TYPES_SOURCE_URL);
  const document = yield* parseXmlSource(targetId, source);
  const { updated, values } = yield* normalizeIanaMediaTypes(document);
  const metadata = sourceMetadata(source, { published: updated });
  const canonical = {
    schemaVersion: "beep-data/iana-media-types/v1",
    metadata,
    mediaTypesByType: byType(values),
  } as const;

  return SyncDataTargetProjection.make({
    files: [
      outputFile(outputPath, renderIanaMediaTypesModule(updated, source.sha256, values)),
      outputFile(canonicalPath, formatJson(canonical)),
    ],
    canonicalPath,
    canonical,
    recordCount: A.length(values),
    summary: `${A.length(values)} media type entries updated ${updated}`,
    sources: [metadata],
  });
});

/**
 * Checked-in sync target for the official IANA media type registry.
 *
 * @category configuration
 * @since 0.0.0
 */
export const ianaMediaTypesTarget: SyncDataTarget = {
  id: targetId,
  description: "Sync official MIME/media type literals from the IANA registry XML.",
  sourceUrls: [IANA_MEDIA_TYPES_SOURCE_URL],
  acquire: acquireIanaMediaTypesProjection(),
};
