import type { LiteralString } from "../../internal";

type ScalarTheme =
  | "alternate"
  | "default"
  | "moon"
  | "purple"
  | "solarized"
  | "bluePlanet"
  | "saturn"
  | "kepler"
  | "mars"
  | "deepSpace"
  | "laserwave"
  | "none";

export interface OpenAPIOptions {
  /**
   * The path to the OpenAPI reference page
   *
   * keep in mind that this path will be appended to the base URL `/api/auth` path
   * by default, so if you set this to `/reference`, the full path will be `/api/auth/reference`
   *
   * @default "/reference"
   */
  path?: LiteralString;
  /**
   * Disable the default reference page that is generated by Scalar
   *
   * @default false
   */
  disableDefaultReference?: boolean;
  /**
   * Theme of the OpenAPI reference page.
   *
   * @default "default"
   */
  theme?: ScalarTheme;
}
