name: beep-ai-metrics-local
services:
  ai-metrics-phoenix:
    container_name: beep-ai-metrics-phoenix
    environment:
      PHOENIX_WORKING_DIR: /data
    image: arizephoenix/phoenix:latest
    ports:
      - 6006:6006
    restart: unless-stopped
    volumes:
      - phoenix_data:/data
volumes:
  phoenix_data: {}
