import { Effect, pipe, SchemaGetter, type SchemaIssue } from "effect";
import * as O from "effect/Option";
import { normalizePath } from "../../eslint/Shared.ts";
import {
  ALLOWLIST_PATH,
  decodeAllowlistDocumentFromJsoncText,
  EffectLawsAllowlistSnapshot,
  encodeAllowlistSnapshot,
  formatSchemaDiagnostics,
  normalizeAllowlistEntries,
} from "./EffectLawsAllowlistSchemas.ts";

const GENERATED_FILE_BANNER = [
  "// @generated by tooling/configs/scripts/GenerateEffectLawsAllowlistSnapshot.ts",
  "// DO NOT EDIT MANUALLY.",
];

const EMPTY_DIAGNOSTICS = [] as const;

const normalizedAllowlistPath = normalizePath(ALLOWLIST_PATH);
const stringifyJsonPretty = SchemaGetter.stringifyJson({ space: 2 });

/**
 * Decode JSONC allowlist content into the immutable snapshot domain model.
 *
 * @param allowlistText - Raw JSONC allowlist content.
 * @returns Snapshot model containing normalized entries or schema diagnostics.
 * @since 0.0.0
 * @category Utility
 */
export const buildAllowlistSnapshotFromJsoncText = (
  allowlistText: string
): Effect.Effect<EffectLawsAllowlistSnapshot> =>
  pipe(
    decodeAllowlistDocumentFromJsoncText(allowlistText),
    Effect.map(
      (document) =>
        new EffectLawsAllowlistSnapshot({
          path: normalizedAllowlistPath,
          entries: normalizeAllowlistEntries(document.entries),
          diagnostics: EMPTY_DIAGNOSTICS,
        })
    ),
    Effect.catch((error) =>
      Effect.succeed(
        new EffectLawsAllowlistSnapshot({
          path: normalizedAllowlistPath,
          diagnostics: formatSchemaDiagnostics(error.issue),
        })
      )
    )
  );

/**
 * Render a generated TypeScript snapshot module.
 *
 * @param snapshot - Snapshot model to emit.
 * @returns Effect producing TypeScript module text exporting immutable snapshot data.
 * @since 0.0.0
 * @category Utility
 */
export const renderAllowlistSnapshotModule = (
  snapshot: EffectLawsAllowlistSnapshot
): Effect.Effect<string, SchemaIssue.Issue> =>
  pipe(
    Effect.succeed(encodeAllowlistSnapshot(snapshot)),
    Effect.flatMap((encodedSnapshot) => stringifyJsonPretty.run(O.some(encodedSnapshot), {})),
    Effect.map(O.getOrElse(() => "")),
    Effect.map((serializedSnapshot) =>
      [...GENERATED_FILE_BANNER, "", `export const ALLOWLIST_SNAPSHOT = ${serializedSnapshot} as const;`, ""].join("\n")
    )
  );

/**
 * Build and render a generated TypeScript snapshot module from JSONC input.
 *
 * @param allowlistText - Raw JSONC allowlist content.
 * @returns Effect producing generated TypeScript source.
 * @since 0.0.0
 * @category Utility
 */
export const buildAllowlistSnapshotModuleFromJsoncText = (
  allowlistText: string
): Effect.Effect<string, SchemaIssue.Issue> =>
  pipe(buildAllowlistSnapshotFromJsoncText(allowlistText), Effect.flatMap(renderAllowlistSnapshotModule));
