import { $IamClientId } from "@beep/identity/packages";

export const {
  $AdminId,
  $ApiKeyId,
  $DeviceAuthorizationId,
  $LastLoginMethodId,
  $MultiSessionId,
  $OauthId,
  $OidcId,
  $OrganizationId,
  $PasskeyId,
  $RecoverId,
  $SessionId,
  $SignInId,
  $SignOutId,
  $SignUpId,
  $SsoId,
  $StripeId,
  $TwoFactorId,
  $UserId,
  $VerifyId,
} = $IamClientId
  .compose("clients")
  .$ClientsId.compose(
    "admin",
    "api-key",
    "device-authorization",
    "last-login-method",
    "multi-session",
    "oauth",
    "oidc",
    "organization",
    "passkey",
    "recover",
    "session",
    "sign-in",
    "sign-out",
    "sign-up",
    "sso",
    "stripe",
    "two-factor",
    "user",
    "verify"
  );
