import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

import { KaServices } from "@beep/runtime-client";
import { RegistryProvider } from "@effect-atom/atom-react";
import Script from "next/script";
import { connection } from "next/server";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

import { runServerPromise } from "@beep/runtime-server";
import { getAppConfig } from "@beep/todox/app-config";
import { GlobalProviders } from "@beep/todox/global-providers";
import * as Effect from "effect/Effect";
import { ThemeProvider } from "next-themes";

const getInitialProps = getAppConfig.pipe(Effect.withSpan("getInitialProps"));

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const isDev = process.env.NODE_ENV === "development";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await connection();
  const appConfig = await runServerPromise(getInitialProps, "RootLayout.getInitialProps");
  return (
    <html lang={appConfig.lang ?? "en"} dir={appConfig.dir} className={inter.variable} suppressHydrationWarning>
      <head>
        {isDev && (
          <>
            <Script src="https://unpkg.com/react-grab@0.1.0-beta.5/dist/index.global.js" strategy="beforeInteractive" />
            <Script
              src="https://unpkg.com/@react-grab/claude-code@0.1.0-beta.5/dist/client.global.js"
              strategy="afterInteractive"
            />
          </>
        )}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <GlobalProviders appConfig={appConfig}>
          <RegistryProvider>
            <KaServices />
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
              {children}
            </ThemeProvider>
          </RegistryProvider>
        </GlobalProviders>
      </body>
    </html>
  );
}
