export * from "./Comment.repo";
export * from "./Discussion.repo";
export * from "./Document.repo";
export * from "./DocumentFile.repo";
export * from "./DocumentVersion.repo";
export * from "./KnowledgeBlock.repo";
export * from "./KnowledgePage.repo";
export * from "./KnowledgeSpace.repo";
export * from "./PageLink.repo";
