config:
  oipWeb:attachProductionDomains: "true"
  oipWeb:attachStagingDomain: "false"
  oipWeb:assetsBucketName: assets.oip.law
  oipWeb:awsRegion: us-east-1
  oipWeb:cloudflareZoneId: 144f81bdbe12b3a7530cdcc8d56b13cc
  oipWeb:legacyCloudflareZoneId: 0d26e874202f4579081926dc38b3bf80
  oipWeb:legacyProductionDomain: opip.law
  oipWeb:legacyStagingDomain: staging.opip.law
  oipWeb:legacyWwwDomain: www.opip.law
  oipWeb:projectName: oip-web
  oipWeb:productionBranch: main
  oipWeb:productionDomain: oip.law
  oipWeb:pulumiStateBucketName: oip-law-pulumi-state
  oipWeb:repository: beep-effect/beep-effect
  oipWeb:rootDirectory: apps/oip-web
  oipWeb:stagingBranch: staging
  oipWeb:stagingDomain: staging.oip.law
  oipWeb:vercelApexTarget: 76.76.21.21
  oipWeb:vercelAuthenticationDeploymentType: none
  oipWeb:wwwDomain: www.oip.law
  oipWeb:hubSpotAccountId: "246203876"
  oipWeb:hubSpotServiceKey:
    secure: v1:iUZDwKJZYViTI3vl:1mg9iTFks9Rbk7DNlr2kBHDvnbEkSaDOiZJjYAYAt6Cav20kaU8g9qF3xRSZkcajXxGFfVldfABsP9Yf
encryptionsalt: v1:ArE3HbpUuJk=:v1:JVQMqcTyT0iDVJdg:aVYL3DgkQAO3RR2C25nWR8Wob3TXBQ==
