config:
  oipWeb:attachProductionDomains: "false"
  oipWeb:attachStagingDomain: "true"
  oipWeb:assetsBucketName: staging-assets.oip.law
  oipWeb:pulumiStateBucketName: oip-law-pulumi-state
  oipWeb:awsRegion: us-east-1
  oipWeb:cloudflareZoneId: 144f81bdbe12b3a7530cdcc8d56b13cc
  oipWeb:legacyCloudflareZoneId: 0d26e874202f4579081926dc38b3bf80
  oipWeb:legacyProductionDomain: opip.law
  oipWeb:legacyStagingDomain: staging.opip.law
  oipWeb:legacyWwwDomain: www.opip.law
  oipWeb:projectName: oip-web-staging
  oipWeb:productionBranch: main
  oipWeb:repository: beep-effect/beep-effect
  oipWeb:rootDirectory: apps/oip-web
  oipWeb:stagingBranch: main
  oipWeb:stagingDomain: staging.oip.law
  oipWeb:vercelApexTarget: 76.76.21.21
  oipWeb:vercelAuthenticationDeploymentType: none
  oipWeb:hubSpotAccountId: "246203876"
  oipWeb:hubSpotServiceKey:
    secure: v1:XEsDLRxOQVGaArr/:Mb2z7gccHpOZ64SCL3HGTqMt4pg+LsH3mZEObVzbWtm6o/kY0dEcCS4Iq3Z6Zn/h96AX8U70ZG7uYlVb
encryptionsalt: v1:fqQdn9tkmAc=:v1:cwXzl12rh4BfgroT:d/vugmtdMVFDl8zAdF+YOXVM7O4giw==
