/**
 * Official ISO 4217 target definition.
 *
 * @module
 * @since 0.0.0
 */

import { $RepoCliId } from "@beep/identity/packages";
import { Effect, flow, MutableHashMap, Order, pipe } from "effect";
import * as A from "effect/Array";
import * as Eq from "effect/Equal";
import * as O from "effect/Option";
import * as P from "effect/Predicate";
import * as S from "effect/Schema";
import * as Str from "effect/String";
import * as jsonc from "jsonc-parser";
import type { SyncDataTarget, SyncDataTargetProjection } from "../internal/Models.js";
import { SyncDataToTsError } from "../internal/Models.js";

const $I = $RepoCliId.create("commands/SyncDataToTs/targets/Iso4217");

/**
 * Official SIX XML source for ISO 4217 List One.
 *
 * @category Configuration
 * @since 0.0.0
 */
export const ISO4217_SOURCE_URL =
  "https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xml" as const;

class Iso4217CurrencyNameWithMetadata extends S.Class<Iso4217CurrencyNameWithMetadata>(
  $I`Iso4217CurrencyNameWithMetadata`
)(
  {
    text: S.String,
    IsFund: S.optional(S.String),
  },
  $I.annote("Iso4217CurrencyNameWithMetadata", {
    description: "Currency name node emitted when the ISO 4217 XML uses inline attributes.",
  })
) {}

const Iso4217CurrencyName = S.Union([S.String, Iso4217CurrencyNameWithMetadata]).pipe(
  S.annotate(
    $I.annote("Iso4217CurrencyName", {
      description: "Currency name node emitted by the ISO 4217 XML parser.",
    })
  )
);

class Iso4217CurrencyCountry extends S.Class<Iso4217CurrencyCountry>($I`Iso4217CurrencyCountry`)(
  {
    CtryNm: S.String,
    CcyNm: Iso4217CurrencyName,
    Ccy: S.optional(S.String),
    CcyNbr: S.optional(S.String),
    CcyMnrUnts: S.optional(S.String),
  },
  $I.annote("Iso4217CurrencyCountry", {
    description: "Single country or fund row from the official ISO 4217 List One XML document.",
  })
) {}

class Iso4217CurrencyTable extends S.Class<Iso4217CurrencyTable>($I`Iso4217CurrencyTable`)(
  {
    CcyNtry: Iso4217CurrencyCountry.pipe(S.Array),
  },
  $I.annote("Iso4217CurrencyTable", {
    description: "Currency table section from the official ISO 4217 XML document.",
  })
) {}

class Iso4217Root extends S.Class<Iso4217Root>($I`Iso4217Root`)(
  {
    Pblshd: S.String,
    CcyTbl: Iso4217CurrencyTable,
  },
  $I.annote("Iso4217Root", {
    description: "Top-level ISO 4217 XML document payload.",
  })
) {}

class Iso4217Document extends S.Class<Iso4217Document>($I`Iso4217Document`)(
  {
    ISO_4217: Iso4217Root,
  },
  $I.annote("Iso4217Document", {
    description: "Decoded XML document for the official SIX ISO 4217 List One feed.",
  })
) {}

class Iso4217CurrencyEntry extends S.Class<Iso4217CurrencyEntry>($I`Iso4217CurrencyEntry`)(
  {
    code: S.String,
    number: S.String,
    digits: S.Number,
    currency: S.String,
    countries: S.Array(S.String),
  },
  $I.annote("Iso4217CurrencyEntry", {
    description: "Normalized ISO 4217 currency entry rendered into @beep/data.",
  })
) {}

type Iso4217CurrencyEntryType = typeof Iso4217CurrencyEntry.Type;
const isIso4217CurrencyNameWithMetadata = S.is(Iso4217CurrencyNameWithMetadata);

const encodeUnknownJson = S.encodeUnknownSync(S.UnknownFromJsonString);

const formatTsLiteral = (value: unknown): string => {
  const encoded = encodeUnknownJson(value);
  const edits = jsonc.format(encoded, undefined, {
    tabSize: 2,
    insertSpaces: true,
  });
  return pipe(jsonc.applyEdits(encoded, edits), Str.replaceAll(/"([A-Za-z_$][A-Za-z0-9_$]*)":/g, "$1:"));
};

const normalizeWhitespace = flow(Str.replaceAll(/\s+/gu, " "), Str.trim);

const normalizeCountryName = flow(normalizeWhitespace, Str.toLocaleLowerCase("en-US"), (str) =>
  str.replaceAll(
    /(^|[\s()/_',.-])([\p{L}\p{N}])/gu,
    (_wholeMatch, prefix: string, segment: string) => `${prefix}${segment.toLocaleUpperCase("en-US")}`
  )
);

const extractCurrencyName = (value: typeof Iso4217CurrencyName.Type): string =>
  isIso4217CurrencyNameWithMetadata(value) ? value.text : value;

const parseMinorUnits = (value: string, code: string): Effect.Effect<number, SyncDataToTsError> =>
  value === "N.A."
    ? Effect.succeed(0)
    : (() => {
        const parsed = Number.parseInt(value, 10);
        return Number.isNaN(parsed)
          ? Effect.fail(
              new SyncDataToTsError({
                message: `Failed to normalize ISO 4217 minor units for ${code}: invalid minor unit "${value}".`,
                targetId: "iso4217",
              })
            )
          : Effect.succeed(parsed);
      })();

const renderIso4217Module = (published: string, values: ReadonlyArray<Iso4217CurrencyEntryType>): string => {
  const renderedValues = formatTsLiteral(values);

  return `/**
 * Generated ISO 4217 currency data.
 *
 * Generated by \`bun run beep sync-data-to-ts --target iso4217\`.
 * Source: ${ISO4217_SOURCE_URL}
 * Published: ${published}
 *
 * @module
 * @since 0.0.0
 */

/**
 * Published date reported by the official ISO 4217 List One feed.
 *
 * @since 0.0.0
 */
export const CurrencyCodeDataPublished = ${formatTsLiteral(published)} as const;

/**
 * Official source URL for the ISO 4217 List One feed.
 *
 * @since 0.0.0
 */
export const CurrencyCodeDataSourceUrl = ${formatTsLiteral(ISO4217_SOURCE_URL)} as const;

/**
 * Normalized ISO 4217 currency entries emitted from the official feed.
 *
 * @since 0.0.0
 */
export const CurrencyCodeDataValues = ${renderedValues} as const;
`;
};

const projectIso4217Document: SyncDataTarget["project"] = Effect.fn("SyncDataToTs.Iso4217.projectIso4217Document")(
  function* (document) {
    const decoded = yield* S.decodeUnknownEffect(Iso4217Document)(document).pipe(
      Effect.mapError(
        (cause) =>
          new SyncDataToTsError({
            message: `Failed to decode the official ISO 4217 XML payload: ${cause.message}`,
            targetId: "iso4217",
          })
      )
    );

    const published = decoded.ISO_4217.Pblshd;
    const grouped = MutableHashMap.empty<string, Iso4217CurrencyEntryType>();

    for (const row of decoded.ISO_4217.CcyTbl.CcyNtry) {
      if (P.isUndefined(row.Ccy) || P.isUndefined(row.CcyNbr) || P.isUndefined(row.CcyMnrUnts)) {
        if (extractCurrencyName(row.CcyNm) === "No universal currency") {
          continue;
        }

        return yield* new SyncDataToTsError({
          message: `Encountered an unexpected ISO 4217 row without complete currency fields for ${row.CtryNm}.`,
          targetId: "iso4217",
        });
      }

      const country = normalizeCountryName(row.CtryNm);
      const currency = extractCurrencyName(row.CcyNm);
      const digits = yield* parseMinorUnits(row.CcyMnrUnts, row.Ccy);
      const existing = MutableHashMap.get(grouped, row.Ccy);

      if (O.isNone(existing)) {
        MutableHashMap.set(
          grouped,
          row.Ccy,
          new Iso4217CurrencyEntry({
            code: row.Ccy,
            number: row.CcyNbr,
            digits,
            currency,
            countries: [country],
          })
        );
        continue;
      }

      if (
        existing.value.number !== row.CcyNbr ||
        existing.value.digits !== digits ||
        existing.value.currency !== currency
      ) {
        return yield* new SyncDataToTsError({
          message: `Encountered inconsistent ISO 4217 currency data for ${row.Ccy}.`,
          targetId: "iso4217",
        });
      }

      const countries = A.some(existing.value.countries, Eq.equals(country))
        ? existing.value.countries
        : A.append(existing.value.countries, country);

      MutableHashMap.set(
        grouped,
        row.Ccy,
        new Iso4217CurrencyEntry({
          ...existing.value,
          countries,
        })
      );
    }

    const values = pipe(
      A.fromIterable(MutableHashMap.values(grouped)),
      A.map(
        (entry) =>
          new Iso4217CurrencyEntry({
            ...entry,
            countries: A.sort(entry.countries, Order.String),
          })
      ),
      A.sort(Order.mapInput(Order.String, ({ code }: Iso4217CurrencyEntryType) => code))
    );

    const projection: SyncDataTargetProjection = {
      content: renderIso4217Module(published, values),
      recordCount: A.length(values),
      summary: `${A.length(values)} currency entries published ${published}`,
    };

    return projection;
  }
);

/**
 * Checked-in sync target for the official SIX ISO 4217 List One XML feed.
 *
 * @category Configuration
 * @since 0.0.0
 */
export const iso4217Target: SyncDataTarget = {
  id: "iso4217",
  description: "Sync official ISO 4217 currency codes from SIX List One (XML).",
  sourceUrl: ISO4217_SOURCE_URL,
  outputPath: "packages/common/data/src/generated/iso4217.ts",
  format: "xml",
  project: projectIso4217Document,
};
