/**
 * Generated Runpod REST schemas and operation descriptors.
 * Do not edit this file by hand.
 * cspell:words CUDA FHHL Mbps VCPU dtos vcpu
 *
 * @packageDocumentation
 * @since 0.1.0
 */

import { $RunpodId } from "@beep/identity";
import { LiteralKit } from "@beep/schema";
import { pipe } from "effect";
import * as S from "effect/Schema";
import type { Effect } from "effect";

const $I = $RunpodId.create("Runpod.generated");

/**
 * Pods schema generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { Pods } from "@beep/runpod"
 *
 * console.log(Pods.ast)
 * ```
 *
 * @category schemas
 * @since 0.1.0
 */
export const Pods = S.suspend(() => Pod).pipe(
  S.Array,
  $I.annoteSchema("Pods", {
    description: "Pods schema generated from the Runpod OpenAPI document.",
  })
);

/**
 * Pods value generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import type { Pods } from "@beep/runpod"
 *
 * type PodsValue = Pods
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type Pods = typeof Pods.Type;

/**
 * Pod model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { Pod } from "@beep/runpod"
 *
 * console.log(Pod.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class Pod extends S.Class<Pod>($I`Pod`)(
  {
    adjustedCostPerHr: S.Finite.pipe(S.optionalKey),
    aiApiId: S.String.pipe(S.optionalKey),
    consumerUserId: S.String.pipe(S.optionalKey),
    containerDiskInGb: S.Finite.pipe(S.optionalKey),
    containerRegistryAuthId: S.String.pipe(S.optionalKey),
    costPerHr: S.Finite.pipe(S.optionalKey),
    cpuFlavorId: S.String.pipe(S.optionalKey),
    desiredStatus: LiteralKit(["RUNNING", "EXITED", "TERMINATED"]).pipe(S.optionalKey),
    dockerEntrypoint: S.String.pipe(S.Array, S.optionalKey),
    dockerStartCmd: S.String.pipe(S.Array, S.optionalKey),
    endpointId: S.String.pipe(S.optionalKey),
    env: S.Record(S.String, S.Unknown).pipe(S.optionalKey),
    gpu: S.Struct({
      id: S.String.pipe(S.optionalKey),
      count: S.Finite.pipe(S.optionalKey),
      displayName: S.String.pipe(S.optionalKey),
      securePrice: S.Finite.pipe(S.optionalKey),
      communityPrice: S.Finite.pipe(S.optionalKey),
      oneMonthPrice: S.Finite.pipe(S.optionalKey),
      threeMonthPrice: S.Finite.pipe(S.optionalKey),
      sixMonthPrice: S.Finite.pipe(S.optionalKey),
      oneWeekPrice: S.Finite.pipe(S.optionalKey),
      communitySpotPrice: S.Finite.pipe(S.optionalKey),
      secureSpotPrice: S.Finite.pipe(S.optionalKey),
    }).pipe(S.optionalKey),
    id: S.String.pipe(S.optionalKey),
    image: S.String.pipe(S.optionalKey),
    interruptible: S.Boolean.pipe(S.optionalKey),
    lastStartedAt: S.String.pipe(S.optionalKey),
    lastStatusChange: S.String.pipe(S.optionalKey),
    locked: S.Boolean.pipe(S.optionalKey),
    machine: S.Struct({
      minPodGpuCount: S.Finite.pipe(S.optionalKey),
      gpuTypeId: S.String.pipe(S.optionalKey),
      gpuType: S.Struct({
        id: S.String.pipe(S.optionalKey),
        count: S.Finite.pipe(S.optionalKey),
        displayName: S.String.pipe(S.optionalKey),
        securePrice: S.Finite.pipe(S.optionalKey),
        communityPrice: S.Finite.pipe(S.optionalKey),
        oneMonthPrice: S.Finite.pipe(S.optionalKey),
        threeMonthPrice: S.Finite.pipe(S.optionalKey),
        sixMonthPrice: S.Finite.pipe(S.optionalKey),
        oneWeekPrice: S.Finite.pipe(S.optionalKey),
        communitySpotPrice: S.Finite.pipe(S.optionalKey),
        secureSpotPrice: S.Finite.pipe(S.optionalKey),
      }).pipe(S.optionalKey),
      cpuCount: S.Finite.pipe(S.optionalKey),
      cpuTypeId: S.String.pipe(S.optionalKey),
      cpuType: S.Struct({
        id: S.String.pipe(S.optionalKey),
        displayName: S.String.pipe(S.optionalKey),
        cores: S.Finite.pipe(S.optionalKey),
        threadsPerCore: S.Finite.pipe(S.optionalKey),
        groupId: S.String.pipe(S.optionalKey),
      }).pipe(S.optionalKey),
      location: S.String.pipe(S.optionalKey),
      dataCenterId: S.String.pipe(S.optionalKey),
      diskThroughputMBps: S.Finite.pipe(S.optionalKey),
      maxDownloadSpeedMbps: S.Finite.pipe(S.optionalKey),
      maxUploadSpeedMbps: S.Finite.pipe(S.optionalKey),
      supportPublicIp: S.Boolean.pipe(S.optionalKey),
      secureCloud: S.Boolean.pipe(S.optionalKey),
      maintenanceStart: S.String.pipe(S.optionalKey),
      maintenanceEnd: S.String.pipe(S.optionalKey),
      maintenanceNote: S.String.pipe(S.optionalKey),
      note: S.String.pipe(S.optionalKey),
      costPerHr: S.Finite.pipe(S.optionalKey),
      currentPricePerGpu: S.Finite.pipe(S.optionalKey),
      gpuAvailable: S.Finite.pipe(S.optionalKey),
      gpuDisplayName: S.String.pipe(S.optionalKey),
    }).pipe(S.optionalKey),
    machineId: S.String.pipe(S.optionalKey),
    memoryInGb: S.Finite.pipe(S.optionalKey),
    name: S.String.pipe(S.optionalKey),
    networkVolume: S.Struct({
      id: S.String.pipe(S.optionalKey),
      name: S.String.pipe(S.optionalKey),
      size: S.Finite.pipe(S.optionalKey),
      dataCenterId: S.String.pipe(S.optionalKey),
    }).pipe(S.optionalKey),
    portMappings: S.Record(S.String, S.Unknown).pipe(S.NullOr, S.optionalKey),
    ports: S.String.pipe(S.Array, S.optionalKey),
    publicIp: S.String.pipe(S.NullOr, S.optionalKey),
    savingsPlans: S.suspend(() => SavingsPlan).pipe(S.Array, S.optionalKey),
    slsVersion: S.Finite.pipe(S.optionalKey),
    templateId: S.String.pipe(S.optionalKey),
    vcpuCount: S.Finite.pipe(S.optionalKey),
    volumeEncrypted: S.Boolean.pipe(S.optionalKey),
    volumeInGb: S.Finite.pipe(S.optionalKey),
    volumeMountPath: S.String.pipe(S.optionalKey),
  },
  $I.annote("Pod", {
    description: "Pod model returned by the Runpod REST API.",
  })
) {}

/**
 * PodUpdateInPlaceInput model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { PodUpdateInPlaceInput } from "@beep/runpod"
 *
 * console.log(PodUpdateInPlaceInput.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class PodUpdateInPlaceInput extends S.Class<PodUpdateInPlaceInput>($I`PodUpdateInPlaceInput`)(
  {
    locked: S.Boolean.pipe(S.optionalKey),
    name: S.String.pipe(S.optionalKey),
  },
  $I.annote("PodUpdateInPlaceInput", {
    description: "PodUpdateInPlaceInput model returned by the Runpod REST API.",
  })
) {}

/**
 * PodUpdateInput model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { PodUpdateInput } from "@beep/runpod"
 *
 * console.log(PodUpdateInput.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class PodUpdateInput extends S.Class<PodUpdateInput>($I`PodUpdateInput`)(
  {
    containerDiskInGb: S.Finite.pipe(S.NullOr, S.optionalKey),
    containerRegistryAuthId: S.String.pipe(S.optionalKey),
    dockerEntrypoint: S.String.pipe(S.Array, S.optionalKey),
    dockerStartCmd: S.String.pipe(S.Array, S.optionalKey),
    env: S.Record(S.String, S.Unknown).pipe(S.optionalKey),
    globalNetworking: S.Boolean.pipe(S.optionalKey),
    imageName: S.String.pipe(S.optionalKey),
    locked: S.Boolean.pipe(S.optionalKey),
    name: S.String.pipe(S.optionalKey),
    ports: S.String.pipe(S.Array, S.optionalKey),
    volumeInGb: S.Finite.pipe(S.NullOr, S.optionalKey),
    volumeMountPath: S.String.pipe(S.optionalKey),
  },
  $I.annote("PodUpdateInput", {
    description: "PodUpdateInput model returned by the Runpod REST API.",
  })
) {}

/**
 * PodCreateInput model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { PodCreateInput } from "@beep/runpod"
 *
 * console.log(PodCreateInput.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class PodCreateInput extends S.Class<PodCreateInput>($I`PodCreateInput`)(
  {
    allowedCudaVersions: S.String.pipe(S.Array, S.optionalKey),
    cloudType: LiteralKit(["SECURE", "COMMUNITY"]).pipe(S.optionalKey),
    computeType: LiteralKit(["GPU", "CPU"]).pipe(S.optionalKey),
    containerDiskInGb: S.Finite.pipe(S.NullOr, S.optionalKey),
    containerRegistryAuthId: S.String.pipe(S.optionalKey),
    countryCodes: S.String.pipe(S.Array, S.optionalKey),
    cpuFlavorIds: S.String.pipe(S.Array, S.optionalKey),
    cpuFlavorPriority: S.String.pipe(S.optionalKey),
    dataCenterIds: S.String.pipe(S.Array, S.optionalKey),
    dataCenterPriority: S.String.pipe(S.optionalKey),
    dockerEntrypoint: S.String.pipe(S.Array, S.optionalKey),
    dockerStartCmd: S.String.pipe(S.Array, S.optionalKey),
    env: S.Record(S.String, S.Unknown).pipe(S.optionalKey),
    globalNetworking: S.Boolean.pipe(S.optionalKey),
    gpuCount: S.Finite.pipe(S.optionalKey),
    gpuTypeIds: S.String.pipe(S.Array, S.optionalKey),
    gpuTypePriority: S.String.pipe(S.optionalKey),
    imageName: S.String.pipe(S.optionalKey),
    interruptible: S.Boolean.pipe(S.optionalKey),
    locked: S.Boolean.pipe(S.optionalKey),
    minDiskBandwidthMBps: S.Finite.pipe(S.optionalKey),
    minDownloadMbps: S.Finite.pipe(S.optionalKey),
    minRAMPerGPU: S.Finite.pipe(S.optionalKey),
    minUploadMbps: S.Finite.pipe(S.optionalKey),
    minVCPUPerGPU: S.Finite.pipe(S.optionalKey),
    name: S.String.pipe(S.optionalKey),
    networkVolumeId: S.String.pipe(S.optionalKey),
    ports: S.String.pipe(S.Array, S.optionalKey),
    supportPublicIp: S.Boolean.pipe(S.optionalKey),
    templateId: S.String.pipe(S.optionalKey),
    vcpuCount: S.Finite.pipe(S.optionalKey),
    volumeInGb: S.Finite.pipe(S.NullOr, S.optionalKey),
    volumeMountPath: S.String.pipe(S.optionalKey),
  },
  $I.annote("PodCreateInput", {
    description: "PodCreateInput model returned by the Runpod REST API.",
  })
) {}

/**
 * NetworkVolumes schema generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { NetworkVolumes } from "@beep/runpod"
 *
 * console.log(NetworkVolumes.ast)
 * ```
 *
 * @category schemas
 * @since 0.1.0
 */
export const NetworkVolumes = pipe(
  S.Struct({
    id: S.String.pipe(S.optionalKey),
    name: S.String.pipe(S.optionalKey),
    size: S.Finite.pipe(S.optionalKey),
    dataCenterId: S.String.pipe(S.optionalKey),
  }),
  S.Array,
  $I.annoteSchema("NetworkVolumes", {
    description: "NetworkVolumes schema generated from the Runpod OpenAPI document.",
  })
);

/**
 * NetworkVolumes value generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import type { NetworkVolumes } from "@beep/runpod"
 *
 * type NetworkVolumesValue = NetworkVolumes
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type NetworkVolumes = typeof NetworkVolumes.Type;

/**
 * NetworkVolume model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { NetworkVolume } from "@beep/runpod"
 *
 * console.log(NetworkVolume.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class NetworkVolume extends S.Class<NetworkVolume>($I`NetworkVolume`)(
  {
    dataCenterId: S.String.pipe(S.optionalKey),
    id: S.String.pipe(S.optionalKey),
    name: S.String.pipe(S.optionalKey),
    size: S.Finite.pipe(S.optionalKey),
  },
  $I.annote("NetworkVolume", {
    description: "NetworkVolume model returned by the Runpod REST API.",
  })
) {}

/**
 * NetworkVolumeCreateInput model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { NetworkVolumeCreateInput } from "@beep/runpod"
 *
 * console.log(NetworkVolumeCreateInput.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class NetworkVolumeCreateInput extends S.Class<NetworkVolumeCreateInput>($I`NetworkVolumeCreateInput`)(
  {
    dataCenterId: S.String,
    name: S.String,
    size: S.Finite,
  },
  $I.annote("NetworkVolumeCreateInput", {
    description: "NetworkVolumeCreateInput model returned by the Runpod REST API.",
  })
) {}

/**
 * NetworkVolumeUpdateInput model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { NetworkVolumeUpdateInput } from "@beep/runpod"
 *
 * console.log(NetworkVolumeUpdateInput.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class NetworkVolumeUpdateInput extends S.Class<NetworkVolumeUpdateInput>($I`NetworkVolumeUpdateInput`)(
  {
    name: S.String.pipe(S.optionalKey),
    size: S.Finite.pipe(S.optionalKey),
  },
  $I.annote("NetworkVolumeUpdateInput", {
    description: "NetworkVolumeUpdateInput model returned by the Runpod REST API.",
  })
) {}

/**
 * Templates schema generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { Templates } from "@beep/runpod"
 *
 * console.log(Templates.ast)
 * ```
 *
 * @category schemas
 * @since 0.1.0
 */
export const Templates = S.suspend(() => Template).pipe(
  S.Array,
  $I.annoteSchema("Templates", {
    description: "Templates schema generated from the Runpod OpenAPI document.",
  })
);

/**
 * Templates value generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import type { Templates } from "@beep/runpod"
 *
 * type TemplatesValue = Templates
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type Templates = typeof Templates.Type;

/**
 * Template model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { Template } from "@beep/runpod"
 *
 * console.log(Template.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class Template extends S.Class<Template>($I`Template`)(
  {
    category: S.String.pipe(S.optionalKey),
    containerDiskInGb: S.Finite.pipe(S.optionalKey),
    containerRegistryAuthId: S.String.pipe(S.optionalKey),
    dockerEntrypoint: S.String.pipe(S.Array, S.optionalKey),
    dockerStartCmd: S.String.pipe(S.Array, S.optionalKey),
    earned: S.Finite.pipe(S.optionalKey),
    env: S.Record(S.String, S.Unknown).pipe(S.optionalKey),
    id: S.String.pipe(S.optionalKey),
    imageName: S.String.pipe(S.optionalKey),
    isPublic: S.Boolean.pipe(S.optionalKey),
    isRunpod: S.Boolean.pipe(S.optionalKey),
    isServerless: S.Boolean.pipe(S.optionalKey),
    name: S.String.pipe(S.optionalKey),
    ports: S.String.pipe(S.Array, S.optionalKey),
    readme: S.String.pipe(S.optionalKey),
    runtimeInMin: S.Finite.pipe(S.optionalKey),
    volumeInGb: S.Finite.pipe(S.optionalKey),
    volumeMountPath: S.String.pipe(S.optionalKey),
  },
  $I.annote("Template", {
    description: "Template model returned by the Runpod REST API.",
  })
) {}

/**
 * TemplateCreateInput model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { TemplateCreateInput } from "@beep/runpod"
 *
 * console.log(TemplateCreateInput.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class TemplateCreateInput extends S.Class<TemplateCreateInput>($I`TemplateCreateInput`)(
  {
    category: LiteralKit(["NVIDIA", "AMD", "CPU"]).pipe(S.optionalKey),
    containerDiskInGb: S.Finite.pipe(S.optionalKey),
    containerRegistryAuthId: S.String.pipe(S.optionalKey),
    dockerEntrypoint: S.String.pipe(S.Array, S.optionalKey),
    dockerStartCmd: S.String.pipe(S.Array, S.optionalKey),
    env: S.Record(S.String, S.Unknown).pipe(S.optionalKey),
    imageName: S.String,
    isPublic: S.Boolean.pipe(S.optionalKey),
    isServerless: S.Boolean.pipe(S.optionalKey),
    name: S.String,
    ports: S.String.pipe(S.Array, S.optionalKey),
    readme: S.String.pipe(S.optionalKey),
    volumeInGb: S.Finite.pipe(S.optionalKey),
    volumeMountPath: S.String.pipe(S.optionalKey),
  },
  $I.annote("TemplateCreateInput", {
    description: "TemplateCreateInput model returned by the Runpod REST API.",
  })
) {}

/**
 * TemplateUpdateInPlaceInput model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { TemplateUpdateInPlaceInput } from "@beep/runpod"
 *
 * console.log(TemplateUpdateInPlaceInput.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class TemplateUpdateInPlaceInput extends S.Class<TemplateUpdateInPlaceInput>($I`TemplateUpdateInPlaceInput`)(
  {
    isPublic: S.Boolean.pipe(S.optionalKey),
    name: S.String.pipe(S.optionalKey),
    readme: S.String.pipe(S.optionalKey),
    volumeInGb: S.Finite.pipe(S.optionalKey),
    volumeMountPath: S.String.pipe(S.optionalKey),
  },
  $I.annote("TemplateUpdateInPlaceInput", {
    description: "TemplateUpdateInPlaceInput model returned by the Runpod REST API.",
  })
) {}

/**
 * TemplateUpdateInput model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { TemplateUpdateInput } from "@beep/runpod"
 *
 * console.log(TemplateUpdateInput.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class TemplateUpdateInput extends S.Class<TemplateUpdateInput>($I`TemplateUpdateInput`)(
  {
    containerDiskInGb: S.Finite.pipe(S.optionalKey),
    containerRegistryAuthId: S.String.pipe(S.optionalKey),
    dockerEntrypoint: S.String.pipe(S.Array, S.optionalKey),
    dockerStartCmd: S.String.pipe(S.Array, S.optionalKey),
    env: S.Record(S.String, S.Unknown).pipe(S.optionalKey),
    imageName: S.String.pipe(S.optionalKey),
    isPublic: S.Boolean.pipe(S.optionalKey),
    name: S.String.pipe(S.optionalKey),
    ports: S.String.pipe(S.Array, S.optionalKey),
    readme: S.String.pipe(S.optionalKey),
    volumeInGb: S.Finite.pipe(S.optionalKey),
    volumeMountPath: S.String.pipe(S.optionalKey),
  },
  $I.annote("TemplateUpdateInput", {
    description: "TemplateUpdateInput model returned by the Runpod REST API.",
  })
) {}

/**
 * Endpoints schema generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { Endpoints } from "@beep/runpod"
 *
 * console.log(Endpoints.ast)
 * ```
 *
 * @category schemas
 * @since 0.1.0
 */
export const Endpoints = S.suspend(() => Endpoint).pipe(
  S.Array,
  $I.annoteSchema("Endpoints", {
    description: "Endpoints schema generated from the Runpod OpenAPI document.",
  })
);

/**
 * Endpoints value generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import type { Endpoints } from "@beep/runpod"
 *
 * type EndpointsValue = Endpoints
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type Endpoints = typeof Endpoints.Type;

/**
 * Endpoint model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { Endpoint } from "@beep/runpod"
 *
 * console.log(Endpoint.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class Endpoint extends S.Class<Endpoint>($I`Endpoint`)(
  {
    allowedCudaVersions: S.String.pipe(S.Array, S.optionalKey),
    computeType: LiteralKit(["CPU", "GPU"]).pipe(S.optionalKey),
    createdAt: S.String.pipe(S.optionalKey),
    dataCenterIds: S.String.pipe(S.Array, S.optionalKey),
    env: S.Record(S.String, S.Unknown).pipe(S.optionalKey),
    executionTimeoutMs: S.Finite.pipe(S.optionalKey),
    gpuCount: S.Finite.pipe(S.optionalKey),
    gpuTypeIds: S.String.pipe(S.Array, S.optionalKey),
    id: S.String.pipe(S.optionalKey),
    idleTimeout: S.Finite.pipe(S.optionalKey),
    instanceIds: S.String.pipe(S.Array, S.optionalKey),
    minCudaVersion: S.String.pipe(S.optionalKey),
    name: S.String.pipe(S.optionalKey),
    networkVolumeId: S.String.pipe(S.optionalKey),
    networkVolumeIds: S.String.pipe(S.Array, S.optionalKey),
    scalerType: LiteralKit(["QUEUE_DELAY", "REQUEST_COUNT"]).pipe(S.optionalKey),
    scalerValue: S.Finite.pipe(S.optionalKey),
    template: S.suspend(() => Template).pipe(S.optionalKey),
    templateId: S.String.pipe(S.optionalKey),
    userId: S.String.pipe(S.optionalKey),
    version: S.Finite.pipe(S.optionalKey),
    workers: S.suspend(() => Pod).pipe(S.Array, S.optionalKey),
    workersMax: S.Finite.pipe(S.optionalKey),
    workersMin: S.Finite.pipe(S.optionalKey),
  },
  $I.annote("Endpoint", {
    description: "Endpoint model returned by the Runpod REST API.",
  })
) {}

/**
 * EndpointUpdateInPlaceInput model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { EndpointUpdateInPlaceInput } from "@beep/runpod"
 *
 * console.log(EndpointUpdateInPlaceInput.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class EndpointUpdateInPlaceInput extends S.Class<EndpointUpdateInPlaceInput>($I`EndpointUpdateInPlaceInput`)(
  {
    executionTimeoutMs: S.Finite.pipe(S.optionalKey),
    flashboot: S.Boolean.pipe(S.optionalKey),
    idleTimeout: S.Finite.pipe(S.optionalKey),
    name: S.String.pipe(S.optionalKey),
    scalerType: LiteralKit(["QUEUE_DELAY", "REQUEST_COUNT"]).pipe(S.optionalKey),
    scalerValue: S.Finite.pipe(S.optionalKey),
    workersMax: S.Finite.pipe(S.optionalKey),
    workersMin: S.Finite.pipe(S.optionalKey),
  },
  $I.annote("EndpointUpdateInPlaceInput", {
    description: "EndpointUpdateInPlaceInput model returned by the Runpod REST API.",
  })
) {}

/**
 * EndpointUpdateInput model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { EndpointUpdateInput } from "@beep/runpod"
 *
 * console.log(EndpointUpdateInput.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class EndpointUpdateInput extends S.Class<EndpointUpdateInput>($I`EndpointUpdateInput`)(
  {
    allowedCudaVersions: S.String.pipe(S.Array, S.optionalKey),
    cpuFlavorIds: S.String.pipe(S.Array, S.optionalKey),
    dataCenterIds: S.String.pipe(S.Array, S.optionalKey),
    executionTimeoutMs: S.Finite.pipe(S.optionalKey),
    flashboot: S.Boolean.pipe(S.optionalKey),
    gpuCount: S.Finite.pipe(S.optionalKey),
    gpuTypeIds: S.String.pipe(S.Array, S.optionalKey),
    idleTimeout: S.Finite.pipe(S.optionalKey),
    minCudaVersion: S.String.pipe(S.optionalKey),
    name: S.String.pipe(S.optionalKey),
    networkVolumeId: S.String.pipe(S.optionalKey),
    networkVolumeIds: S.String.pipe(S.Array, S.optionalKey),
    scalerType: LiteralKit(["QUEUE_DELAY", "REQUEST_COUNT"]).pipe(S.optionalKey),
    scalerValue: S.Finite.pipe(S.optionalKey),
    templateId: S.String.pipe(S.optionalKey),
    vcpuCount: S.Finite.pipe(S.optionalKey),
    workersMax: S.Finite.pipe(S.optionalKey),
    workersMin: S.Finite.pipe(S.optionalKey),
  },
  $I.annote("EndpointUpdateInput", {
    description: "EndpointUpdateInput model returned by the Runpod REST API.",
  })
) {}

/**
 * EndpointCreateInput model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { EndpointCreateInput } from "@beep/runpod"
 *
 * console.log(EndpointCreateInput.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class EndpointCreateInput extends S.Class<EndpointCreateInput>($I`EndpointCreateInput`)(
  {
    allowedCudaVersions: S.String.pipe(S.Array, S.optionalKey),
    computeType: LiteralKit(["GPU", "CPU"]).pipe(S.optionalKey),
    cpuFlavorIds: S.String.pipe(S.Array, S.optionalKey),
    dataCenterIds: S.String.pipe(S.Array, S.optionalKey),
    executionTimeoutMs: S.Finite.pipe(S.optionalKey),
    flashboot: S.Boolean.pipe(S.optionalKey),
    gpuCount: S.Finite.pipe(S.optionalKey),
    gpuTypeIds: S.String.pipe(S.Array, S.optionalKey),
    idleTimeout: S.Finite.pipe(S.optionalKey),
    minCudaVersion: S.String.pipe(S.optionalKey),
    name: S.String.pipe(S.optionalKey),
    networkVolumeId: S.String.pipe(S.optionalKey),
    networkVolumeIds: S.String.pipe(S.Array, S.optionalKey),
    scalerType: LiteralKit(["QUEUE_DELAY", "REQUEST_COUNT"]).pipe(S.optionalKey),
    scalerValue: S.Finite.pipe(S.optionalKey),
    templateId: S.String,
    vcpuCount: S.Finite.pipe(S.optionalKey),
    workersMax: S.Finite.pipe(S.optionalKey),
    workersMin: S.Finite.pipe(S.optionalKey),
  },
  $I.annote("EndpointCreateInput", {
    description: "EndpointCreateInput model returned by the Runpod REST API.",
  })
) {}

/**
 * User schema generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { User } from "@beep/runpod"
 *
 * console.log(User.ast)
 * ```
 *
 * @category schemas
 * @since 0.1.0
 */
export const User = S.String.pipe(
  $I.annoteSchema("User", {
    description: "User schema generated from the Runpod OpenAPI document.",
  })
);

/**
 * User value generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import type { User } from "@beep/runpod"
 *
 * type UserValue = User
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type User = typeof User.Type;

/**
 * SavingsPlan model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { SavingsPlan } from "@beep/runpod"
 *
 * console.log(SavingsPlan.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class SavingsPlan extends S.Class<SavingsPlan>($I`SavingsPlan`)(
  {
    costPerHr: S.Finite.pipe(S.optionalKey),
    endTime: S.String.pipe(S.optionalKey),
    gpuTypeId: S.String.pipe(S.optionalKey),
    id: S.String.pipe(S.optionalKey),
    podId: S.String.pipe(S.optionalKey),
    startTime: S.String.pipe(S.optionalKey),
  },
  $I.annote("SavingsPlan", {
    description: "SavingsPlan model returned by the Runpod REST API.",
  })
) {}

/**
 * Machine model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { Machine } from "@beep/runpod"
 *
 * console.log(Machine.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class Machine extends S.Class<Machine>($I`Machine`)(
  {
    costPerHr: S.Finite.pipe(S.optionalKey),
    cpuCount: S.Finite.pipe(S.optionalKey),
    cpuType: S.Struct({
      id: S.String.pipe(S.optionalKey),
      displayName: S.String.pipe(S.optionalKey),
      cores: S.Finite.pipe(S.optionalKey),
      threadsPerCore: S.Finite.pipe(S.optionalKey),
      groupId: S.String.pipe(S.optionalKey),
    }).pipe(S.optionalKey),
    cpuTypeId: S.String.pipe(S.optionalKey),
    currentPricePerGpu: S.Finite.pipe(S.optionalKey),
    dataCenterId: S.String.pipe(S.optionalKey),
    diskThroughputMBps: S.Finite.pipe(S.optionalKey),
    gpuAvailable: S.Finite.pipe(S.optionalKey),
    gpuDisplayName: S.String.pipe(S.optionalKey),
    gpuType: S.Struct({
      id: S.String.pipe(S.optionalKey),
      count: S.Finite.pipe(S.optionalKey),
      displayName: S.String.pipe(S.optionalKey),
      securePrice: S.Finite.pipe(S.optionalKey),
      communityPrice: S.Finite.pipe(S.optionalKey),
      oneMonthPrice: S.Finite.pipe(S.optionalKey),
      threeMonthPrice: S.Finite.pipe(S.optionalKey),
      sixMonthPrice: S.Finite.pipe(S.optionalKey),
      oneWeekPrice: S.Finite.pipe(S.optionalKey),
      communitySpotPrice: S.Finite.pipe(S.optionalKey),
      secureSpotPrice: S.Finite.pipe(S.optionalKey),
    }).pipe(S.optionalKey),
    gpuTypeId: S.String.pipe(S.optionalKey),
    location: S.String.pipe(S.optionalKey),
    maintenanceEnd: S.String.pipe(S.optionalKey),
    maintenanceNote: S.String.pipe(S.optionalKey),
    maintenanceStart: S.String.pipe(S.optionalKey),
    maxDownloadSpeedMbps: S.Finite.pipe(S.optionalKey),
    maxUploadSpeedMbps: S.Finite.pipe(S.optionalKey),
    minPodGpuCount: S.Finite.pipe(S.optionalKey),
    note: S.String.pipe(S.optionalKey),
    secureCloud: S.Boolean.pipe(S.optionalKey),
    supportPublicIp: S.Boolean.pipe(S.optionalKey),
  },
  $I.annote("Machine", {
    description: "Machine model returned by the Runpod REST API.",
  })
) {}

/**
 * DataCenter model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { DataCenter } from "@beep/runpod"
 *
 * console.log(DataCenter.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class DataCenter extends S.Class<DataCenter>($I`DataCenter`)(
  {
    id: S.String.pipe(S.optionalKey),
  },
  $I.annote("DataCenter", {
    description: "DataCenter model returned by the Runpod REST API.",
  })
) {}

/**
 * UnauthorizedError model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { UnauthorizedError } from "@beep/runpod"
 *
 * console.log(UnauthorizedError.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class UnauthorizedError extends S.Class<UnauthorizedError>($I`UnauthorizedError`)(
  {
    message: S.String.pipe(S.optionalKey),
  },
  $I.annote("UnauthorizedError", {
    description: "UnauthorizedError model returned by the Runpod REST API.",
  })
) {}

/**
 * CudaVersions schema generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { CudaVersions } from "@beep/runpod"
 *
 * console.log(CudaVersions.ast)
 * ```
 *
 * @category schemas
 * @since 0.1.0
 */
export const CudaVersions = S.String.pipe(
  $I.annoteSchema("CudaVersions", {
    description: "CudaVersions schema generated from the Runpod OpenAPI document.",
  })
);

/**
 * CudaVersions value generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import type { CudaVersions } from "@beep/runpod"
 *
 * type CudaVersionsValue = CudaVersions
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type CudaVersions = typeof CudaVersions.Type;

/**
 * GPUTypeId schema generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { GPUTypeId } from "@beep/runpod"
 *
 * console.log(GPUTypeId.ast)
 * ```
 *
 * @category schemas
 * @since 0.1.0
 */
export const GPUTypeId = S.String.pipe(
  $I.annoteSchema("GPUTypeId", {
    description: "GPUTypeId schema generated from the Runpod OpenAPI document.",
  })
);

/**
 * GPUTypeId value generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import type { GPUTypeId } from "@beep/runpod"
 *
 * type GPUTypeIdValue = GPUTypeId
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type GPUTypeId = typeof GPUTypeId.Type;

/**
 * ContainerRegistryAuth model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { ContainerRegistryAuth } from "@beep/runpod"
 *
 * console.log(ContainerRegistryAuth.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class ContainerRegistryAuth extends S.Class<ContainerRegistryAuth>($I`ContainerRegistryAuth`)(
  {
    id: S.String.pipe(S.optionalKey),
    name: S.String.pipe(S.optionalKey),
  },
  $I.annote("ContainerRegistryAuth", {
    description: "ContainerRegistryAuth model returned by the Runpod REST API.",
  })
) {}

/**
 * ContainerRegistryAuths schema generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { ContainerRegistryAuths } from "@beep/runpod"
 *
 * console.log(ContainerRegistryAuths.ast)
 * ```
 *
 * @category schemas
 * @since 0.1.0
 */
export const ContainerRegistryAuths = S.suspend(() => ContainerRegistryAuth).pipe(
  S.Array,
  $I.annoteSchema("ContainerRegistryAuths", {
    description: "ContainerRegistryAuths schema generated from the Runpod OpenAPI document.",
  })
);

/**
 * ContainerRegistryAuths value generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import type { ContainerRegistryAuths } from "@beep/runpod"
 *
 * type ContainerRegistryAuthsValue = ContainerRegistryAuths
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type ContainerRegistryAuths = typeof ContainerRegistryAuths.Type;

/**
 * ContainerRegistryAuthCreateInput model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { ContainerRegistryAuthCreateInput } from "@beep/runpod"
 *
 * console.log(ContainerRegistryAuthCreateInput.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class ContainerRegistryAuthCreateInput extends S.Class<ContainerRegistryAuthCreateInput>(
  $I`ContainerRegistryAuthCreateInput`
)(
  {
    name: S.String,
    password: S.String,
    username: S.String,
  },
  $I.annote("ContainerRegistryAuthCreateInput", {
    description: "ContainerRegistryAuthCreateInput model returned by the Runpod REST API.",
  })
) {}

/**
 * BillingRecord model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { BillingRecord } from "@beep/runpod"
 *
 * console.log(BillingRecord.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class BillingRecord extends S.Class<BillingRecord>($I`BillingRecord`)(
  {
    amount: S.Finite.pipe(S.optionalKey),
    diskSpaceBilledGb: S.Finite.pipe(S.optionalKey),
    endpointId: S.String.pipe(S.optionalKey),
    gpuTypeId: S.String.pipe(S.optionalKey),
    podId: S.String.pipe(S.optionalKey),
    time: S.String.pipe(S.optionalKey),
    timeBilledMs: S.Finite.pipe(S.optionalKey),
  },
  $I.annote("BillingRecord", {
    description: "BillingRecord model returned by the Runpod REST API.",
  })
) {}

/**
 * BillingRecords schema generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { BillingRecords } from "@beep/runpod"
 *
 * console.log(BillingRecords.ast)
 * ```
 *
 * @category schemas
 * @since 0.1.0
 */
export const BillingRecords = pipe(
  S.Struct({
    amount: S.Finite.pipe(S.optionalKey),
    diskSpaceBilledGb: S.Finite.pipe(S.optionalKey),
    endpointId: S.String.pipe(S.optionalKey),
    gpuTypeId: S.String.pipe(S.optionalKey),
    podId: S.String.pipe(S.optionalKey),
    time: S.String.pipe(S.optionalKey),
    timeBilledMs: S.Finite.pipe(S.optionalKey),
  }),
  S.Array,
  $I.annoteSchema("BillingRecords", {
    description: "BillingRecords schema generated from the Runpod OpenAPI document.",
  })
);

/**
 * BillingRecords value generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import type { BillingRecords } from "@beep/runpod"
 *
 * type BillingRecordsValue = BillingRecords
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type BillingRecords = typeof BillingRecords.Type;

/**
 * NetworkVolumeBillingRecord model returned by the Runpod REST API.
 *
 * @example
 * ```ts
 * import { NetworkVolumeBillingRecord } from "@beep/runpod"
 *
 * console.log(NetworkVolumeBillingRecord.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class NetworkVolumeBillingRecord extends S.Class<NetworkVolumeBillingRecord>($I`NetworkVolumeBillingRecord`)(
  {
    amount: S.Finite.pipe(S.optionalKey),
    diskSpaceBilledGb: S.Finite.pipe(S.optionalKey),
    highPerformanceStorageAmount: S.Finite.pipe(S.optionalKey),
    highPerformanceStorageDiskSpaceBilledGb: S.Finite.pipe(S.optionalKey),
    time: S.String.pipe(S.optionalKey),
  },
  $I.annote("NetworkVolumeBillingRecord", {
    description: "NetworkVolumeBillingRecord model returned by the Runpod REST API.",
  })
) {}

/**
 * NetworkVolumeBillingRecords schema generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { NetworkVolumeBillingRecords } from "@beep/runpod"
 *
 * console.log(NetworkVolumeBillingRecords.ast)
 * ```
 *
 * @category schemas
 * @since 0.1.0
 */
export const NetworkVolumeBillingRecords = pipe(
  S.Struct({
    amount: S.Finite.pipe(S.optionalKey),
    diskSpaceBilledGb: S.Finite.pipe(S.optionalKey),
    highPerformanceStorageAmount: S.Finite.pipe(S.optionalKey),
    highPerformanceStorageDiskSpaceBilledGb: S.Finite.pipe(S.optionalKey),
    time: S.String.pipe(S.optionalKey),
  }),
  S.Array,
  $I.annoteSchema("NetworkVolumeBillingRecords", {
    description: "NetworkVolumeBillingRecords schema generated from the Runpod OpenAPI document.",
  })
);

/**
 * NetworkVolumeBillingRecords value generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import type { NetworkVolumeBillingRecords } from "@beep/runpod"
 *
 * type NetworkVolumeBillingRecordsValue = NetworkVolumeBillingRecords
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type NetworkVolumeBillingRecords = typeof NetworkVolumeBillingRecords.Type;

/**
 * Advisory allowedCudaVersions values observed in the checked-in Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { RUNPOD_ALLOWED_CUDA_VERSIONS_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_ALLOWED_CUDA_VERSIONS_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_ALLOWED_CUDA_VERSIONS_VALUES = [
  "13.0",
  "12.9",
  "12.8",
  "12.7",
  "12.6",
  "12.5",
  "12.4",
  "12.3",
  "12.2",
  "12.1",
  "12.0",
  "11.8",
] as const;

/**
 * Advisory cpuFlavorIds values observed in the checked-in Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { RUNPOD_CPU_FLAVOR_IDS_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_CPU_FLAVOR_IDS_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_CPU_FLAVOR_IDS_VALUES = ["cpu3c", "cpu3g", "cpu5c", "cpu5g"] as const;

/**
 * Advisory cpuFlavorPriority values observed in the checked-in Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { RUNPOD_CPU_FLAVOR_PRIORITY_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_CPU_FLAVOR_PRIORITY_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_CPU_FLAVOR_PRIORITY_VALUES = ["availability", "custom"] as const;

/**
 * Advisory cudaVersions values observed in the checked-in Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { RUNPOD_CUDA_VERSIONS_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_CUDA_VERSIONS_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_CUDA_VERSIONS_VALUES = ["12.4", "12.3", "12.2", "12.1", "12.0", "11.8"] as const;

/**
 * Advisory dataCenterId values observed in the checked-in Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { RUNPOD_DATA_CENTER_ID_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_DATA_CENTER_ID_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_DATA_CENTER_ID_VALUES = [
  "EU-RO-1",
  "CA-MTL-1",
  "EU-SE-1",
  "US-IL-1",
  "EUR-IS-1",
  "EU-CZ-1",
  "US-TX-3",
  "EUR-IS-2",
  "US-KS-2",
  "US-GA-2",
  "US-WA-1",
  "US-TX-1",
  "CA-MTL-3",
  "EU-NL-1",
  "US-TX-4",
  "US-CA-2",
  "US-NC-1",
  "OC-AU-1",
  "US-DE-1",
  "EUR-IS-3",
  "CA-MTL-2",
  "AP-JP-1",
  "EUR-NO-1",
  "EU-FR-1",
  "US-KS-3",
  "US-GA-1",
] as const;

/**
 * Advisory dataCenterIds values observed in the checked-in Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { RUNPOD_DATA_CENTER_IDS_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_DATA_CENTER_IDS_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_DATA_CENTER_IDS_VALUES = [
  "EU-RO-1",
  "CA-MTL-1",
  "EU-SE-1",
  "US-IL-1",
  "EUR-IS-1",
  "EU-CZ-1",
  "US-TX-3",
  "EUR-IS-2",
  "US-KS-2",
  "US-GA-2",
  "US-WA-1",
  "US-TX-1",
  "CA-MTL-3",
  "EU-NL-1",
  "US-TX-4",
  "US-CA-2",
  "US-NC-1",
  "OC-AU-1",
  "US-DE-1",
  "EUR-IS-3",
  "CA-MTL-2",
  "AP-JP-1",
  "EUR-NO-1",
  "EU-FR-1",
  "US-KS-3",
  "US-GA-1",
] as const;

/**
 * Advisory dataCenterPriority values observed in the checked-in Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { RUNPOD_DATA_CENTER_PRIORITY_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_DATA_CENTER_PRIORITY_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_DATA_CENTER_PRIORITY_VALUES = ["availability", "custom"] as const;

/**
 * Advisory gpuTypeId values observed in the checked-in Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { RUNPOD_GPU_TYPE_ID_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_GPU_TYPE_ID_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_GPU_TYPE_ID_VALUES = [
  "NVIDIA GeForce RTX 4090",
  "NVIDIA RTX A5000",
  "NVIDIA RTX A4000",
  "NVIDIA GeForce RTX 3090",
  "NVIDIA RTX A6000",
  "NVIDIA A40",
  "NVIDIA RTX A4500",
  "NVIDIA A100 80GB PCIe",
  "NVIDIA L4",
  "NVIDIA RTX 4000 Ada Generation",
  "NVIDIA RTX 6000 Ada Generation",
  "NVIDIA A100-SXM4-80GB",
  "NVIDIA H100 80GB HBM3",
  "NVIDIA L40",
  "NVIDIA H100 PCIe",
  "NVIDIA L40S",
  "NVIDIA GeForce RTX 3080",
  "NVIDIA GeForce RTX 3070",
  "NVIDIA GeForce RTX 3080 Ti",
  "NVIDIA A30",
  "NVIDIA GeForce RTX 4080",
  "NVIDIA RTX A2000",
  "NVIDIA GeForce RTX 3090 Ti",
  "Tesla V100-SXM2-32GB",
  "NVIDIA GeForce RTX 4070 Ti",
  "NVIDIA RTX 4000 SFF Ada Generation",
  "NVIDIA RTX 5000 Ada Generation",
  "Tesla V100-SXM2-16GB",
  "Tesla V100-FHHL-16GB",
  "Tesla V100-PCIE-16GB",
  "NVIDIA RTX 2000 Ada Generation",
  "NVIDIA H100 NVL",
  "AMD Instinct MI300X OAM",
  "NVIDIA A100-SXM4-40GB",
] as const;

/**
 * Advisory gpuTypeIds values observed in the checked-in Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { RUNPOD_GPU_TYPE_IDS_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_GPU_TYPE_IDS_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_GPU_TYPE_IDS_VALUES = [
  "NVIDIA GeForce RTX 4090",
  "NVIDIA A40",
  "NVIDIA RTX A5000",
  "NVIDIA GeForce RTX 5090",
  "NVIDIA H100 80GB HBM3",
  "NVIDIA GeForce RTX 3090",
  "NVIDIA RTX A4500",
  "NVIDIA L40S",
  "NVIDIA H200",
  "NVIDIA L4",
  "NVIDIA RTX 6000 Ada Generation",
  "NVIDIA A100-SXM4-80GB",
  "NVIDIA RTX 4000 Ada Generation",
  "NVIDIA RTX A6000",
  "NVIDIA A100 80GB PCIe",
  "NVIDIA RTX 2000 Ada Generation",
  "NVIDIA RTX A4000",
  "NVIDIA RTX PRO 6000 Blackwell Server Edition",
  "NVIDIA H100 PCIe",
  "NVIDIA H100 NVL",
  "NVIDIA L40",
  "NVIDIA B200",
  "NVIDIA GeForce RTX 3080 Ti",
  "NVIDIA RTX PRO 6000 Blackwell Workstation Edition",
  "NVIDIA GeForce RTX 3080",
  "NVIDIA GeForce RTX 3070",
  "AMD Instinct MI300X OAM",
  "NVIDIA GeForce RTX 4080 SUPER",
  "Tesla V100-PCIE-16GB",
  "Tesla V100-SXM2-32GB",
  "NVIDIA RTX 5000 Ada Generation",
  "NVIDIA GeForce RTX 4070 Ti",
  "NVIDIA RTX 4000 SFF Ada Generation",
  "NVIDIA GeForce RTX 3090 Ti",
  "NVIDIA RTX A2000",
  "NVIDIA GeForce RTX 4080",
  "NVIDIA A30",
  "NVIDIA GeForce RTX 5080",
  "Tesla V100-FHHL-16GB",
  "NVIDIA H200 NVL",
  "Tesla V100-SXM2-16GB",
  "NVIDIA RTX PRO 6000 Blackwell Max-Q Workstation Edition",
  "NVIDIA A5000 Ada",
  "Tesla V100-PCIE-32GB",
  "NVIDIA  RTX A4500",
  "NVIDIA  A30",
  "NVIDIA GeForce RTX 3080TI",
  "Tesla T4",
  "NVIDIA RTX A30",
] as const;

/**
 * Advisory gpuTypePriority values observed in the checked-in Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { RUNPOD_GPU_TYPE_PRIORITY_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_GPU_TYPE_PRIORITY_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_GPU_TYPE_PRIORITY_VALUES = ["availability", "custom"] as const;

/**
 * Advisory minCudaVersion values observed in the checked-in Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { RUNPOD_MIN_CUDA_VERSION_VALUES } from "@beep/runpod"
 *
 * console.log(RUNPOD_MIN_CUDA_VERSION_VALUES)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_MIN_CUDA_VERSION_VALUES = [
  "13.0",
  "12.9",
  "12.8",
  "12.7",
  "12.6",
  "12.5",
  "12.4",
  "12.3",
  "12.2",
  "12.1",
  "12.0",
  "11.8",
] as const;

/**
 * GetOpenAPIStatus200Response schema generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { GetOpenAPIStatus200Response } from "@beep/runpod"
 *
 * console.log(GetOpenAPIStatus200Response.ast)
 * ```
 *
 * @category schemas
 * @since 0.1.0
 */
export const GetOpenAPIStatus200Response = S.Record(S.String, S.Unknown).pipe(
  $I.annoteSchema("GetOpenAPIStatus200Response", {
    description: "GetOpenAPIStatus200Response schema generated from the Runpod OpenAPI document.",
  })
);

/**
 * GetOpenAPIStatus200Response value generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import type { GetOpenAPIStatus200Response } from "@beep/runpod"
 *
 * type GetOpenAPIStatus200ResponseValue = GetOpenAPIStatus200Response
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type GetOpenAPIStatus200Response = typeof GetOpenAPIStatus200Response.Type;

/**
 * GetDocsStatus200TextResponse schema generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import { GetDocsStatus200TextResponse } from "@beep/runpod"
 *
 * console.log(GetDocsStatus200TextResponse.ast)
 * ```
 *
 * @category schemas
 * @since 0.1.0
 */
export const GetDocsStatus200TextResponse = S.String.pipe(
  $I.annoteSchema("GetDocsStatus200TextResponse", {
    description: "GetDocsStatus200TextResponse schema generated from the Runpod OpenAPI document.",
  })
);

/**
 * GetDocsStatus200TextResponse value generated from the Runpod OpenAPI document.
 *
 * @example
 * ```ts
 * import type { GetDocsStatus200TextResponse } from "@beep/runpod"
 *
 * type GetDocsStatus200TextResponseValue = GetDocsStatus200TextResponse
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type GetDocsStatus200TextResponse = typeof GetDocsStatus200TextResponse.Type;

/**
 * Request input for GetOpenAPI.
 *
 * @example
 * ```ts
 * import { GetOpenAPIRequest } from "@beep/runpod"
 *
 * console.log(GetOpenAPIRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class GetOpenAPIRequest extends S.Class<GetOpenAPIRequest>($I`GetOpenAPIRequest`)(
  {},
  $I.annote("GetOpenAPIRequest", {
    description: "Request input for GetOpenAPI.",
  })
) {}

/**
 * Request input for GetDocs.
 *
 * @example
 * ```ts
 * import { GetDocsRequest } from "@beep/runpod"
 *
 * console.log(GetDocsRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class GetDocsRequest extends S.Class<GetDocsRequest>($I`GetDocsRequest`)(
  {},
  $I.annote("GetDocsRequest", {
    description: "Request input for GetDocs.",
  })
) {}

/**
 * Request input for ListPods.
 *
 * @example
 * ```ts
 * import { ListPodsRequest } from "@beep/runpod"
 *
 * console.log(ListPodsRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class ListPodsRequest extends S.Class<ListPodsRequest>($I`ListPodsRequest`)(
  {
    computeType: LiteralKit(["GPU", "CPU"]).pipe(S.optionalKey),
    cpuFlavorId: S.String.pipe(S.Array, S.optionalKey),
    dataCenterId: S.String.pipe(S.Array, S.optionalKey),
    desiredStatus: LiteralKit(["RUNNING", "EXITED", "TERMINATED"]).pipe(S.optionalKey),
    endpointId: S.String.pipe(S.optionalKey),
    gpuTypeId: S.String.pipe(S.Array, S.optionalKey),
    id: S.String.pipe(S.optionalKey),
    imageName: S.String.pipe(S.optionalKey),
    includeMachine: S.Boolean.pipe(S.optionalKey),
    includeNetworkVolume: S.Boolean.pipe(S.optionalKey),
    includeSavingsPlans: S.Boolean.pipe(S.optionalKey),
    includeTemplate: S.Boolean.pipe(S.optionalKey),
    includeWorkers: S.Boolean.pipe(S.optionalKey),
    name: S.String.pipe(S.optionalKey),
    networkVolumeId: S.String.pipe(S.optionalKey),
    templateId: S.String.pipe(S.optionalKey),
  },
  $I.annote("ListPodsRequest", {
    description: "Request input for ListPods.",
  })
) {}

/**
 * Request input for CreatePod.
 *
 * @example
 * ```ts
 * import { CreatePodRequest } from "@beep/runpod"
 *
 * console.log(CreatePodRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class CreatePodRequest extends S.Class<CreatePodRequest>($I`CreatePodRequest`)(
  {
    body: S.suspend(() => PodCreateInput),
  },
  $I.annote("CreatePodRequest", {
    description: "Request input for CreatePod.",
  })
) {}

/**
 * Request input for GetPod.
 *
 * @example
 * ```ts
 * import { GetPodRequest } from "@beep/runpod"
 *
 * console.log(GetPodRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class GetPodRequest extends S.Class<GetPodRequest>($I`GetPodRequest`)(
  {
    includeMachine: S.Boolean.pipe(S.optionalKey),
    includeNetworkVolume: S.Boolean.pipe(S.optionalKey),
    includeSavingsPlans: S.Boolean.pipe(S.optionalKey),
    includeTemplate: S.Boolean.pipe(S.optionalKey),
    includeWorkers: S.Boolean.pipe(S.optionalKey),
    podId: S.String,
  },
  $I.annote("GetPodRequest", {
    description: "Request input for GetPod.",
  })
) {}

/**
 * Request input for UpdatePod.
 *
 * @example
 * ```ts
 * import { UpdatePodRequest } from "@beep/runpod"
 *
 * console.log(UpdatePodRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class UpdatePodRequest extends S.Class<UpdatePodRequest>($I`UpdatePodRequest`)(
  {
    podId: S.String,
    body: S.suspend(() => PodUpdateInput),
  },
  $I.annote("UpdatePodRequest", {
    description: "Request input for UpdatePod.",
  })
) {}

/**
 * Request input for DeletePod.
 *
 * @example
 * ```ts
 * import { DeletePodRequest } from "@beep/runpod"
 *
 * console.log(DeletePodRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class DeletePodRequest extends S.Class<DeletePodRequest>($I`DeletePodRequest`)(
  {
    podId: S.String,
  },
  $I.annote("DeletePodRequest", {
    description: "Request input for DeletePod.",
  })
) {}

/**
 * Request input for UpdatePod.
 *
 * @example
 * ```ts
 * import { UpdatePodViaPostRequest } from "@beep/runpod"
 *
 * console.log(UpdatePodViaPostRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class UpdatePodViaPostRequest extends S.Class<UpdatePodViaPostRequest>($I`UpdatePodViaPostRequest`)(
  {
    podId: S.String,
    body: S.suspend(() => PodUpdateInput),
  },
  $I.annote("UpdatePodViaPostRequest", {
    description: "Request input for UpdatePod.",
  })
) {}

/**
 * Request input for StartPod.
 *
 * @example
 * ```ts
 * import { StartPodRequest } from "@beep/runpod"
 *
 * console.log(StartPodRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class StartPodRequest extends S.Class<StartPodRequest>($I`StartPodRequest`)(
  {
    podId: S.String,
  },
  $I.annote("StartPodRequest", {
    description: "Request input for StartPod.",
  })
) {}

/**
 * Request input for StopPod.
 *
 * @example
 * ```ts
 * import { StopPodRequest } from "@beep/runpod"
 *
 * console.log(StopPodRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class StopPodRequest extends S.Class<StopPodRequest>($I`StopPodRequest`)(
  {
    podId: S.String,
  },
  $I.annote("StopPodRequest", {
    description: "Request input for StopPod.",
  })
) {}

/**
 * Request input for ResetPod.
 *
 * @example
 * ```ts
 * import { ResetPodRequest } from "@beep/runpod"
 *
 * console.log(ResetPodRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class ResetPodRequest extends S.Class<ResetPodRequest>($I`ResetPodRequest`)(
  {
    podId: S.String,
  },
  $I.annote("ResetPodRequest", {
    description: "Request input for ResetPod.",
  })
) {}

/**
 * Request input for RestartPod.
 *
 * @example
 * ```ts
 * import { RestartPodRequest } from "@beep/runpod"
 *
 * console.log(RestartPodRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class RestartPodRequest extends S.Class<RestartPodRequest>($I`RestartPodRequest`)(
  {
    podId: S.String,
  },
  $I.annote("RestartPodRequest", {
    description: "Request input for RestartPod.",
  })
) {}

/**
 * Request input for ListEndpoints.
 *
 * @example
 * ```ts
 * import { ListEndpointsRequest } from "@beep/runpod"
 *
 * console.log(ListEndpointsRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class ListEndpointsRequest extends S.Class<ListEndpointsRequest>($I`ListEndpointsRequest`)(
  {
    includeTemplate: S.Boolean.pipe(S.optionalKey),
    includeWorkers: S.Boolean.pipe(S.optionalKey),
  },
  $I.annote("ListEndpointsRequest", {
    description: "Request input for ListEndpoints.",
  })
) {}

/**
 * Request input for CreateEndpoint.
 *
 * @example
 * ```ts
 * import { CreateEndpointRequest } from "@beep/runpod"
 *
 * console.log(CreateEndpointRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class CreateEndpointRequest extends S.Class<CreateEndpointRequest>($I`CreateEndpointRequest`)(
  {
    body: S.suspend(() => EndpointCreateInput),
  },
  $I.annote("CreateEndpointRequest", {
    description: "Request input for CreateEndpoint.",
  })
) {}

/**
 * Request input for GetEndpoint.
 *
 * @example
 * ```ts
 * import { GetEndpointRequest } from "@beep/runpod"
 *
 * console.log(GetEndpointRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class GetEndpointRequest extends S.Class<GetEndpointRequest>($I`GetEndpointRequest`)(
  {
    endpointId: S.String,
    includeTemplate: S.Boolean.pipe(S.optionalKey),
    includeWorkers: S.Boolean.pipe(S.optionalKey),
  },
  $I.annote("GetEndpointRequest", {
    description: "Request input for GetEndpoint.",
  })
) {}

/**
 * Request input for UpdateEndpoint.
 *
 * @example
 * ```ts
 * import { UpdateEndpointRequest } from "@beep/runpod"
 *
 * console.log(UpdateEndpointRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class UpdateEndpointRequest extends S.Class<UpdateEndpointRequest>($I`UpdateEndpointRequest`)(
  {
    endpointId: S.String,
    body: S.suspend(() => EndpointUpdateInput),
  },
  $I.annote("UpdateEndpointRequest", {
    description: "Request input for UpdateEndpoint.",
  })
) {}

/**
 * Request input for DeleteEndpoint.
 *
 * @example
 * ```ts
 * import { DeleteEndpointRequest } from "@beep/runpod"
 *
 * console.log(DeleteEndpointRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class DeleteEndpointRequest extends S.Class<DeleteEndpointRequest>($I`DeleteEndpointRequest`)(
  {
    endpointId: S.String,
  },
  $I.annote("DeleteEndpointRequest", {
    description: "Request input for DeleteEndpoint.",
  })
) {}

/**
 * Request input for UpdateEndpoint.
 *
 * @example
 * ```ts
 * import { UpdateEndpointViaPostRequest } from "@beep/runpod"
 *
 * console.log(UpdateEndpointViaPostRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class UpdateEndpointViaPostRequest extends S.Class<UpdateEndpointViaPostRequest>(
  $I`UpdateEndpointViaPostRequest`
)(
  {
    endpointId: S.String,
    body: S.suspend(() => EndpointUpdateInput),
  },
  $I.annote("UpdateEndpointViaPostRequest", {
    description: "Request input for UpdateEndpoint.",
  })
) {}

/**
 * Request input for ListTemplates.
 *
 * @example
 * ```ts
 * import { ListTemplatesRequest } from "@beep/runpod"
 *
 * console.log(ListTemplatesRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class ListTemplatesRequest extends S.Class<ListTemplatesRequest>($I`ListTemplatesRequest`)(
  {
    includeEndpointBoundTemplates: S.Boolean.pipe(S.optionalKey),
    includePublicTemplates: S.Boolean.pipe(S.optionalKey),
    includeRunpodTemplates: S.Boolean.pipe(S.optionalKey),
  },
  $I.annote("ListTemplatesRequest", {
    description: "Request input for ListTemplates.",
  })
) {}

/**
 * Request input for CreateTemplate.
 *
 * @example
 * ```ts
 * import { CreateTemplateRequest } from "@beep/runpod"
 *
 * console.log(CreateTemplateRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class CreateTemplateRequest extends S.Class<CreateTemplateRequest>($I`CreateTemplateRequest`)(
  {
    body: S.suspend(() => TemplateCreateInput),
  },
  $I.annote("CreateTemplateRequest", {
    description: "Request input for CreateTemplate.",
  })
) {}

/**
 * Request input for GetTemplate.
 *
 * @example
 * ```ts
 * import { GetTemplateRequest } from "@beep/runpod"
 *
 * console.log(GetTemplateRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class GetTemplateRequest extends S.Class<GetTemplateRequest>($I`GetTemplateRequest`)(
  {
    includeEndpointBoundTemplates: S.Boolean.pipe(S.optionalKey),
    includePublicTemplates: S.Boolean.pipe(S.optionalKey),
    includeRunpodTemplates: S.Boolean.pipe(S.optionalKey),
    templateId: S.String,
  },
  $I.annote("GetTemplateRequest", {
    description: "Request input for GetTemplate.",
  })
) {}

/**
 * Request input for UpdateTemplate.
 *
 * @example
 * ```ts
 * import { UpdateTemplateRequest } from "@beep/runpod"
 *
 * console.log(UpdateTemplateRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class UpdateTemplateRequest extends S.Class<UpdateTemplateRequest>($I`UpdateTemplateRequest`)(
  {
    templateId: S.String,
    body: S.suspend(() => TemplateUpdateInput),
  },
  $I.annote("UpdateTemplateRequest", {
    description: "Request input for UpdateTemplate.",
  })
) {}

/**
 * Request input for DeleteTemplate.
 *
 * @example
 * ```ts
 * import { DeleteTemplateRequest } from "@beep/runpod"
 *
 * console.log(DeleteTemplateRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class DeleteTemplateRequest extends S.Class<DeleteTemplateRequest>($I`DeleteTemplateRequest`)(
  {
    templateId: S.String,
  },
  $I.annote("DeleteTemplateRequest", {
    description: "Request input for DeleteTemplate.",
  })
) {}

/**
 * Request input for UpdateTemplate.
 *
 * @example
 * ```ts
 * import { UpdateTemplateViaPostRequest } from "@beep/runpod"
 *
 * console.log(UpdateTemplateViaPostRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class UpdateTemplateViaPostRequest extends S.Class<UpdateTemplateViaPostRequest>(
  $I`UpdateTemplateViaPostRequest`
)(
  {
    templateId: S.String,
    body: S.suspend(() => TemplateUpdateInput),
  },
  $I.annote("UpdateTemplateViaPostRequest", {
    description: "Request input for UpdateTemplate.",
  })
) {}

/**
 * Request input for ListNetworkVolumes.
 *
 * @example
 * ```ts
 * import { ListNetworkVolumesRequest } from "@beep/runpod"
 *
 * console.log(ListNetworkVolumesRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class ListNetworkVolumesRequest extends S.Class<ListNetworkVolumesRequest>($I`ListNetworkVolumesRequest`)(
  {},
  $I.annote("ListNetworkVolumesRequest", {
    description: "Request input for ListNetworkVolumes.",
  })
) {}

/**
 * Request input for CreateNetworkVolume.
 *
 * @example
 * ```ts
 * import { CreateNetworkVolumeRequest } from "@beep/runpod"
 *
 * console.log(CreateNetworkVolumeRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class CreateNetworkVolumeRequest extends S.Class<CreateNetworkVolumeRequest>($I`CreateNetworkVolumeRequest`)(
  {
    body: S.suspend(() => NetworkVolumeCreateInput),
  },
  $I.annote("CreateNetworkVolumeRequest", {
    description: "Request input for CreateNetworkVolume.",
  })
) {}

/**
 * Request input for GetNetworkVolume.
 *
 * @example
 * ```ts
 * import { GetNetworkVolumeRequest } from "@beep/runpod"
 *
 * console.log(GetNetworkVolumeRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class GetNetworkVolumeRequest extends S.Class<GetNetworkVolumeRequest>($I`GetNetworkVolumeRequest`)(
  {
    networkVolumeId: S.String,
  },
  $I.annote("GetNetworkVolumeRequest", {
    description: "Request input for GetNetworkVolume.",
  })
) {}

/**
 * Request input for UpdateNetworkVolume.
 *
 * @example
 * ```ts
 * import { UpdateNetworkVolumeRequest } from "@beep/runpod"
 *
 * console.log(UpdateNetworkVolumeRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class UpdateNetworkVolumeRequest extends S.Class<UpdateNetworkVolumeRequest>($I`UpdateNetworkVolumeRequest`)(
  {
    networkVolumeId: S.String,
    body: S.suspend(() => NetworkVolumeUpdateInput),
  },
  $I.annote("UpdateNetworkVolumeRequest", {
    description: "Request input for UpdateNetworkVolume.",
  })
) {}

/**
 * Request input for DeleteNetworkVolume.
 *
 * @example
 * ```ts
 * import { DeleteNetworkVolumeRequest } from "@beep/runpod"
 *
 * console.log(DeleteNetworkVolumeRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class DeleteNetworkVolumeRequest extends S.Class<DeleteNetworkVolumeRequest>($I`DeleteNetworkVolumeRequest`)(
  {
    networkVolumeId: S.String,
  },
  $I.annote("DeleteNetworkVolumeRequest", {
    description: "Request input for DeleteNetworkVolume.",
  })
) {}

/**
 * Request input for UpdateNetworkVolume.
 *
 * @example
 * ```ts
 * import { UpdateNetworkVolumeViaPostRequest } from "@beep/runpod"
 *
 * console.log(UpdateNetworkVolumeViaPostRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class UpdateNetworkVolumeViaPostRequest extends S.Class<UpdateNetworkVolumeViaPostRequest>(
  $I`UpdateNetworkVolumeViaPostRequest`
)(
  {
    networkVolumeId: S.String,
    body: S.suspend(() => NetworkVolumeUpdateInput),
  },
  $I.annote("UpdateNetworkVolumeViaPostRequest", {
    description: "Request input for UpdateNetworkVolume.",
  })
) {}

/**
 * Request input for ListContainerRegistryAuths.
 *
 * @example
 * ```ts
 * import { ListContainerRegistryAuthsRequest } from "@beep/runpod"
 *
 * console.log(ListContainerRegistryAuthsRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class ListContainerRegistryAuthsRequest extends S.Class<ListContainerRegistryAuthsRequest>(
  $I`ListContainerRegistryAuthsRequest`
)(
  {},
  $I.annote("ListContainerRegistryAuthsRequest", {
    description: "Request input for ListContainerRegistryAuths.",
  })
) {}

/**
 * Request input for CreateContainerRegistryAuth.
 *
 * @example
 * ```ts
 * import { CreateContainerRegistryAuthRequest } from "@beep/runpod"
 *
 * console.log(CreateContainerRegistryAuthRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class CreateContainerRegistryAuthRequest extends S.Class<CreateContainerRegistryAuthRequest>(
  $I`CreateContainerRegistryAuthRequest`
)(
  {
    body: S.suspend(() => ContainerRegistryAuthCreateInput),
  },
  $I.annote("CreateContainerRegistryAuthRequest", {
    description: "Request input for CreateContainerRegistryAuth.",
  })
) {}

/**
 * Request input for GetContainerRegistryAuth.
 *
 * @example
 * ```ts
 * import { GetContainerRegistryAuthRequest } from "@beep/runpod"
 *
 * console.log(GetContainerRegistryAuthRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class GetContainerRegistryAuthRequest extends S.Class<GetContainerRegistryAuthRequest>(
  $I`GetContainerRegistryAuthRequest`
)(
  {
    containerRegistryAuthId: S.String,
  },
  $I.annote("GetContainerRegistryAuthRequest", {
    description: "Request input for GetContainerRegistryAuth.",
  })
) {}

/**
 * Request input for DeleteContainerRegistryAuth.
 *
 * @example
 * ```ts
 * import { DeleteContainerRegistryAuthRequest } from "@beep/runpod"
 *
 * console.log(DeleteContainerRegistryAuthRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class DeleteContainerRegistryAuthRequest extends S.Class<DeleteContainerRegistryAuthRequest>(
  $I`DeleteContainerRegistryAuthRequest`
)(
  {
    containerRegistryAuthId: S.String,
  },
  $I.annote("DeleteContainerRegistryAuthRequest", {
    description: "Request input for DeleteContainerRegistryAuth.",
  })
) {}

/**
 * Request input for PodBilling.
 *
 * @example
 * ```ts
 * import { PodBillingRequest } from "@beep/runpod"
 *
 * console.log(PodBillingRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class PodBillingRequest extends S.Class<PodBillingRequest>($I`PodBillingRequest`)(
  {
    bucketSize: LiteralKit(["hour", "day", "week", "month", "year"]).pipe(S.optionalKey),
    endTime: S.String.pipe(S.optionalKey),
    gpuTypeId: S.String.pipe(S.optionalKey),
    grouping: LiteralKit(["podId", "gpuTypeId"]).pipe(S.optionalKey),
    podId: S.String.pipe(S.optionalKey),
    startTime: S.String.pipe(S.optionalKey),
  },
  $I.annote("PodBillingRequest", {
    description: "Request input for PodBilling.",
  })
) {}

/**
 * Request input for EndpointBilling.
 *
 * @example
 * ```ts
 * import { EndpointBillingRequest } from "@beep/runpod"
 *
 * console.log(EndpointBillingRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class EndpointBillingRequest extends S.Class<EndpointBillingRequest>($I`EndpointBillingRequest`)(
  {
    bucketSize: LiteralKit(["hour", "day", "week", "month", "year"]).pipe(S.optionalKey),
    dataCenterId: S.String.pipe(S.Array, S.optionalKey),
    endpointId: S.String.pipe(S.optionalKey),
    endTime: S.String.pipe(S.optionalKey),
    gpuTypeId: S.String.pipe(S.Array, S.optionalKey),
    grouping: LiteralKit(["endpointId", "podId", "gpuTypeId"]).pipe(S.optionalKey),
    imageName: S.String.pipe(S.optionalKey),
    startTime: S.String.pipe(S.optionalKey),
    templateId: S.String.pipe(S.optionalKey),
  },
  $I.annote("EndpointBillingRequest", {
    description: "Request input for EndpointBilling.",
  })
) {}

/**
 * Request input for NetworkVolumeBilling.
 *
 * @example
 * ```ts
 * import { NetworkVolumeBillingRequest } from "@beep/runpod"
 *
 * console.log(NetworkVolumeBillingRequest.ast)
 * ```
 *
 * @category dtos
 * @since 0.1.0
 */
export class NetworkVolumeBillingRequest extends S.Class<NetworkVolumeBillingRequest>($I`NetworkVolumeBillingRequest`)(
  {
    bucketSize: LiteralKit(["hour", "day", "week", "month", "year"]).pipe(S.optionalKey),
    endTime: S.String.pipe(S.optionalKey),
    startTime: S.String.pipe(S.optionalKey),
  },
  $I.annote("NetworkVolumeBillingRequest", {
    description: "Request input for NetworkVolumeBilling.",
  })
) {}

/**
 * Supported Runpod HTTP methods.
 *
 * @example
 * ```ts
 * import { RunpodHttpMethod } from "@beep/runpod"
 *
 * console.log(RunpodHttpMethod.ast)
 * ```
 *
 * @category schemas
 * @since 0.1.0
 */
export const RunpodHttpMethod = LiteralKit(["GET", "POST", "PATCH", "DELETE"]);

/**
 * Supported Runpod HTTP method.
 *
 * @example
 * ```ts
 * import type { RunpodHttpMethod } from "@beep/runpod"
 *
 * type Method = RunpodHttpMethod
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type RunpodHttpMethod = typeof RunpodHttpMethod.Type;

/**
 * Operation ids exposed by Runpod REST API v1.
 *
 * @example
 * ```ts
 * import { RunpodOperationId } from "@beep/runpod"
 *
 * console.log(RunpodOperationId.ast)
 * ```
 *
 * @category schemas
 * @since 0.1.0
 */
export const RunpodOperationId = LiteralKit([
  "GetOpenAPI",
  "GetDocs",
  "ListPods",
  "CreatePod",
  "GetPod",
  "UpdatePod",
  "DeletePod",
  "StartPod",
  "StopPod",
  "ResetPod",
  "RestartPod",
  "ListEndpoints",
  "CreateEndpoint",
  "GetEndpoint",
  "UpdateEndpoint",
  "DeleteEndpoint",
  "ListTemplates",
  "CreateTemplate",
  "GetTemplate",
  "UpdateTemplate",
  "DeleteTemplate",
  "ListNetworkVolumes",
  "CreateNetworkVolume",
  "GetNetworkVolume",
  "UpdateNetworkVolume",
  "DeleteNetworkVolume",
  "ListContainerRegistryAuths",
  "CreateContainerRegistryAuth",
  "GetContainerRegistryAuth",
  "DeleteContainerRegistryAuth",
  "PodBilling",
  "EndpointBilling",
  "NetworkVolumeBilling",
]);

/**
 * Operation id exposed by Runpod REST API v1.
 *
 * @example
 * ```ts
 * import type { RunpodOperationId } from "@beep/runpod"
 *
 * type OperationId = RunpodOperationId
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type RunpodOperationId = typeof RunpodOperationId.Type;

/**
 * Request body encoding used by a Runpod operation.
 *
 * @example
 * ```ts
 * import { RunpodRequestBodyKind } from "@beep/runpod"
 *
 * console.log(RunpodRequestBodyKind.ast)
 * ```
 *
 * @category schemas
 * @since 0.1.0
 */
export const RunpodRequestBodyKind = LiteralKit(["json", "none"]);

/**
 * Request body encoding used by a Runpod operation.
 *
 * @example
 * ```ts
 * import type { RunpodRequestBodyKind } from "@beep/runpod"
 *
 * type RequestBodyKind = RunpodRequestBodyKind
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type RunpodRequestBodyKind = typeof RunpodRequestBodyKind.Type;

/**
 * Response body decoding used by a Runpod operation.
 *
 * @example
 * ```ts
 * import { RunpodResponseBodyKind } from "@beep/runpod"
 *
 * console.log(RunpodResponseBodyKind.ast)
 * ```
 *
 * @category schemas
 * @since 0.1.0
 */
export const RunpodResponseBodyKind = LiteralKit(["json", "none", "text"]);

/**
 * Response body decoding used by a Runpod operation.
 *
 * @example
 * ```ts
 * import type { RunpodResponseBodyKind } from "@beep/runpod"
 *
 * type ResponseBodyKind = RunpodResponseBodyKind
 * ```
 *
 * @category type-level
 * @since 0.1.0
 */
export type RunpodResponseBodyKind = typeof RunpodResponseBodyKind.Type;

/**
 * Static metadata for one Runpod REST operation.
 *
 * @example
 * ```ts
 * import { RunpodOperationDescriptor } from "@beep/runpod"
 *
 * console.log(RunpodOperationDescriptor.ast)
 * ```
 *
 * @category models
 * @since 0.1.0
 */
export class RunpodOperationDescriptor extends S.Class<RunpodOperationDescriptor>($I`RunpodOperationDescriptor`)(
  {
    authenticated: S.Boolean,
    method: RunpodHttpMethod,
    methodName: S.String,
    operationId: RunpodOperationId,
    path: S.String,
    pathParams: S.Array(S.String),
    queryParams: S.Array(S.String),
    requestBody: RunpodRequestBodyKind,
    requestBodyRequired: S.Boolean,
    responseBody: RunpodResponseBodyKind,
    status: S.String,
  },
  $I.annote("RunpodOperationDescriptor", {
    description: "Static metadata for one Runpod REST operation.",
  })
) {}

/**
 * Descriptor for GetOpenAPI.
 *
 * @example
 * ```ts
 * import { getOpenAPIOperation } from "@beep/runpod"
 *
 * console.log(getOpenAPIOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const getOpenAPIOperation = RunpodOperationDescriptor.make({
  authenticated: false,
  method: "GET",
  methodName: "getOpenAPI",
  operationId: "GetOpenAPI",
  path: "/openapi.json",
  pathParams: [],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for GetDocs.
 *
 * @example
 * ```ts
 * import { getDocsOperation } from "@beep/runpod"
 *
 * console.log(getDocsOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const getDocsOperation = RunpodOperationDescriptor.make({
  authenticated: false,
  method: "GET",
  methodName: "getDocs",
  operationId: "GetDocs",
  path: "/docs",
  pathParams: [],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "text",
  status: "200",
});

/**
 * Descriptor for ListPods.
 *
 * @example
 * ```ts
 * import { listPodsOperation } from "@beep/runpod"
 *
 * console.log(listPodsOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const listPodsOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "listPods",
  operationId: "ListPods",
  path: "/pods",
  pathParams: [],
  queryParams: [
    "computeType",
    "cpuFlavorId",
    "dataCenterId",
    "desiredStatus",
    "endpointId",
    "gpuTypeId",
    "id",
    "imageName",
    "includeMachine",
    "includeNetworkVolume",
    "includeSavingsPlans",
    "includeTemplate",
    "includeWorkers",
    "name",
    "networkVolumeId",
    "templateId",
  ],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for CreatePod.
 *
 * @example
 * ```ts
 * import { createPodOperation } from "@beep/runpod"
 *
 * console.log(createPodOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const createPodOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "createPod",
  operationId: "CreatePod",
  path: "/pods",
  pathParams: [],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "201",
});

/**
 * Descriptor for GetPod.
 *
 * @example
 * ```ts
 * import { getPodOperation } from "@beep/runpod"
 *
 * console.log(getPodOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const getPodOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "getPod",
  operationId: "GetPod",
  path: "/pods/{podId}",
  pathParams: ["podId"],
  queryParams: ["includeMachine", "includeNetworkVolume", "includeSavingsPlans", "includeTemplate", "includeWorkers"],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for UpdatePod.
 *
 * @example
 * ```ts
 * import { updatePodOperation } from "@beep/runpod"
 *
 * console.log(updatePodOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const updatePodOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "PATCH",
  methodName: "updatePod",
  operationId: "UpdatePod",
  path: "/pods/{podId}",
  pathParams: ["podId"],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for DeletePod.
 *
 * @example
 * ```ts
 * import { deletePodOperation } from "@beep/runpod"
 *
 * console.log(deletePodOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const deletePodOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "DELETE",
  methodName: "deletePod",
  operationId: "DeletePod",
  path: "/pods/{podId}",
  pathParams: ["podId"],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "none",
  status: "204",
});

/**
 * Descriptor for UpdatePod.
 *
 * @example
 * ```ts
 * import { updatePodViaPostOperation } from "@beep/runpod"
 *
 * console.log(updatePodViaPostOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const updatePodViaPostOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "updatePodViaPost",
  operationId: "UpdatePod",
  path: "/pods/{podId}/update",
  pathParams: ["podId"],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for StartPod.
 *
 * @example
 * ```ts
 * import { startPodOperation } from "@beep/runpod"
 *
 * console.log(startPodOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const startPodOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "startPod",
  operationId: "StartPod",
  path: "/pods/{podId}/start",
  pathParams: ["podId"],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "none",
  status: "200",
});

/**
 * Descriptor for StopPod.
 *
 * @example
 * ```ts
 * import { stopPodOperation } from "@beep/runpod"
 *
 * console.log(stopPodOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const stopPodOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "stopPod",
  operationId: "StopPod",
  path: "/pods/{podId}/stop",
  pathParams: ["podId"],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "none",
  status: "200",
});

/**
 * Descriptor for ResetPod.
 *
 * @example
 * ```ts
 * import { resetPodOperation } from "@beep/runpod"
 *
 * console.log(resetPodOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const resetPodOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "resetPod",
  operationId: "ResetPod",
  path: "/pods/{podId}/reset",
  pathParams: ["podId"],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "none",
  status: "200",
});

/**
 * Descriptor for RestartPod.
 *
 * @example
 * ```ts
 * import { restartPodOperation } from "@beep/runpod"
 *
 * console.log(restartPodOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const restartPodOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "restartPod",
  operationId: "RestartPod",
  path: "/pods/{podId}/restart",
  pathParams: ["podId"],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "none",
  status: "400",
});

/**
 * Descriptor for ListEndpoints.
 *
 * @example
 * ```ts
 * import { listEndpointsOperation } from "@beep/runpod"
 *
 * console.log(listEndpointsOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const listEndpointsOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "listEndpoints",
  operationId: "ListEndpoints",
  path: "/endpoints",
  pathParams: [],
  queryParams: ["includeTemplate", "includeWorkers"],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for CreateEndpoint.
 *
 * @example
 * ```ts
 * import { createEndpointOperation } from "@beep/runpod"
 *
 * console.log(createEndpointOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const createEndpointOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "createEndpoint",
  operationId: "CreateEndpoint",
  path: "/endpoints",
  pathParams: [],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for GetEndpoint.
 *
 * @example
 * ```ts
 * import { getEndpointOperation } from "@beep/runpod"
 *
 * console.log(getEndpointOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const getEndpointOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "getEndpoint",
  operationId: "GetEndpoint",
  path: "/endpoints/{endpointId}",
  pathParams: ["endpointId"],
  queryParams: ["includeTemplate", "includeWorkers"],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for UpdateEndpoint.
 *
 * @example
 * ```ts
 * import { updateEndpointOperation } from "@beep/runpod"
 *
 * console.log(updateEndpointOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const updateEndpointOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "PATCH",
  methodName: "updateEndpoint",
  operationId: "UpdateEndpoint",
  path: "/endpoints/{endpointId}",
  pathParams: ["endpointId"],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for DeleteEndpoint.
 *
 * @example
 * ```ts
 * import { deleteEndpointOperation } from "@beep/runpod"
 *
 * console.log(deleteEndpointOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const deleteEndpointOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "DELETE",
  methodName: "deleteEndpoint",
  operationId: "DeleteEndpoint",
  path: "/endpoints/{endpointId}",
  pathParams: ["endpointId"],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "none",
  status: "204",
});

/**
 * Descriptor for UpdateEndpoint.
 *
 * @example
 * ```ts
 * import { updateEndpointViaPostOperation } from "@beep/runpod"
 *
 * console.log(updateEndpointViaPostOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const updateEndpointViaPostOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "updateEndpointViaPost",
  operationId: "UpdateEndpoint",
  path: "/endpoints/{endpointId}/update",
  pathParams: ["endpointId"],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for ListTemplates.
 *
 * @example
 * ```ts
 * import { listTemplatesOperation } from "@beep/runpod"
 *
 * console.log(listTemplatesOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const listTemplatesOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "listTemplates",
  operationId: "ListTemplates",
  path: "/templates",
  pathParams: [],
  queryParams: ["includeEndpointBoundTemplates", "includePublicTemplates", "includeRunpodTemplates"],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for CreateTemplate.
 *
 * @example
 * ```ts
 * import { createTemplateOperation } from "@beep/runpod"
 *
 * console.log(createTemplateOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const createTemplateOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "createTemplate",
  operationId: "CreateTemplate",
  path: "/templates",
  pathParams: [],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for GetTemplate.
 *
 * @example
 * ```ts
 * import { getTemplateOperation } from "@beep/runpod"
 *
 * console.log(getTemplateOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const getTemplateOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "getTemplate",
  operationId: "GetTemplate",
  path: "/templates/{templateId}",
  pathParams: ["templateId"],
  queryParams: ["includeEndpointBoundTemplates", "includePublicTemplates", "includeRunpodTemplates"],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for UpdateTemplate.
 *
 * @example
 * ```ts
 * import { updateTemplateOperation } from "@beep/runpod"
 *
 * console.log(updateTemplateOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const updateTemplateOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "PATCH",
  methodName: "updateTemplate",
  operationId: "UpdateTemplate",
  path: "/templates/{templateId}",
  pathParams: ["templateId"],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for DeleteTemplate.
 *
 * @example
 * ```ts
 * import { deleteTemplateOperation } from "@beep/runpod"
 *
 * console.log(deleteTemplateOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const deleteTemplateOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "DELETE",
  methodName: "deleteTemplate",
  operationId: "DeleteTemplate",
  path: "/templates/{templateId}",
  pathParams: ["templateId"],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "none",
  status: "204",
});

/**
 * Descriptor for UpdateTemplate.
 *
 * @example
 * ```ts
 * import { updateTemplateViaPostOperation } from "@beep/runpod"
 *
 * console.log(updateTemplateViaPostOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const updateTemplateViaPostOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "updateTemplateViaPost",
  operationId: "UpdateTemplate",
  path: "/templates/{templateId}/update",
  pathParams: ["templateId"],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for ListNetworkVolumes.
 *
 * @example
 * ```ts
 * import { listNetworkVolumesOperation } from "@beep/runpod"
 *
 * console.log(listNetworkVolumesOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const listNetworkVolumesOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "listNetworkVolumes",
  operationId: "ListNetworkVolumes",
  path: "/networkvolumes",
  pathParams: [],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for CreateNetworkVolume.
 *
 * @example
 * ```ts
 * import { createNetworkVolumeOperation } from "@beep/runpod"
 *
 * console.log(createNetworkVolumeOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const createNetworkVolumeOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "createNetworkVolume",
  operationId: "CreateNetworkVolume",
  path: "/networkvolumes",
  pathParams: [],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for GetNetworkVolume.
 *
 * @example
 * ```ts
 * import { getNetworkVolumeOperation } from "@beep/runpod"
 *
 * console.log(getNetworkVolumeOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const getNetworkVolumeOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "getNetworkVolume",
  operationId: "GetNetworkVolume",
  path: "/networkvolumes/{networkVolumeId}",
  pathParams: ["networkVolumeId"],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for UpdateNetworkVolume.
 *
 * @example
 * ```ts
 * import { updateNetworkVolumeOperation } from "@beep/runpod"
 *
 * console.log(updateNetworkVolumeOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const updateNetworkVolumeOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "PATCH",
  methodName: "updateNetworkVolume",
  operationId: "UpdateNetworkVolume",
  path: "/networkvolumes/{networkVolumeId}",
  pathParams: ["networkVolumeId"],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for DeleteNetworkVolume.
 *
 * @example
 * ```ts
 * import { deleteNetworkVolumeOperation } from "@beep/runpod"
 *
 * console.log(deleteNetworkVolumeOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const deleteNetworkVolumeOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "DELETE",
  methodName: "deleteNetworkVolume",
  operationId: "DeleteNetworkVolume",
  path: "/networkvolumes/{networkVolumeId}",
  pathParams: ["networkVolumeId"],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "none",
  status: "204",
});

/**
 * Descriptor for UpdateNetworkVolume.
 *
 * @example
 * ```ts
 * import { updateNetworkVolumeViaPostOperation } from "@beep/runpod"
 *
 * console.log(updateNetworkVolumeViaPostOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const updateNetworkVolumeViaPostOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "updateNetworkVolumeViaPost",
  operationId: "UpdateNetworkVolume",
  path: "/networkvolumes/{networkVolumeId}/update",
  pathParams: ["networkVolumeId"],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for ListContainerRegistryAuths.
 *
 * @example
 * ```ts
 * import { listContainerRegistryAuthsOperation } from "@beep/runpod"
 *
 * console.log(listContainerRegistryAuthsOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const listContainerRegistryAuthsOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "listContainerRegistryAuths",
  operationId: "ListContainerRegistryAuths",
  path: "/containerregistryauth",
  pathParams: [],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for CreateContainerRegistryAuth.
 *
 * @example
 * ```ts
 * import { createContainerRegistryAuthOperation } from "@beep/runpod"
 *
 * console.log(createContainerRegistryAuthOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const createContainerRegistryAuthOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "POST",
  methodName: "createContainerRegistryAuth",
  operationId: "CreateContainerRegistryAuth",
  path: "/containerregistryauth",
  pathParams: [],
  queryParams: [],
  requestBody: "json",
  requestBodyRequired: true,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for GetContainerRegistryAuth.
 *
 * @example
 * ```ts
 * import { getContainerRegistryAuthOperation } from "@beep/runpod"
 *
 * console.log(getContainerRegistryAuthOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const getContainerRegistryAuthOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "getContainerRegistryAuth",
  operationId: "GetContainerRegistryAuth",
  path: "/containerregistryauth/{containerRegistryAuthId}",
  pathParams: ["containerRegistryAuthId"],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for DeleteContainerRegistryAuth.
 *
 * @example
 * ```ts
 * import { deleteContainerRegistryAuthOperation } from "@beep/runpod"
 *
 * console.log(deleteContainerRegistryAuthOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const deleteContainerRegistryAuthOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "DELETE",
  methodName: "deleteContainerRegistryAuth",
  operationId: "DeleteContainerRegistryAuth",
  path: "/containerregistryauth/{containerRegistryAuthId}",
  pathParams: ["containerRegistryAuthId"],
  queryParams: [],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "none",
  status: "204",
});

/**
 * Descriptor for PodBilling.
 *
 * @example
 * ```ts
 * import { podBillingOperation } from "@beep/runpod"
 *
 * console.log(podBillingOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const podBillingOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "podBilling",
  operationId: "PodBilling",
  path: "/billing/pods",
  pathParams: [],
  queryParams: ["bucketSize", "endTime", "gpuTypeId", "grouping", "podId", "startTime"],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for EndpointBilling.
 *
 * @example
 * ```ts
 * import { endpointBillingOperation } from "@beep/runpod"
 *
 * console.log(endpointBillingOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const endpointBillingOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "endpointBilling",
  operationId: "EndpointBilling",
  path: "/billing/endpoints",
  pathParams: [],
  queryParams: [
    "bucketSize",
    "dataCenterId",
    "endpointId",
    "endTime",
    "gpuTypeId",
    "grouping",
    "imageName",
    "startTime",
    "templateId",
  ],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Descriptor for NetworkVolumeBilling.
 *
 * @example
 * ```ts
 * import { networkVolumeBillingOperation } from "@beep/runpod"
 *
 * console.log(networkVolumeBillingOperation.path)
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const networkVolumeBillingOperation = RunpodOperationDescriptor.make({
  authenticated: true,
  method: "GET",
  methodName: "networkVolumeBilling",
  operationId: "NetworkVolumeBilling",
  path: "/billing/networkvolumes",
  pathParams: [],
  queryParams: ["bucketSize", "endTime", "startTime"],
  requestBody: "none",
  requestBodyRequired: false,
  responseBody: "json",
  status: "200",
});

/**
 * Generated operation spec table for Runpod service construction.
 *
 * @example
 * ```ts
 * import { RUNPOD_OPERATION_SPECS } from "@beep/runpod"
 *
 * console.log(Object.keys(RUNPOD_OPERATION_SPECS))
 * ```
 *
 * @category constants
 * @since 0.1.0
 */
export const RUNPOD_OPERATION_SPECS = {
  getOpenAPI: {
    descriptor: getOpenAPIOperation,
    request: GetOpenAPIRequest,
    response: GetOpenAPIStatus200Response,
  },
  getDocs: {
    descriptor: getDocsOperation,
    request: GetDocsRequest,
    response: GetDocsStatus200TextResponse,
  },
  listPods: {
    descriptor: listPodsOperation,
    request: ListPodsRequest,
    response: Pods,
  },
  createPod: {
    descriptor: createPodOperation,
    request: CreatePodRequest,
    response: Pod,
  },
  getPod: {
    descriptor: getPodOperation,
    request: GetPodRequest,
    response: Pod,
  },
  updatePod: {
    descriptor: updatePodOperation,
    request: UpdatePodRequest,
    response: Pod,
  },
  deletePod: {
    descriptor: deletePodOperation,
    request: DeletePodRequest,
  },
  updatePodViaPost: {
    descriptor: updatePodViaPostOperation,
    request: UpdatePodViaPostRequest,
    response: Pod,
  },
  startPod: {
    descriptor: startPodOperation,
    request: StartPodRequest,
  },
  stopPod: {
    descriptor: stopPodOperation,
    request: StopPodRequest,
  },
  resetPod: {
    descriptor: resetPodOperation,
    request: ResetPodRequest,
  },
  restartPod: {
    descriptor: restartPodOperation,
    request: RestartPodRequest,
  },
  listEndpoints: {
    descriptor: listEndpointsOperation,
    request: ListEndpointsRequest,
    response: Endpoints,
  },
  createEndpoint: {
    descriptor: createEndpointOperation,
    request: CreateEndpointRequest,
    response: Endpoint,
  },
  getEndpoint: {
    descriptor: getEndpointOperation,
    request: GetEndpointRequest,
    response: Endpoint,
  },
  updateEndpoint: {
    descriptor: updateEndpointOperation,
    request: UpdateEndpointRequest,
    response: Endpoint,
  },
  deleteEndpoint: {
    descriptor: deleteEndpointOperation,
    request: DeleteEndpointRequest,
  },
  updateEndpointViaPost: {
    descriptor: updateEndpointViaPostOperation,
    request: UpdateEndpointViaPostRequest,
    response: Endpoint,
  },
  listTemplates: {
    descriptor: listTemplatesOperation,
    request: ListTemplatesRequest,
    response: Templates,
  },
  createTemplate: {
    descriptor: createTemplateOperation,
    request: CreateTemplateRequest,
    response: Template,
  },
  getTemplate: {
    descriptor: getTemplateOperation,
    request: GetTemplateRequest,
    response: Template,
  },
  updateTemplate: {
    descriptor: updateTemplateOperation,
    request: UpdateTemplateRequest,
    response: Template,
  },
  deleteTemplate: {
    descriptor: deleteTemplateOperation,
    request: DeleteTemplateRequest,
  },
  updateTemplateViaPost: {
    descriptor: updateTemplateViaPostOperation,
    request: UpdateTemplateViaPostRequest,
    response: Template,
  },
  listNetworkVolumes: {
    descriptor: listNetworkVolumesOperation,
    request: ListNetworkVolumesRequest,
    response: NetworkVolumes,
  },
  createNetworkVolume: {
    descriptor: createNetworkVolumeOperation,
    request: CreateNetworkVolumeRequest,
    response: NetworkVolume,
  },
  getNetworkVolume: {
    descriptor: getNetworkVolumeOperation,
    request: GetNetworkVolumeRequest,
    response: NetworkVolume,
  },
  updateNetworkVolume: {
    descriptor: updateNetworkVolumeOperation,
    request: UpdateNetworkVolumeRequest,
    response: NetworkVolume,
  },
  deleteNetworkVolume: {
    descriptor: deleteNetworkVolumeOperation,
    request: DeleteNetworkVolumeRequest,
  },
  updateNetworkVolumeViaPost: {
    descriptor: updateNetworkVolumeViaPostOperation,
    request: UpdateNetworkVolumeViaPostRequest,
    response: NetworkVolume,
  },
  listContainerRegistryAuths: {
    descriptor: listContainerRegistryAuthsOperation,
    request: ListContainerRegistryAuthsRequest,
    response: ContainerRegistryAuths,
  },
  createContainerRegistryAuth: {
    descriptor: createContainerRegistryAuthOperation,
    request: CreateContainerRegistryAuthRequest,
    response: ContainerRegistryAuth,
  },
  getContainerRegistryAuth: {
    descriptor: getContainerRegistryAuthOperation,
    request: GetContainerRegistryAuthRequest,
    response: ContainerRegistryAuth,
  },
  deleteContainerRegistryAuth: {
    descriptor: deleteContainerRegistryAuthOperation,
    request: DeleteContainerRegistryAuthRequest,
  },
  podBilling: {
    descriptor: podBillingOperation,
    request: PodBillingRequest,
    response: BillingRecords,
  },
  endpointBilling: {
    descriptor: endpointBillingOperation,
    request: EndpointBillingRequest,
    response: BillingRecords,
  },
  networkVolumeBilling: {
    descriptor: networkVolumeBillingOperation,
    request: NetworkVolumeBillingRequest,
    response: NetworkVolumeBillingRecords,
  },
};

/**
 * Typed method surface generated from Runpod REST API v1.
 *
 * @example
 * ```ts
 * import type { RunpodOperationsShape } from "@beep/runpod"
 *
 * type Operations = RunpodOperationsShape<never>
 * ```
 *
 * @category services
 * @since 0.1.0
 */
export interface RunpodOperationsShape<E> {
  readonly createContainerRegistryAuth: (
    request: CreateContainerRegistryAuthRequest
  ) => Effect.Effect<ContainerRegistryAuth, E>;
  readonly createEndpoint: (request: CreateEndpointRequest) => Effect.Effect<Endpoint, E>;
  readonly createNetworkVolume: (request: CreateNetworkVolumeRequest) => Effect.Effect<NetworkVolume, E>;
  readonly createPod: (request: CreatePodRequest) => Effect.Effect<Pod, E>;
  readonly createTemplate: (request: CreateTemplateRequest) => Effect.Effect<Template, E>;
  readonly deleteContainerRegistryAuth: (request: DeleteContainerRegistryAuthRequest) => Effect.Effect<void, E>;
  readonly deleteEndpoint: (request: DeleteEndpointRequest) => Effect.Effect<void, E>;
  readonly deleteNetworkVolume: (request: DeleteNetworkVolumeRequest) => Effect.Effect<void, E>;
  readonly deletePod: (request: DeletePodRequest) => Effect.Effect<void, E>;
  readonly deleteTemplate: (request: DeleteTemplateRequest) => Effect.Effect<void, E>;
  readonly endpointBilling: (request?: EndpointBillingRequest) => Effect.Effect<BillingRecords, E>;
  readonly getContainerRegistryAuth: (
    request: GetContainerRegistryAuthRequest
  ) => Effect.Effect<ContainerRegistryAuth, E>;
  readonly getDocs: (request?: GetDocsRequest) => Effect.Effect<string, E>;
  readonly getEndpoint: (request: GetEndpointRequest) => Effect.Effect<Endpoint, E>;
  readonly getNetworkVolume: (request: GetNetworkVolumeRequest) => Effect.Effect<NetworkVolume, E>;
  readonly getOpenAPI: (request?: GetOpenAPIRequest) => Effect.Effect<GetOpenAPIStatus200Response, E>;
  readonly getPod: (request: GetPodRequest) => Effect.Effect<Pod, E>;
  readonly getTemplate: (request: GetTemplateRequest) => Effect.Effect<Template, E>;
  readonly listContainerRegistryAuths: (
    request?: ListContainerRegistryAuthsRequest
  ) => Effect.Effect<ContainerRegistryAuths, E>;
  readonly listEndpoints: (request?: ListEndpointsRequest) => Effect.Effect<Endpoints, E>;
  readonly listNetworkVolumes: (request?: ListNetworkVolumesRequest) => Effect.Effect<NetworkVolumes, E>;
  readonly listPods: (request?: ListPodsRequest) => Effect.Effect<Pods, E>;
  readonly listTemplates: (request?: ListTemplatesRequest) => Effect.Effect<Templates, E>;
  readonly networkVolumeBilling: (
    request?: NetworkVolumeBillingRequest
  ) => Effect.Effect<NetworkVolumeBillingRecords, E>;
  readonly podBilling: (request?: PodBillingRequest) => Effect.Effect<BillingRecords, E>;
  readonly resetPod: (request: ResetPodRequest) => Effect.Effect<void, E>;
  readonly restartPod: (request: RestartPodRequest) => Effect.Effect<void, E>;
  readonly startPod: (request: StartPodRequest) => Effect.Effect<void, E>;
  readonly stopPod: (request: StopPodRequest) => Effect.Effect<void, E>;
  readonly updateEndpoint: (request: UpdateEndpointRequest) => Effect.Effect<Endpoint, E>;
  readonly updateEndpointViaPost: (request: UpdateEndpointViaPostRequest) => Effect.Effect<Endpoint, E>;
  readonly updateNetworkVolume: (request: UpdateNetworkVolumeRequest) => Effect.Effect<NetworkVolume, E>;
  readonly updateNetworkVolumeViaPost: (request: UpdateNetworkVolumeViaPostRequest) => Effect.Effect<NetworkVolume, E>;
  readonly updatePod: (request: UpdatePodRequest) => Effect.Effect<Pod, E>;
  readonly updatePodViaPost: (request: UpdatePodViaPostRequest) => Effect.Effect<Pod, E>;
  readonly updateTemplate: (request: UpdateTemplateRequest) => Effect.Effect<Template, E>;
  readonly updateTemplateViaPost: (request: UpdateTemplateViaPostRequest) => Effect.Effect<Template, E>;
}
