/**
 * Root layout and static metadata for the codedank web app.
 *
 * @since 0.0.0
 * @module
 */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import type { ReactNode } from "react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Static metadata for the codedank web app shell.
 *
 * @category models
 * @since 0.0.0
 */
export const metadata: Metadata = {
  title: "codedank-web",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
};

/**
 * Root HTML layout for the codedank web app.
 *
 * @category constructors
 * @since 0.0.0
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
