/**
 * Web app manifest for the codedank web app shell.
 *
 * @since 0.0.0
 * @module
 */

import type { MetadataRoute } from "next";

/**
 * Returns the static web manifest for codedank web.
 *
 * @category constructors
 * @since 0.0.0
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "codedank-web",
    short_name: "codedank-web",
    description: "Generated by create next app",
    start_url: "/",
    display: "standalone",
    background_color: "#ffffff",
    theme_color: "#ffffff",
    icons: [
      {
        src: "/favicon.ico",
        sizes: "any",
        type: "image/x-icon",
      },
    ],
  };
}
