import type { IToolbarControls } from "../types";

export const toolbarDefaultControls: IToolbarControls = {
  history: ["undo", "redo"],
  blockFormat: ["paragraph", "h1", "h2", "h3", "h4", "h5", "h6", "bullet", "number", "check", "quote", "code"],
  textFormat: [
    "bold",
    "italic",
    "underline",
    "strikethrough",
    "link",
    "code",
    "leftAlign",
    "centerAlign",
    "rightAlign",
  ],
  viewFormat: ["horizontal", "image", "video", "table"],
  codeLanguages: [
    "c",
    "clike",
    "cpp",
    "css",
    "html",
    "java",
    "js",
    "markdown",
    "objc",
    "plain",
    "powershell",
    "py",
    "rust",
    "sql",
    "swift",
    "typescript",
    "xml",
  ],
  clear: ["editor"],
};
